### ISSUE TITLE
Emulationstation Crashes when audio jack is unplugged

### ISSUE THREAD

**Issue by Onysfx** [batocera-linux/batocera-emulationstation#1006]
When there is no audio output device detected in System Settings/Audio Output, it seems emulationstation will crash when opening roms, loading the screensaver, or opening the F1 file manager. The emulators will not load either nor will the file manager (checked TOP). Only had my main batocera dedicated PC, and a older laptop to test which already had built in audio. Ran into the issue just last night, as this was the first time I unplugged the audio jack and ran without one in.

Build: Batocera v32 stable, x86_64
Specs: Intel Core i5 6500 @3.6Ghz, Nvidia GT1030 2GB GDDR5, 16GB DDR4 RAM

Batocera worked fine on the laptop, so it's not a userdata issue, and it worked fine once the 3.5mm jack was plugged back in. It did not even need to be connected to a speaker, so long as it was plugged in, Batocera would detect it.

Trying to load the F1 menu with audio jack unplugged:
![F1_menu_with_audio_unplugged](https://user-images.githubusercontent.com/92001234/136126512-34c08975-35c0-4615-ab3f-b584b3b49b0b.png)

Trying to load a rom with audio jack unplugged:
![N64_game_with_audio_unplugged](https://user-images.githubusercontent.com/92001234/136126607-6594e494-59a4-46bd-8e80-a455335a5775.png)

Trying to create a Batocera support file with audio jack unplugged:
![Batocera_support_file_audio_unplugged](https://user-images.githubusercontent.com/92001234/136126698-d4613086-b1bf-48b2-bcd2-c3b4f6078a6f.png)

All of the above work fine if Batocera detects an audio output.

**Comment by fabricecaruso** [comment]
Very old issue
