### ISSUE TITLE
After exists a Steam game, batocera stucks and can't go back to emulation station

### ISSUE THREAD

**Issue by maioni** [batocera-linux/batocera-emulationstation#1010]
Issue: After exists a Steam game, batocera stucks and can't go back to emulation station

Expected result: After exists a Steam game, batocera goes back to emulation station

Conditions: Steam flatpak installed. A Steam game installed and listed into Steam system (at emulation station)

Reproduction steps: 1. Open a Steam Game (tested with The Binding of Isaac Rebirth)

2. During the game play, exit it or press HOTKEY + START to exit it

3. Batocera stucks, game doesn't exit, and emulation station can't be loaded.

Info: pid: 11809 (maybe it could help) [After the game stucks the pid process is gone too]

Notes: I had to force emulation station to restart with: /etc/init.d/S31emulationstation restart

**Comment by liberodark** [comment]
That have been fixed in v33.
