### ISSUE TITLE
blurry battery icon after ES restart

### ISSUE THREAD

**Issue by dhwz** [batocera-linux/batocera-emulationstation#1027]
I'm using a high-res svg battery icon in my active theme, but it doesn't get used after ES is restarted, it only appears after battery state is changed then the theme battery icon is loaded. Restart ES and the blurry icon is back again, as it always loads the icon from ES resources folder initially.
If you use a completely different Icon in your theme you'll get the wrong one after restart.

Can you please fix that behavior.

**Comment by fabricecaruso** [comment]
Where can we download the theme to test it ?

**Comment by dhwz** [comment]
@fabricecaruso 
Here https://github.com/szalik-rg351/es-theme-art-book-4-3
But I think you can reproduce it with any theme, if you place a different battery icon in resources than in the theme used.

**Comment by fabricecaruso** [comment]
Ok Commited

**Comment by dhwz** [comment]
wow great thx
