### ISSUE TITLE
merging snes-msu into snes

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#1029]
After the merge of both systems I got two Aladdins, two Top Gear 3000. that is not ok. if you want to merge please tag msu games with "[msu-1]" following the name of the game. Otherwise the situation is confusing.

**Comment by fabricecaruso** [comment]
There's an option for that

![image](https://user-images.githubusercontent.com/51082152/140303591-e6e43c86-b2b8-45f7-a981-8ae3c4a8a388.png)
