### ISSUE TITLE
RetroAchievements added for PSP

### ISSUE THREAD

**Issue by wholee** [batocera-linux/batocera-emulationstation#1030]
Hi,

RetroAchievements were added for PSP with this PR:
https://github.com/RetroAchievements/rcheevos/pull/155
along with some other updates.

Can this be added to ES?
https://github.com/batocera-linux/batocera-emulationstation/tree/master/external/libcheevos

It's already added to batocera.linux with this PR:
https://github.com/batocera-linux/batocera.linux/pull/4825

Thank you

**Comment by fabricecaruso** [comment]
Commited. Works only with ISO file format. CSO & PBP formats are not supported.
