### ISSUE TITLE
Batocera-EmulationStation Mac Port, compiled but not working. Open Gl Error

### ISSUE THREAD

**Issue by pablormago** [batocera-linux/batocera-emulationstation#1054]
Hi to everyone, i compiled the old ES 2.1 version on mac and succeded in making it working. But it's to old and without all the improvements batocera's team made.

I tried to compile batocera's ES and it succeded, but it automatically closes just after launch, and throws an OpenGl error: 

/Users/pablojimenez/Github/EmulationStation/Debug/emulationstation ; exit;

Nov 25 16:44:28 lvl0: 	GL error: glGenTextures(1, &texture) failed with error code: 1280

Nov 25 16:44:28 lvl0: 	GL error: glEnable(GL_TEXTURE_2D) failed with error code: 1280

Nov 25 16:44:28 lvl0: 	GL error: glEnableClientState(GL_VERTEX_ARRAY) failed with error code: 1282

Nov 25 16:44:28 lvl0: 	GL error: glEnableClientState(GL_TEXTURE_COORD_ARRAY) failed with error code: 1282

Nov 25 16:44:28 lvl0: 	GL error: glEnableClientState(GL_COLOR_ARRAY) failed with error code: 1282

Nov 25 16:44:28 lvl0: 	Error - File type unknown!

Nov 25 16:44:28 lvl0: 	GL error: glMatrixMode(GL_PROJECTION) failed with error code: 1282

Nov 25 16:44:28 lvl0: 	GL error: glLoadMatrixf((GLfloat*)&_projection) failed with error code: 1282

Assertion failed: (!err), function FontFace, file /Users/pablojimenez/Github/EmulationStation/es-core/src/resources/Font.cpp, line 21.

Abort trap: 6

logout

Saving session...

...copying shared history...

...saving history...truncating history files...

...completed.

Any idea on how to face the error??

Thanks in advance

Pd: i didn't edit any file, just compiled the source as it is

**Comment by fabricecaruso** [comment]
There are 3 possible GL engines GLES, GLES3 & desktopGL when compiling
Try to change using "-DGLES=OFF -DGLES2=OFF -DGL=ON" with cmake or maybe "-DGLES=ON -DGLES2=OFF -DGL=OFF"

If it does not work try to play with thoses lines in the code  :
		SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION ...
		SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION ...
To change the major & minor version to use.

If does not work... I don't use a Mac, so...

**Comment by pablormago** [comment]
Thanks a lot, i will give it a try and post the results!!

**Comment by pablormago** [comment]
Hi @fabricecaruso now it throws this error:

-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SDLMIXER_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/external/libcheevos
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-core
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-core
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-core
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-core
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-core
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-core
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-core
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-core
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-core
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-app
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-app
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-app
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-app
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-app
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-app
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-app
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-app
   used as include directory in directory /Users/pablojimenez/github/batocera-emulationstation/es-app
SDLMIXER_LIBRARY (ADVANCED)
    linked by target "es-core" in directory /Users/pablojimenez/github/batocera-emulationstation/es-core
    linked by target "emulationstation" in directory /Users/pablojimenez/github/batocera-emulationstation/es-app

CMake Warning (dev) in external/libcheevos/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "libcheevos":

    "SDLMIXER_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in external/libcheevos/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "libcheevos":

    "SDLMIXER_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in external/libcheevos/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "libcheevos":

    "SDLMIXER_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in external/libcheevos/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "libcheevos":

    "SDLMIXER_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in external/libcheevos/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "libcheevos":

    "SDLMIXER_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in external/libcheevos/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "libcheevos":

    "SDLMIXER_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in external/libcheevos/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "libcheevos":

    "SDLMIXER_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in external/libcheevos/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "libcheevos":

    "SDLMIXER_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in es-core/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "es-core":

    "SDLMIXER_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in es-core/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of "es-core":

    "SDLMIXER_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in es-app/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "emulationstation":

    "SDLMIXER_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in es-app/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "emulationstation":

    "SDLMIXER_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
