### ISSUE TITLE
Trying to understand automatic gamepad detection

### ISSUE THREAD

**Issue by shantigilbert** [batocera-linux/batocera-emulationstation#106]
First of all thanks for all the hard work on Batocera!

This is not an issue per se, hopefully this is the right place to ask this!

I noticed than your version of ES has a feature that I Would like to implement on the ES version I use (The one from Retropie)

Automatic gamepad detection when you already have another setup. 

if I set my 1st gamepad in Retropie (lets say P1) and I connect another one, I have to go into the menu with P1 and manually go into the setup input screen so I can set up another gamepad, if for any reason I don't have the P1 gamepad connected there is no way to enter the menu until I connect the P1 gamepad and go request the input setup manually, or reboot without the P1 gamepad connected.

In Batocera as soon as I connect a new gamepad I get a nice pop-up asking me if I want to set it up, even if I have P1 disconnected. 

Could you point me in the right direction as to where this happens in the code? or the commit where this was implemented? 

Been trying to do it for a while, but my knowledge of C++ is very limited. 

Thanks!

**Comment by nadenislamarre** [comment]
https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-app/src/views/ViewController.cpp#L374

**Comment by shantigilbert** [comment]
Thank you so much! don't know how I missed that part!
