### ISSUE TITLE
"Release Date" input mask on game's metadata is floating outside the screen when there is no value set

### ISSUE THREAD

**Issue by NeverEatYellowSwissSnow** [batocera-linux/batocera-emulationstation#1066]
When a game's "Release Date" metadata has no entry yet (e.g. before scraping or when there is no "Release Date" set after scraping) and you want to set it manually by using the ES input mask, the input mask is floating outside of the screen so it is not visible to the user. Therefore it is impossible to set a "Release Date" value manually.
**Again: This is really only the case if the game's "Release Date" has no value being set yet!**
![screenshot-2021 10 12-10h08 58](https://user-images.githubusercontent.com/48346793/144743963-3a98d01a-3898-44a9-b9c2-fec1ca3cf1d6.jpg)

**Comment by fabricecaruso** [comment]
done
