### ISSUE TITLE
Q: Show md_image instead of md_video when video not found

### ISSUE THREAD

**Issue by cyberluke** [batocera-linux/batocera-emulationstation#1088]
Hi, currently if no video exists, there is some 'snapshot' video: "not_found" information (based on the theme).

My question is: If video is not present, how can I show the screenshot instead? Can it be done using some XML scripting in Themes or should I fork the project and change something in the code?

I did not find anything in THEMES.MD for scripting.

**Comment by cyberluke** [comment]
I have tried setting `showSnapshotNoVideo` to false, but it does not seem to help (I could check the grid view section in theme one more time)

**Comment by fabricecaruso** [comment]
I need to see the theme to understand

**Comment by cyberluke** [comment]
es-theme-batocer-club-reloaded ...I think I should set showSnapshotNoVideo to true instead of false, is that correct? And snapshot will be a screenshot in this case. The name of property did confuse me a little bit.

**Comment by pajarorrojo** [comment]
Hello cyberluke. This is now possible using binding dynamic variables and the 'exists' filter method:

https://github.com/batocera-linux/batocera-emulationstation/blob/master/THEMES_BINDINGS.md
