### ISSUE TITLE
Emulationstation not full screen/wrong resolution?

### ISSUE THREAD

**Issue by Tryant666** [batocera-linux/batocera-emulationstation#1098]
Issue: Emulationstation is the wrong resolution or not full screen. Sits in the Lower left corner black bar on top and right side.

Expected result: Emulation station in full screen or proper resolution

Reproduction steps: No idea tried it on 2 monitors both have the same problem. First time I was able to fix it by changing the menu driver. Later I rebooted and the problem was back and changing the menu drivers again did nothing.

Logs and data: 
Raspberry Pi 4B 2GB (heatsink and 120mm fan)
32gb samsung 10mb/s microSD card
Version 32 2021/09/20 23:29

[batocera-support-20211231125337.tar.gz](https://github.com/batocera-linux/batocera-emulationstation/files/7796222/batocera-support-20211231125337.tar.gz)

**Comment by fabricecaruso** [comment]
It's not directly related to ES.
Can you close here repost that in batocera.linux repository ?
Thanks
