### ISSUE TITLE
Disable Menu Go by decade

### ISSUE THREAD

**Issue by bobix88** [batocera-linux/batocera-emulationstation#1100]
Hello
I created several categories and suddenly the classification by decade does not make sense.
I would like to disable this menu?
In the same spirit, I would like to deactivate the left and right in the menu which does not add anything, it allows to go from decade to decade but I do not find it useful. In summary, I just wish I could go down or up :)
So I thinks thoses options can be set on batocera.conf in the first time.
Thanks.

**Comment by fabricecaruso** [comment]
What ? Where did you see a "go by decade" menu ? There is no such menu in EmulationStation.
I don't understand what you are talking about.

**Comment by bobix88** [comment]
With system sorted by date, on the systems selections.
This menu appear when we use the BUTTON_BACK
From the code, it's  line 531 on https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-app/src/views/SystemView.cpp

**Comment by fabricecaruso** [comment]
Mmm ok... It's not a menu, but the system navigation bar...
No it can't be disabled. Why do you want to disable it ? 
If you use only custom collections, sort them alphabetically instead, no ?

**Comment by bobix88** [comment]
I want to disable it because I don't need it and I don't like it :)
I do not only use custom collections, that's the problem.
I have a Retro collection, a 1vs1 Collection and others and I have system too like snes, megadrive, ...
With my example, I would like to get in first Retro, then each system order by date and then 1vs1.
I have see that's there a customsort branch on git, maybe it's going to answer what i want.
Anyway, i think it would be a good option to be able to disable this system navigation bar :)
Thanks

**Comment by fabricecaruso** [comment]
If you don't like it, just don't use it. I won't plan to add an option to disable it because 1 user doesn't like it. 
Either, don't press B. Either, disable systems sorting -> There's no bar when there's no sorting.

There's no plan either for sorting custom collections like you ask, either. 
The branch you name is totally about something else...
