### ISSUE TITLE
Screensaver halts if image is missing (minor)

### ISSUE THREAD

**Issue by Hew-ux** [batocera-linux/batocera-emulationstation#1101]
Issue: If the screensaver is running in slideshow mode and comes across an image in the gamelist.xml that is not present on the device, the screensaver will instead show a completely black screen and fail to move onto any other image.

Expected result: To skip over the missing image, or at the least be able to continue the slideshow after showing the black screen.

Reproduction steps:

Install a game and scrape it.
Set the screensaver mode to slideshow.
Manually delete the image file from the share (this can also be done for games that have been removed completely, but the data in gamelist.xml is still present).
Let the screensaver begin.
Eventually, the screensaver will reach the image that is missing and the issue will occur.

No logs describe the situation as it happens.

Workarounds: Going to SYSTEM SETTINGS -> DEVELOPER -> CLEAN GAMELISTS & REMOVE UNUSED MEDIA will fix the gamelists, thus avoiding the issue.

**Comment by fabricecaruso** [comment]
I can't reproduce.
Also : given the code, it looks like it's not be possible. 
There's a condition `if (!Utils::FileSystem::exists(path)) continue;` that would ignore the game and take the next one.

It could happen only if you delete all the images. Is that what you did ?
In this case, it does a black screensaver... And that's a normal bevavihour.

**Comment by Hew-ux** [comment]
Interesting, it seems to be consistently reproducible for me, even across multiple reflashes on multiple platforms. But if you can't reproduce it, then there isn't really much we can do.

Considering this is relatively minor with an easy workaround, shall I just close this issue?

**Comment by Hew-ux** [comment]
Just an update on this, the issue is still present on v35-dev. Even after a flash, if the only thing you do is delete a single image and then let the screensaver play, the issue occurs.

**Comment by fabricecaruso** [comment]
OK PR pending
