### ISSUE TITLE
Scraper not showing most systems and crashes (win32).

### ISSUE THREAD

**Issue by MusicMunkee** [batocera-linux/batocera-emulationstation#1104]
Scraper shows only 2 systems to scrape, but 19 systems are installed. 19 systems were shown on collection setting correctly and can be started correctly.

Scraper crashes on one machine (Ryzen 5600) and just does nothing in intel machine. All in an actual win32 build with actual code from yesterday.

**Comment by fabricecaruso** [comment]
"19 systems were shown on collection" what does that mean ? Your 19 systems are collections ?

**Comment by fabricecaruso** [comment]
No answer : i'm closing
