### ISSUE TITLE
Batocera - TDP issue running on ASUS PN51

### ISSUE THREAD

**Issue by rmd1234** [batocera-linux/batocera-emulationstation#1108]
Sorry for the Noob query
Trying to run Batocera from a SSD on a ASUS PN51.
The AMD 5500u has a TDP limit which I can fix in windows using the AMD tuning utility. (ETA Prime did a great video on this).
But because Batocera is booting directly off the SSD, the tuning utility doesn't kick in.
The ASUS bios are very limited so I can't do much at that level.
Finding that emulation on Batocera is running slower than expected - just need to tweak the APU to speed that back up.
Any help would be very gratefully received.
Thanks!

**Comment by fabricecaruso** [comment]
It's absolutely not related to EmulationStation but to batocera.linux, so I'm closing this : can't help you on this since EmulationStation is just a "launcher" and is platform independant.
Please repost your question in batocera.linux repository, or ask on discord.
