### ISSUE TITLE
ES crashes when plugging in more than 4 controllers

### ISSUE THREAD

**Issue by euston-r** [batocera-linux/batocera-emulationstation#1109]
Batocera 32

I have 2 Ultrastik controllers, 2 xbox one controllers (with dongle) and a wired PS4 controller in my cabinet. No bluetooth.
When plugging in the 5th controller, ES will crash and restart in a non stop loop until the offending controller is removed.
This happens whether the xbox controllers are using the wireless dongle, or wired.
Removing the ultrastiks, allows the 2 xbox controllers and ps4 to work.
Oddly, once this happens, ES will then always crash whenever that 5th controller is plugged in - even if one of the xbox ones are turned off. 
 I can reset this behaviour by  booting a different (clean) USB..  Then it work fine until again I insert a 5th controller.  Note its not the PS4 controller - same happens if the xbox or ultrastiks are 5th.

**Comment by euston-r** [comment]
A couple of things to add - 
1) This is an issue with the PC (x86) version. I can run the pi4 version with the identical hardware (ie, all 5 controllers) no problem.
2) I'm struggling to find the reason for the crash - The error doesnt seem to get logged anywhere I can see.  The only error I can find is the output from the emulationstation executable when run from the commandline and I stick in that 5th controller to force the issue.  The error is :

*** stack smashing detected ***: terminated
/usr/bin/emulationstation-standalone: line 119:  3073 Aborted                 emulationstation --exit-on-reboot-required --windowed ${CUSTOMESOPTIONS}

**Comment by euston-r** [comment]
I have done some further investigation.

I also have 2 sindon lightguns, a mayflash. 2 spinners, and a trackball plugged into the cabinet. I dont use the lightguns, or the mayflash with the pi4. And on the PC they are just plugged in, and not setup yet.
If I unplug one of the lightguns before booting the PC, then there are no crashes at all - I can have all 5 controllers working fine.

If I plug in the 2nd light gun after ES has already completed startup with the 5 controllers active - again, no problem. No crashes. 

So - I think its something to do with the devices - the order, or there's too many, or maybe just a funky device ID due to the fact there are so many - dont know. 

As I havent set the guns up at all as yet, I have no problem leaving one unplugged for now as a work-around..  Let me know if you need any more info.

**Comment by fabricecaruso** [comment]
2 years without new comments on the subject. We consider it solved
