### ISSUE TITLE
typo in /usr/bin/xow-daemon 

### ISSUE THREAD

**Issue by euston-r** [batocera-linux/batocera-emulationstation#1113]
In the x86 version of Batocera - there's a typo in the /usr/bin/xow-daemon script

`#!/usr/bin/env bash

if pregp xow; then
    killall xow
fi
`
I'm pretty sure "pregp" should be "pgrep"   :)

The symptoms of this - it appears to work, but sometimes at boot time - if your controller is on during boot - the xbox controllers wont pair after ES has started. You then have to unplug the dongle and plug it back it - then it works. 

I think its because xow gets started (via xow-daemon) by inetd - then the udev rule will also run xow-daemon - because of the typo, xow doesnt get killed on the 2nd run. xow doesnt like 2 copies running, seems to cause problems, and its random .-sometimes it will be ok, sometimes xow will die completely, sometimes it will stay running, but be non-functional. 

In the code above, I also put a 3 second sleep after the kill to make sure....

For anyone else reading this - make sure you save the overlay (batocera-save-overlay) after fixing the script - or your change will be lost on reboot.

**Comment by fabricecaruso** [comment]
It's absolutely not related to EmulationStation, sorry... This script is not part of EmulationStation !
Please repost in batocera-linux.
