### ISSUE TITLE
Feature Request: X and Y button remap option for inside games menu

### ISSUE THREAD

**Issue by 89carrot** [batocera-linux/batocera-emulationstation#1126]
Good Day, thank you for continuing to support this project!

I was wondering if it'd be possible to give the option remap the X and Y buttons in the game menu. I find (at least for my liking) quick press for search and save state would be better programmed to the long press on each button. And Favourites and Random would be the quick press for X and Y as example.

Thank you

**Comment by fabricecaruso** [comment]
Almost 2 years without new comments.
