### ISSUE TITLE
DuckStation is not picking up 2nd memory card

### ISSUE THREAD

**Issue by jackmaday** [batocera-linux/batocera-emulationstation#1130]
Hey,

**My issue is:** PSX games are not picking up that there is a memory card inserted in slot 2 while using Duckstation.

I am on a pc, everything has been installed correctly, everything is running just fine, but when I use duckstation (not the libretro one) games are not showing that there is a mem card in slot 2.

I’ve tried pressing f1 and editing the config, but it doesn’t change anything. In fact, no settings have produced a different result, and believe me, I’ve tried them all. I reported it in the discord and they said it was for sure a bug.

I am not sure of any logs that would benefit this issue.

Thank you!

**Comment by fabricecaruso** [comment]
It's not related to ES. Please close this issue & reopen a new one in batocera.linux
