### ISSUE TITLE
Sometimes ES does not see gamepad

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#1133]
Since some time (I follow beta) there is an issue with gamepad. Linux kernel sees gamepad -- I checked with https://wiki.batocera.org/diagnose_joysticks_issues via ssh but ES does not. To use gamepad it has to be put in in moment of booting my mini pc intel 64bit. Gamepad is wired (usb) 8bitdo.

**Comment by fabricecaruso** [comment]
- It's not directly related to EmulationStation but to the system and/or SDL
- Nobody make any comment since almost 2 years on this one, maybe it's fine by now.
