### ISSUE TITLE
Screensaver will not stay on (2014 Mac mini)

### ISSUE THREAD

**Issue by revolvingdonut** [batocera-linux/batocera-emulationstation#1136]
When activating the screensaver in ES either manually or by waiting for the timer to expire, Batocera will enter into screensaver mode successfully, but then re-awaken periodically (seemingly at random) even when no one is at the controls and nothing has been touched.

- Occurs whether network is connected or not.
- Occurs whether music is enabled or disabled.
- Occurs regardless of timer value.

I'm running the latest version of Batocera, using a 2014 Mac mini with installation on internal SSD. In case it's relevant, controls are Sanwa Joysticks and arcade buttons plugged into USB encoders, and direct into the Mac mini USB ports.

**Comment by Hew-ux** [comment]
Does this issue still occur if you disconnect the Sanwa Joysticks and arcade buttons from the USB ports?

**Comment by fabricecaruso** [comment]
I'm closing it because :
- It's not related to EmulationStation. If the screensaver exists, it's related to the fact that the system sends an input. So it's related to the system, not emulationstation.
- Almost 2 years without any new comment
