### ISSUE TITLE
Enhancement: Theming: Ability to show descriptive images in theme options

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1142]
Hi @fabricecaruso. Would it be possible to add the ability to show descriptive context images in the theme options or subsets? for example like is showed in the “DECORATION SET” game options (picture). 

![IMG_20220223_232313399](https://user-images.githubusercontent.com/73712202/155421293-7d686fb7-98fa-44fe-b68b-838789449abe.jpg)

Im thinking in coding something like:
```
<subset name="subset-1" displayname="subset 1">
        <include name=“option-1“ displayName=“Option 1“ thumbnail=“/path/to/thumb.png” />
</subset>
```

I think it would be a very powerful addon for themes developing and the UX if we can offer descpritive images or pictograms to clarify some options.

**Comment by Snapouille** [comment]
that would be huge!

**Comment by pajarorrojo** [comment]
Opened a new thread on discord:
https://discord.com/channels/357518249883205632/1151478615712731136/threads/1153710777937690694

**Comment by fabricecaruso** [comment]
Honnestly, no... I won't had this

**Comment by pajarorrojo** [comment]
Ok, It's a shame, I think the UX could be improved. For example, in my theme, the user could see the avatars before selecting one.
