### ISSUE TITLE
Add a new option "download game instructions manual" in game options menu.

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1144]
I think a new option "download game instructions manual" in game options menu would be very useful. This option appears in the same position as "see manual" and only if the game does not have a manual assigned. This option would do a quick scrape only for the manual. I think it could be a great and useful addon.

Thanks again for the hard work!

**Comment by fabricecaruso** [comment]
I don't agree... 
If we add this, when you'll ask for map, for video or for any other medias.
I won't add this.
