### ISSUE TITLE
Please add L1/R1 for page up/down

### ISSUE THREAD

**Issue by dfilskov** [batocera-linux/batocera-emulationstation#1147]
On some devices (like Anbernic's) L2/R2 are harder to reach than L1/R2.

Therefore please allow for L1/R1 to be used for page up/down in the game lists instead of just L2/R2 which are the only way on a controller currently.

**Comment by Hew-ux** [comment]
Just for clarification: right now, L1 and R1 are indeed used for page up and page down respectively. However, L2 and R2 currently only switch systems in the game list, and do not offer the same functionality as page up and page down in vertical option lists.

**Comment by dfilskov** [comment]
That would be geat - but when running 351elec's Emulation Station on an Anbernic RG351MP the L1/R1 buttons do nothing in the game list - and the less reachable L2/R2 are used for page up/down :|

**Comment by Hew-ux** [comment]
You should... probably report that to 351elec's fork and not here. It's clearly a modification that has been made in that fork.

**Comment by dfilskov** [comment]
That's what they told me on Discord :) - I'll ask them again. Thanks!
