### ISSUE TITLE
Exit without rebooting entire system

### ISSUE THREAD

**Issue by CursingOwl** [batocera-linux/batocera-emulationstation#1161]
i'm using bactocera-emulationstation on manjaro, but when i want to exit the only way to do so is alt+f4, if i click on exit the only options are on shutdown or rebooting the entire system.
on windows i don't have the same issue, 
i've done something wrong or there's not an option to exit the frontend lightly on linux?

**Comment by nadenislamarre** [comment]
https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-app/src/guis/GuiMenu.cpp#L3469

i guess you want that.
