### ISSUE TITLE
Game manual not show

### ISSUE THREAD

**Issue by heloisatech** [batocera-linux/batocera-emulationstation#1171]
RPi3, v34
Game manual appears blank in some games

**Comment by fabricecaruso** [comment]
Did you check the Pdf files manually on a PC ?

**Comment by heloisatech** [comment]
> Did you check the Pdf files manually on a PC ?

Yes, open normally

**Comment by heloisatech** [comment]
> Did you check the Pdf files manually on a PC ?

Yes, open normally

**Comment by fabricecaruso** [comment]
Probably a problem with the pdf encoding. Impossible to test without the file.

**Comment by heloisatech** [comment]
@fabricecaruso  There are several manuals that don't open, this is one of them

[Legend of Zelda, The - A Link to the Past (USA)-manual.pdf](https://github.com/batocera-linux/batocera-emulationstation/files/8555598/Legend.of.Zelda.The.-.A.Link.to.the.Past.USA.-manual.pdf)
m

**Comment by heloisatech** [comment]
@fabricecaruso  

![Manual](https://user-images.githubusercontent.com/6962212/165146904-04bf420d-c6b2-4c57-b0c2-87151ee3a906.jpg)

**Comment by fabricecaruso** [comment]
Pdf file is correct.
@nadenislamarre : Did you update pdftoppm with v34 ? It's working fine with retrobat's pdftoppm version.

**Comment by nadenislamarre** [comment]
https://github.com/batocera-linux/buildroot/tree/br2-external/package/poppler

yes. buildroot was updated. and poppler is coming with it.

**Comment by nadenislamarre** [comment]
let me check this issue.

**Comment by nadenislamarre** [comment]
Syntax Error (8163012): Unknown filter 'JPXDecode'
...
  use libopenjpeg2:     no
Warning: You're not compiling any JPX decoder. Some files will fail to display properly.
...
openjpeg dependancy added to es together with poppler to be sure it is selected
...
fixed.

**Comment by nadenislamarre** [comment]
https://github.com/batocera-linux/batocera.linux/pull/6085

**Comment by heloisatech** [comment]
@nadenislamarre  Tks!

**Comment by nadenislamarre** [comment]
please wait the coming next beta to confirm it is ok for you too.

**Comment by heloisatech** [comment]
@nadenislamarre Not working. Raspberry restarts when trying to view the manual

**Comment by nadenislamarre** [comment]
so this is not the same issue ;-)
raspberry number ? reboot is probably a power issue however.

**Comment by heloisatech** [comment]
Raspberry Pi 3

**Comment by heloisatech** [comment]
The same manuals that didn't open, now restart the RPi

**Comment by heloisatech** [comment]
> [batocera-linux/batocera.linux#6085](https://github.com/batocera-linux/batocera.linux/pull/6085)

JPEG or JPEG2000 in this line? @nadenislamarre

**Comment by heloisatech** [comment]
@nadenislamarre It worked with a fresh install. Tks
