### ISSUE TITLE
ES cannot configure some inputs

### ISSUE THREAD

**Issue by dmanlfc** [batocera-linux/batocera-emulationstation#1173]
I have noticed recently ES cannot take certain inputs from controllers, specifically Axis.
For example a Nintendo Switch clone bluetooth controller identified as the "Lic Pro Controller" you cannot configure Joy 1 left (Left Analog Left) & Joy 2 left (Right Analog Left).
Note: Up axis registers fine.

When testing with `sdl2-jstest -t 1` (where 1 is the controller number)
The left / right axis on both sticks are registered fine.

sdl2-jstest -l output:

```
Joystick Name:     'Lic Pro Controller'
Joystick Path:     '/dev/input/event22'
Joystick GUID:     050000004c69632050726f20436f6e00
Joystick Number:    1
Number of Axes:     4
Number of Buttons: 16
Number of Hats:     1
Number of Balls:    0
GameController:
  not a gamepad
Axis code  0:    0
Axis code  1:    1
Axis code  2:    3
Axis code  3:    4
Button code  0:   304
Button code  1:   305
Button code  2:   306
Button code  3:   307
Button code  4:   308
Button code  5:   309
Button code  6:   310
Button code  7:   311
Button code  8:   312
Button code  9:   313
Button code 10:   314
Button code 11:   315
Button code 12:   316
Button code 13:   317
Button code 14:   318
Button code 15:   319
Hat code  0:   -1
```
I have removed all reference to the controller for es_input.cfg etc without any improvements.

**Comment by dmanlfc** [comment]
`dmesg | grep 'Lic Pro'`

[  122.972524] input: Lic Pro Controller as /devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8:1.0/bluetooth/hci1/hci1:1/0005:0000:0000.0006/input/input35
[  122.972615] hid-generic 0005:0000:0000.0006: input,hidraw5: BLUETOOTH HID v0.01 Gamepad [Lic Pro Controller] on 00:15:83:0c:bf:eb

**Comment by dmanlfc** [comment]
Also occurs with the Xbox 360 pad - only Left Analog Left does not register.

**Comment by dmanlfc** [comment]
evtest also registers the inputs on both controllers...

**Comment by nadenislamarre** [comment]
they register, but with evtest, do you see events happen ?

**Comment by dmanlfc** [comment]
When i say register - I mean the events - yes

**Comment by nadenislamarre** [comment]
so, 'Left Analog Left ' => when you move it :
- it is ok in evtest
- it is ok in sdl2-jstest (so sdl)
- and no even display at configuration step in es ?

**Comment by dmanlfc** [comment]
> so, 'Left Analog Left ' => when you move it :
> 
> * it is ok in evtest
> * it is ok in sdl2-jstest (so sdl)
> * and no even display at configuration step in es ?

Correct

**Comment by nadenislamarre** [comment]
i try to reproduce with my xbox360 as told. i can't. for me all is working.
