### ISSUE TITLE
Duplicate Text

### ISSUE THREAD

**Issue by heloisatech** [batocera-linux/batocera-emulationstation#1175]
v34 beta

The text **INTEGER SCALING** appears twice

![IMG_20220427_125502123.jpg](https://user-images.githubusercontent.com/6962212/165560905-393c136e-c118-4c02-b27a-ded1b680b97f.jpg)

**Comment by fabricecaruso** [comment]
@nadenislamarre 
It's declared twice there :
https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulationstation/batocera-es-system/es_features.yml#L190

**Comment by heloisatech** [comment]
@fabricecaruso 

I did a fresh install of v34 and no Integer Scale text is duplicated

**Comment by heloisatech** [comment]
@fabricecaruso 

I did a fresh install of v34 and no Integer Scale text is duplicated

**Comment by heloisatech** [comment]
Probably some problem with my system,  I don't know what could have happened. Tks

**Comment by heloisatech** [comment]
@fabricecaruso  @nadenislamarre 

Integer Scale is duplicated in option per-system configuration. 

In game settings it's ok

**Comment by heloisatech** [comment]
![game options](https://user-images.githubusercontent.com/6962212/166109839-3b7e18d3-6790-4eb7-8778-1c408a6b2775.jpg)

![per system](https://user-images.githubusercontent.com/6962212/166109838-01b5d061-174f-473c-bcce-93e318197dea.jpg)

**Comment by nadenislamarre** [comment]
thanks. removed from the yml file.
