### ISSUE TITLE
Theming: Animated gifs don't work in splash view

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1177]
Hi @fabricecaruso Animated gifs in V34 don't work in the splash view, and this is an ideal place to put an animated gif as a loading spinner, can we fix this please?

Thanks

**Comment by fabricecaruso** [comment]
It will never work in the splash. It would need a complete rewrite to thread things.

**Comment by pajarorrojo** [comment]
Ok understood, a pity...
