### ISSUE TITLE
boot screen progress bar after exit of game

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#1186]
Batocera -- dev version, up to date. Every time I exit any game two things happen:
1. I see boot screen for moment with progress bar
2. I'm not in the system I started game but at the main screen of Batocera.

Both things are annoying.

**Comment by nadenislamarre** [comment]
1. i guess this is for sbc. this is the normal behavior.
2. strange. maybe an option set. which batocera version ?

**Comment by fabricecaruso** [comment]
please, reproduce it, then send es_log.txt and es_log.txt.bak files.
It probably crashed & launched again.

**Comment by mistepien** [comment]
here are these file
[es_log.txt](https://github.com/batocera-linux/batocera-emulationstation/files/8706848/es_log.txt)
[es_log.txt.bak.txt](https://github.com/batocera-linux/batocera-emulationstation/files/8706854/es_log.txt.bak.txt)
s

**Comment by mistepien** [comment]
`[root@batocera /userdata/system]# batocera-check-updates
SSL_INIT
SSL_INIT
Installed:   34 2022/05/14 08:03
Webversion:  33 2022/02/03 21:51
Update URL:  https://updates.batocera.org/x86_64/stable/last
Branch:      STABLE-branch searched
Used arch:   x86_64
Status:      No Update found!
`

**Comment by fabricecaruso** [comment]
Looks like it's crashing when logging "GL exts:" -> It's just a string provided by SDL2. ( this line https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-core/src/renderers/Renderer_GLES20.cpp#L437 )
glGetString(GL_EXTENSIONS) probably returns a value pointing in a bad memory space.

It's certainly not related directly to ES, but to SDL2, or the video driver.

**Comment by mistepien** [comment]
So the bug is even worse. Machine is 100% intel based and it works like a charm with retroarch.

**Comment by mistepien** [comment]
Problem has been automatically solved by moving to kernel 5.18.

**Comment by mistepien** [comment]
Problem has been automatically solved by moving to kernel 5.18.
