### ISSUE TITLE
No audio - Intel Iris Xe graphics

### ISSUE THREAD

**Issue by arianecinco** [batocera-linux/batocera-emulationstation#1187]
I'm booting Batocera from a USB drive on a Samsung Galaxy Pro 360 - Intel Core i7 (1165G7) + Intel Iris XE Graphics, 16 Gb Ram, HD (High Definition) Audio. Dolby Atmos®

I get no sould, I've tried all different audio output and audio profile options, also tried uncommenting #intel-i965-driver=true and still no audio either on front end or in-game on the built-in speakers. I haven't been able to try it over HDMI yet (waiting for a usb-c to HDMI adapter)

I'm also unable to use the touchpad to navigate the folders through the file manager

**Comment by fabricecaruso** [comment]
not related to emulationstation.
Please repost in batocera-linux
