### ISSUE TITLE
Cheevo Scanning Parser Not Detecting All Formats

### ISSUE THREAD

**Issue by chewvodka** [batocera-linux/batocera-emulationstation#1189]
Following up on Atari's suggestion here:
https://discord.com/channels/357518249883205632/357954026916151298/975938505916162068

While it was working on previous builds (v32, v33), the RetroAchievement scanner is no longer detecting ANY compatible ROMs for the PCE-CD/TurboGrafx-CD system.  I'm not sure what ROM format it's looking for but it's very quick to skip over everything I have.  My current ROMSET comes as a Redump Verified bin/cue format.  This has been confirmed by the Discord users hansolo77 (me) and Oddysee.

Dreamcast achievements are also not properly being scanned as compatible.  According to the [announcement thread](http://retroachievements.org/viewtopic.php?t=15276) in the RetroAchievement's forums, Dreamcast support is compatible with ROM formats of BIN/CUE, BIN/GDI, and BIN/RAW/GDI.  I have a "mixed bag" of ROMs that also includes CHD.  It appears that our current system only finds compatible ROM matches that are CHDs.  This is weird because CHD wasn't even officially announced as supported (I verified with the OP Televandalist that they DO in-fact work).  So we have a Parser that is looking for CHD (unofficially supported) but not any other formats (officially supported).

These other formats need to be added into the list of compatible ROM formats to scan for.

**Comment by fabricecaruso** [comment]
I don't know, It works fine for me but I only have CHD files ( for PCE-CD & also for Dreamcast )

**Comment by fabricecaruso** [comment]
Ok, I found by. I have a fix there : https://github.com/batocera-linux/batocera-emulationstation/pull/1190

**Comment by chewvodka** [comment]
Looks like it's partially working now.  PCE-CD/TGCD seem to be working, but Dreamcast still isn't.  Dreamcast is still only finding CHD files, not the others.  It should be able to detect `bin/cue` and `gdi/bin/raw`.  `CDI` and `ISO` are other Dreamcast formats I've seen, but I read that CDI doesn't work with cheevos and I don't have any ISO to test.  Can those other formats be added too?

**Comment by fabricecaruso** [comment]
it should work for bin/cue files, but I can't find any roms using that format & can't test.
gdi/raw/cdi file formats are not supported by the library.
So use chd files instead.

**Comment by fabricecaruso** [comment]
I looked futher in the code. 

There could be a way to make it work with GDI files, but it's complex because it depends on rcheevos (retroachivements) official library. Their "cdreader/hash" api is not thread safe when you need to use another "cdreader" ( for CHD ).

So, It's not possible to implement support for GDI & CHD indexing at the same time without making very big changes...
The only solution would be disable multithreading indexing, but indexing games would be far slower ( up to 4 times slower if you have a 8 threads CPU ).

As soon as it's not possible to switch cdreader in a thread safe way in their library, I won't add support for it, as it concerns only a few dreamcast formats -> use CHDs.

**Comment by chewvodka** [comment]
Makes sense to me.  I'm in no hurry.  RetroArch already supports the format.  So in the interim I've just moved all the unsupported games to an external drive. Doing that, I have a clean list that is all supported.  I just won't be able to see my achievement progress for those games that are undetected until a solution can be found.  Thanks for checking into it though.  I'll keep waiting.  :)
