### ISSUE TITLE
Collections per genre

### ISSUE THREAD

**Issue by heloisatech** [batocera-linux/batocera-emulationstation#1195]
@fabricecaruso Collections by genre don't work, I choose a genre but they don't appear.
Do you intend to fix this error?

v34 last update, RPi3

![IMG_20220524_131307230](https://user-images.githubusercontent.com/6962212/170084293-20061fb0-4371-42a3-a24c-f5285f801bd0.jpg)

**Comment by fabricecaruso** [comment]
Please re-scrap all your games & try again (unless you scraped them recently)
You probably have a problem in your gamelists

**Comment by heloisatech** [comment]
@fabricecaruso They appear when they are ungrouped.
When grouped doesn't appear

**Comment by fabricecaruso** [comment]
When grouped there's a "Collections" collection. Don't you have it ?

**Comment by heloisatech** [comment]
No, don't appear Collections

**Comment by fabricecaruso** [comment]
What if you create some custom collections ?

**Comment by fabricecaruso** [comment]
Ok 
I fixed this & opened a PR for v35

https://github.com/batocera-linux/batocera-emulationstation/pull/1198

**Comment by heloisatech** [comment]
Thanks!

**Comment by maioni** [comment]
@fabricecaruso can you move this issue to https://github.com/batocera-linux/batocera.linux/issues/6122 to emulation-station? It's a simular issue.

**Comment by fabricecaruso** [comment]
@maioni Just proposed a fix for this one too. You can close your original issue
