### ISSUE TITLE
Custom tattoo

### ISSUE THREAD

**Issue by heloisatech** [batocera-linux/batocera-emulationstation#1200]
@fabricecaruso  Hi again! 

**Custom .PNG tattoo** doesn't recognize .PNG file

I chose the **userdata/system** folder for my **.PNG**

In **batocera.conf** it appeared as **mame.bezel.tattoo_file=/userdata/system** and the game stays without bezel

I manually added the logo  **/userdata/system/logo.png** and just like that it appeared, 
but after restart it goes back to **/userdata/system**

**Comment by fabricecaruso** [comment]
The tatoo thing is not related to ES... ( it's just a menu entry for BATOCERA, writing in the conf file )
It's managed by Batocera.linux.
So I can't help.
Please close this & maybe repost to batocera.linux repo
