### ISSUE TITLE
New screensaver mode for arcade cabinets

### ISSUE THREAD

**Issue by FRANCKYNO** [batocera-linux/batocera-emulationstation#1202]
Creating a new screensaver mode dedicated to arcade cabinets would be very interesting. 

The idea is to cycle through the games in the EmulationStation interface randomly like in HyperSpin by moving and spinning quickly and randomly through the list or through the wheel of games and systems and stopping on a game to display game’s marquee, image, video, information available then go to another game.

This mode is really great for an arcade machine that stays on all the time.

@fabricecaruso, @nadenislamarre : do you think it's technically possible to navigate automatically in the ES GUI?

**Comment by fabricecaruso** [comment]
No, sorry. I won't add such a functionnality.
