### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by CursingOwl** [batocera-linux/batocera-emulationstation#1203]
is there a way to compile this version of batocera-emulationstation for linux?
or better yet a linux release?
(the original is wonky can't scrape can't even exit the program without shutting down the entire machine)

**Comment by lbrpdx** [comment]
Batocera is a Linux distribution, so yes, obviously, you can compile Batocera-EmulationStation under Linux. 
You even have the instructions written on the main GitHub page: https://github.com/batocera-linux/batocera-emulationstation#building 

Now, if you want to run it on a different distribution than Batocera or the other retrogaming-oriented Linux distributions that ship with this version of EmulationSttion (Emuelec, Amberelec…) you’ll need to adapt many paths and binaries around it. Everything is in the code, but I’d recommend to stick with a supported Linux distribution that ships EmulationStation in its binary form with it if you don’t know how to do it.

**Comment by Hew-ux** [comment]
@CursingOwl Assuming you're just an end-user who simply wants to use a standalone version of ES, try this out: https://www.es-de.org/

As Lbrpdx said, trying to use Batocera's ES in another system requires a lot of manual setup.
