### ISSUE TITLE
WIN32 - pdftoppm

### ISSUE THREAD

**Issue by psakhis** [batocera-linux/batocera-emulationstation#1219]
Hi,
In WIN32 APISystem can't detect /usr/bin/ for pdftoppm and pdfinfo for PDFEXTRACT.

Where are files supposed to put the executables?

Thx.

**Comment by fabricecaruso** [comment]
/usr/bin/ is a path for linux.
It's a custom setup ?

**Comment by psakhis** [comment]
I'm using your win32 build (with linux works).

I see this code in ApiSystem.cpp and path is hardcoded

```
for (auto executable : executables)
		if (!Utils::FileSystem::exists(**"/usr/bin/"** + executable))
			return false;
```

**Comment by fabricecaruso** [comment]
win32 build on linux ??? Using wine ?

**Comment by psakhis** [comment]
Hello, your release for windows. https://github.com/fabricecaruso/batocera-emulationstation
I'm in W10.
Maybe isn't possible use manual viewer like linux even though pdftoppm and pdfinfo are in win32 as well.

**Comment by fabricecaruso** [comment]
If you are using Windows : use & install retrobat, everything is already set.

**Comment by psakhis** [comment]
Ok thanks, I'll look at it to see if the manual viewer works on retrobat.

**Comment by fabricecaruso** [comment]
it works with retrobat & everything is already set up

**Comment by psakhis** [comment]
nice, thanks for your hard work.
