### ISSUE TITLE
Enhacement : Top 25 ROMs per system

### ISSUE THREAD

**Issue by wadiebs** [batocera-linux/batocera-emulationstation#1222]
Dear All,

ES already offer the feature to create built-in collections such as games per category (i.e. Action, Adventure) or per Publisher (i.e. CPS1,2,3).

I was wondering if built-in collection presenting a top 25 or something per system based on games ranking can be added.

Thank you and best regards

**Comment by fabricecaruso** [comment]
How do you select the Top 25 games, when you have 30000 roms when 5000 have 5 stars ? Randomly !???
Anyway, you can create a dynamic collections filtering games having 5 stars.

**Comment by wadiebs** [comment]
Maybe top 100 per system makes more sense..

I already implement it through dynamic collections, but I think it will be very usefull to add it as a built-in collections. Indeed more easy to activate, and interesting to filter quickly best games per system.

Moreover, having tried the collections regardless of the number of games per system, I can confirm that the results is just great!

**Comment by fabricecaruso** [comment]
sort by desc ? I'm still not convinced...

**Comment by Rose22** [comment]
this would be covered by my suggestion [over here](https://github.com/batocera-linux/batocera-emulationstation/issues/1228), of just adding an option to limit the amount of items shown in a gamelist. wanna add support to that suggestion @wadiebs ?

**Comment by fabricecaruso** [comment]
I'm closing this one as nobody was convinced, and it's getting old without any new suggestions
