### ISSUE TITLE
Theming: Clip -> Stroryboard -> Opacity dont work in some scraped image formats

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1224]
Animation opacity in gamelist events **only has effect on md_image**, not on the rest of scrapped medias, like fanart, thumbnail etc.

In this code example only the md_image works fine:
```
    <control name="md_image, md_thumbnail, md_marquee, md_boxart, md_cartridge, md_fanart, md_titleshot">
      <clipRect>0 0.1 1 0.78</clipRect>

      <storyboard event="open">
        <animation property="opacity" from="1" to="0.2" duration="1500" begin="1200" mode="easeOutCubic" />
      </storyboard>

      <storyboard event="activateNext">
        <animation property="opacity" from="1" to="0.2" duration="1500" begin="1200" mode="easeOutCubic" />
      </storyboard>

      <storyboard event="activatePrev">
        <animation property="opacity" from="1" to="0.2" duration="1500" begin="1200" mode="easeOutCubic" />
      </storyboard>
      
    </control>
```

(FYI) But animations directly without clip events, works on all media
```
      <image name="md_image, md_thumbnail, md_marquee, md_boxart, md_cartridge, md_fanart, md_titleshot">
         <storyboard>
            <animation property="opacity" from="1" from="1" to="0.2" duration="700" mode="easeIn" />
          </storyboard>
      </image>
```

Thanks again for your hard work

**Comment by hoover900** [comment]
what does <clipRect> do? also what is this <control> element? is this something new because it's not in the docs?

**Comment by fabricecaruso** [comment]
<clipRect> allows to clip a control when it's scrolling using offsetY/offsetX -> Parts out of bounds are not visible.
<control> allows to set on or more properties to... multiple controls ( independant from the type text/image/video )

I don't have any problem with opacity. Can you provide a theme where the problem occurs ?

**Comment by pajarorrojo** [comment]
I just did numerous tests on a clean theme and I can't reproduce the problem. I have to investigate why it doesn't work in my theme, it's probably something with the ifSubset conditions that I use to display one type of media or another. My apologies, I leave the issue closed.
