### ISSUE TITLE
please add proper sleep functionality for handhelds

### ISSUE THREAD

**Issue by Rose22** [batocera-linux/batocera-emulationstation#1226]
hi! i'm using an anbernic rg351v running AmberElec, and AmberElec inherits from batocera and so any deep code changes need to be done in batocera instead of amberelec, so i was told to go here.

1. i often find myself putting the thing away, forgetting to press the power button, and then it idles on the menu and drains the battery. im sure im not the only one doing this! so first of all, can we get an auto sleep function as a screensaver option?

2. once it IS in sleep mode, it still seems to drain battery somewhat. miyoo mini running MiniUI will shut down the device completely after it's in sleep mode for a little while. that preserves the battery even more. can that be added?

3. speaking of MiniUI, if you're in a game in MiniUI and press the power button, it'll save the game state, enter sleep mode, (eventually shut down), and then once you power it back on it'll immediately jump back into the game. can we get that?

i also heard that sleep used to be available on amberelec, but was taken out because 351p doesnt support it. well.. 351v does, maybe 351mp too, why remove it for all of them when the only one that cant do it is 351p?

**Comment by MAXXPR0** [comment]
simply agree with ALL you wrote!

i only need to say that on my 351mp power button is SO easy to activate, i often find the handeld active and overheating in the bag, your first suggestion could be a perfect fix!

**Comment by Hew-ux** [comment]
For 1., you could turn on the power saving mode appropriate to your device. That will cause the screen to stop updating until you press a button. However, it isn't as power-saving as a true display time-out would be, which is what you're suggesting.

2. is purely the responsibility of Amberelec. Batocera-EmulationStation does not handle the sleep operations of the operating system itself. It does not help that Batocera itself does not have a sleep mode, therefore there might be hidden bugs that exist.

3. I'm pretty sure this feature already exists, but that's in Batocera.

**Comment by Hew-ux** [comment]
To elaborate on point 3, it could just be that the version of ES being used in Amberelec is just a tiny bit behind Batocera-emulationstation upstream. Unless they've explicitly gone out of their way to disable that, it should appear in one of Amberelec's new betas soon.

**Comment by fabricecaruso** [comment]
1/ I commited something yesterday night about this. I added a new "SUSPEND" option in the screensaver modes.

2 & 3/ It's not EmulationStation responsability to do that, but it's the OS responsability. 

This "issue" is no more a concern for EmulationStation, so this issue is now closed here.
