### ISSUE TITLE
enhancement for handhelds: proper gametime list

### ISSUE THREAD

**Issue by Rose22** [batocera-linux/batocera-emulationstation#1227]
right now, the only way to make a list that shows how long youve played each game is by using a dynamic collection and sorting it by gametime in descending order. 

OnionOS on Miyoo Mini does a great job of this kind of thing:
![](https://user-images.githubusercontent.com/16885275/162589339-e779c6dd-4e9d-47f0-8543-4646d84fc748.png)

the problems with using dynamic collections for this:

1. there is no limit to how big the list can get, which can introduce a bit of lag
2. displaying gametime is dependent on the theme and gamelist view used
3. its not easily available from the system carousel
4. there is no total gametime counter

can we get this properly implemented?

**Comment by fabricecaruso** [comment]
I don't know this OS. It's probably not a gamelist view but some menu. 
Can you provide a full set of screenshots, of how to access this menu ( from the main page to the game activity page ) ?

**Comment by Rose22** [comment]
> I don't know this OS. It's probably not a gamelist view but some menu. Can you provide a full set of screenshots, of how to access this menu ( from the main page to the game activity page ) ?

it's a completely different OS that isn't using emulationstation. there are lots of screenshots of it over here: [https://github.com/jimgraygit/onion](https://github.com/jimgraygit/onion)

**Comment by fabricecaruso** [comment]
it does not show how you access this screen ( if it's a specific screen / per system / global / if it's based on filters / sort) ....

**Comment by Rose22** [comment]
> it does not show how you access this screen ( if it's a specific screen / per system / global / if it's based on filters / sort) ....

on onionOS, it's a specific screen accessed from the main menu. it pulls from all systems (so it's global). it sorts descending based on amount of time played per game (in ES that's md_gametime)

you can see for yourself here: https://www.youtube.com/watch?v=lLiT21Ddnuk

**Comment by Rose22** [comment]
sorry, that video doesnt show it. this one does: https://www.youtube.com/watch?v=oSQUIR_Oir0
it's in the list of apps inside onionOS as "play activity"

**Comment by fabricecaruso** [comment]
it should be enough if we have time after game name, when a system is sorted by gametime like this :
No ?

![image](https://user-images.githubusercontent.com/51082152/177749346-a41156d7-cc73-4fad-84cf-5c289e07f290.png)
