### ISSUE TITLE
enhancements for gamelists

### ISSUE THREAD

**Issue by Rose22** [batocera-linux/batocera-emulationstation#1228]
here are a few simple ideas for gamelists that can greatly help navigation of your library:

1. the ability to save filters applied to gamelists! it would be so nice to save for instance a region filter into a gamelist and have it just always be applied without having to re-apply it every time.
2. the ability to limit how many items in a list are shown. say you have a gamelist sorted by gametime, or times played. if you set the cutoff to 25, the intended function is that the list will still be sorted using the metadata from all games, but will cut off at 25 items, so that it'll show the 25 most played games
3. when sorting by genre, manufacturer, or anything else that isnt numeric, small headers per section like the smalltext in the ES main menu. so that, say, if we sort by genre ascending, the list will be split into sections according to genre, with headers that say what genre the list below it is, and enabling removal of the genre name from the displayed gane name ([Puzzle] Tetris is an example, could be displayed as just Tetris)
4. hotkeys to navigate one letter forward or one letter backward. this would use the first letter of the game name, so say i'm on a game that starts with A, if i press the button to go forward, it would jump me to the first game starting with B

**Comment by nadenislamarre** [comment]
1 => this is dynamic gamelist, no ?

**Comment by fabricecaruso** [comment]
Absolutely wrong... dynamic collections are independant from one to another !!!

**Comment by Rose22** [comment]
1 - i'm not wrong! if "group unthemed custom collections" is enabled, then the filters and sorting order apply across **all** custom and dynamic collections. it's a bug and denying that it exists isn't gonna fix it. if it helps, i'm on AmberELEC (which uses batocera as its base) on an Anbernic rg351v.

2 - let's say you want a list of the top 25 games you've spent the most time in. you *only* want to see 25 items, not any more, *because that would add a lot of clutter and make it harder to navigate and see what's going on*. imagine if every website that does top 10 lists would make their lists 1000 items long. would you want to bother going through the whole thing? wouldn't you get lost in the list and find it hard to see, at a glance, what you were looking for?

there's a nice clean-ness and clarity to a list that has a limited amount of items in it. imagine if your computer desktop had 99999 icons crammed into it, wouldn't be very nice to use, would it?

3 - fair enough

4 - why not add it as an option? so that in the menu, you can set it to scroll by page or scroll by letter

**Comment by fabricecaruso** [comment]
I just checked it AGAIN : Filters are just working fine for dynamic collection & are independant from one collection to another. Sorting is common to the "collections" collection & it's on purpose. 

**_I'm not denying anything : it's a fact._**

About the _"it's a bug and denying that it exists isn't gonna fix it"_
Then fix it yourself and propose a correction !!!!!!!
I'll stay polite : Spend hours of you time working freely, when people have as this respect as they can say sentences like this... mmmm

Anyway : We're not AmberELEC. 
AmberELEC has its own fork with their own changes & their own bevavious ( and maybe bugs ) . 
This repository only concerns **Batocera & Retrobat**. 
If you meet a problem with AmberELEC, please contact them instead.

**Comment by Rose22** [comment]
> I just checked it AGAIN : Filters are just working fine for dynamic collection & are independant from one collection to another. Sorting is common to the "collections" collection & it's on purpose.
> 
> **_I'm not denying anything : it's a fact._**
why are sorting and filters shared across all collections in the "collections" collection? with the way it is now, you can either have all your collections scattered throughout the system carousel, or if you want them neatly grouped together, you can't have the sorting and filters independent anymore. why?..
> 
> About the _"it's a bug and denying that it exists isn't gonna fix it"_ Then fix it yourself and propose a correction !!!!!!! I'll stay polite : Spend hours of you time working freely, when people have as this respect as they can say sentences like this... mmmm
Sorry, you were being very rude yourself (maybe unintentionally?) so i replied back like that. i apologize
> 
> Anyway : We're not AmberELEC. AmberELEC has its own fork with their own changes & their own bevavious ( and maybe bugs ) . This repository only concerns **Batocera & Retrobat**. If you meet a problem with AmberELEC, please contact them instead.
AmberELEC's team always sends people who want to suggest stuff, to batocera and to their github. you may wanna talk to amberelec about it, because if you look in the posted issues on this github, you'll see i'm not the only one asking for stuff for amberelec in batocera's github

**Comment by fabricecaruso** [comment]
Again : **filters are not shared across dynamic collections !** dynamic collections are independant from one to another & it's their initial goal !!!!!

Sorting is applying to the "collections" collection & it's on purpose. It's not gonna change.

We can't do support for AmberELEC. 
They import our features, but have their own fork with their own source code & their own changes.
If they introduced a bug compared to our repository, it's their responsability to fix it.

Dynamic collections are working fine with Batocera.

But maybe you're not talking about **dynamic collections** (they have their own filter) but **editable custom collections** ( filter is common to "collections" collection ).

**Comment by Rose22** [comment]
> Again : **filters are not shared across dynamic collections !** dynamic collections are independant from one to another & it's their initial goal !!!!!

well, on my end, on amberelec, if i turn on "group unthemed custom collections" and edit the sorting or filters of any of the lists inside that system carousel item called "collections", it applies to all the other collections within it as well. so this isn't the case in batocera itself then? wow, i'll take it to amberelec and show them this post so they know it's not in batocera..
> 
> Sorting is applying to the "collections" collection & it's on purpose. It's not gonna change.
> 
> We can't do support for AmberELEC. They import our features, but have their own fork with their own source code & their own changes. If they introduced a bug compared to our repository, it's their responsability to fix it.

they don't want to make any changes inside batocera's code. basically they only add stuff on top of the base batocera code, but they never change anything inside it. so for things like sleep mode functionality, changes in gamelists, new settings in the menu, stuff like that that they would need to edit batocera's source code for... they send us here to this github, hoping you'll make the changes so that they'll flow downstream into amberelec
> 
> Dynamic collections are working fine with Batocera.
> 
> But maybe you're not talking about **dynamic collections** (they have their own filter) but **editable custom collections** ( filter is common to "collections" collection ).
i'm talking about both. this problem applies to both editable custom collections and dynamic collections.. but again, maybe it's only in amberelec, not batocera

**Comment by fabricecaruso** [comment]
I confirm there's a possibility to double filter dynamic collections ( using the dynamic collection filter then appling the  "collections" collection filter ) when there's a custom collection in the list, so there's something in the UI to fix because once you applyed the global filter you can't reset/change it when the result is only with dynamic collections.

Anyway : 
- The "collections" global filter goal is to apply to every child collections of "collections".
- It's different from the dynamic collections mecanism. If we take the initial requirement "the ability to save filters applied to gamelists" exists through dynamic collections.

**Comment by Rose22** [comment]
> I confirm there's a possibility to double filter dynamic collections ( using the dynamic collection filter then appling the "collections" collection filter ) when there's a custom collection in the list, so there's something in the UI to fix because once you applyed the global filter you can't reset/change it when the result is only with dynamic collections.

i don't know what you're talking about with the "collections" collection filter, as i only see the "group unthemed collections"  option and when you turn it on, a new item shows up in the system carousel called "collections" that has all custom collections inside of it. i don't see a filter called "collections"?

i'm talking to amberelec's devs right now and they are saying their code is basically 99% batocera, with a few menu options added on top. so it doesn't make sense that this bug would exist in amberelec but not in batocera...
> 
> Anyway :
> 
> * The "collections" global filter goal is to apply to every child collections of "collections".
> * It's different from the dynamic collections mecanism. If we take the initial requirement "the ability to save filters applied to gamelists" exists through dynamic collections.

yes i agree that there's no need to save filters in the system carousel gamelists if it exists within dynamic collections! but.. it doesn't work. it seems that when you have "group unthemed collections" turned off, and all the dynamic collections have their own item in the system carousel, *then* it does work. but that becomes very cluttered fast. when you make it all grouped into the one gamelist called "collections" by turning on that "group unthemed collections" option, you lose the independent gamelist filters and sorting for some reason
