### ISSUE TITLE
Mask/Alpha functionality for theming

### ISSUE THREAD

**Issue by DevilBlackDeath** [batocera-linux/batocera-emulationstation#1234]
I think it would be amazing for themes to be able to specify, for images, another path (with a new xml tag called alpha or mask) to a greyscale image to use as a mask for images. This would allow for more advanced image/carousel based game lists without resorting to external editing of the images. This is actually the main usage, as asset images can be used as svg or png, this would mostly be useful for "procedural" image loading i.e scraped content.

I might do this myself later but I can't look at the code right now and I'm not accustomed to batocera's ES code yet (or standard ES either for that matter)

**Comment by fabricecaruso** [comment]
I dont even understand the interest of that.
PNG images have an alpha channel...

**Comment by DevilBlackDeath** [comment]
I thought I explained pretty well the reason for it to exist. Pretty much, since game assets (scraped assets) are not loaded by path but "procedurally" you can't apply a mask to them out of batch image editing through some scripts.

**Comment by fabricecaruso** [comment]
I personnally don't see any real interest in doing that & won't probably be the one adding this feature.
It's a big work for something which will probably won't be used ( or very rarely ).
I'm working for free on my personnal time, so I work only on things that I'm interested in. 
And I'm not interested in this.

You already have custom shaders support, you also have per-game theming ( so you can subtitute images ). 

"I might do this myself later". 
Then propose, participations are welcome.

**Comment by DevilBlackDeath** [comment]
I did say I might, I don't see the need for passive aggressiveness here and I'm not sure why my topic elicited that reaction. I understand the nature of free open source software but if a feature request that is done pretty peacefully without condescendence towards your work makes you feel the need to burst the "I'm doing this for free" argument despite me not disrespecting your time then maybe don't do it ?

As for game theming I haven't found a doc for it, is there any ? I doubt it would meet what I was looking for.

I likely won't add the feature simply because creating a batch image edition script will be a much easier solution for me than dive into an unknown codebase. I was more thinking about having it as a theming tool for less code-heavy people or people who might enjoy themes using it. That's about all this was about.

In all cases it's okay not adding it, I was just wondering about the interest others had and the feasibility (after all it's simply about multiplying an alpha channel by a value based on another input, I was assuming access to the "texture" data was pretty easy, but depending on the APIs used I realize that's not necessarily true).

As for my first paragraph, I have no ill will towards you this was simply how I felt about the whole interaction. If you are a contributor, then wonderful and do keep doing it if you like it. I also think I recognize your name from the Windows build of ES am I right ? Out of curiosity and completely off subject are you a sec of batocera or did you do the build for Retrobat (of which I'd then assume you are a/the dev).

In both cases that's amazing as I'll be using Batocera for my Pi, so being able to use the same UI on my desktop computer is really amazing, so thanks for that ;)

**Comment by fabricecaruso** [comment]
I work for both Batocera & Retrobat & it's the same repo for the 2 projects.
I'm now the main contributor on this repo for maybe 95% of the new code & features... 
So I have to choose & sort what to implement... Unfortunately, no one else will unless it's a small fix, but not when it's complex like that...
There are so many requests on both project. I can't take them all, especially if I don't see the point.
That's what I said that ( don't see any passive aggressiveness ) & I said contributions are welcome.
So I leave this issue open, in case you ( or someone else ) want to contribute

**Comment by DevilBlackDeath** [comment]
Sorry for misreading then. It's awesome that you keep working on it. I really don't see any reason why RetroPie and RecalBox are not switching to and contributing to this version rather than maintaining an outdated version of EmulationStation. I hope this can be changed.

As for this particular issue I'll see what I can do but it would also entail adding a couple more features that are less "trivial" even in their concept. It's mostly about finding the best way to implement it while changing as little of the theming system as possible. Still might give it a go as this is IMO the best frontend so far and the updates done to the batocera branch really make it shine.

**Comment by fabricecaruso** [comment]
I'm closing this one because :
- We won't add a mask functionnality using another png file.
- Now that you can use custom shaders on elements, you can do whatever you want using glsl shaders. If you are good at writing shaders, you'll achieve what you want easily.

**Comment by DevilBlackDeath** [comment]
Shaders ? Well that's nice ! Indeed it should be more than fairly easy to achieve the desired effect.
