### ISSUE TITLE
storyboard animation events that affect other elements

### ISSUE THREAD

**Issue by Rose22** [batocera-linux/batocera-emulationstation#1244]
can we have animation/storyboard events that affect elements other than what the event is attached to?

you might wonder why someone would want this. well, im making a theme, and i want to make the gamelist itself fade out when you stay idle on a gamelist item for a while. but right now it seems i can only affect the game image or video with the "activated" event, not the gamelist itself or the gamelist text/logos..

**Comment by fabricecaruso** [comment]
"the event is attached to" you mean the element ? use an element event to animate element !? that's it ?

**Comment by Rose22** [comment]
> "the event is attached to" you mean the element ? use an element event to animate another element !? that's it ? No it's not possible. It would be simplier to add new events to some controls ( textlist ? ).

if i add the activate event to the textlist, it doesn't seem to do anything when switching games in the list?

**Comment by fabricecaruso** [comment]
activate / deactivate events are only supported with carousel component. With carousel, events can be set on items ( using logo element )
It's impossible with textlist, items in the list are not exposed/exposable (you can't "theme" theme using a <text> element ). 
We could think about adding some new event. Something like "selectionchanged" to the textlist, but it's not sure it will help your case

**Comment by Rose22** [comment]
> We could think about adding some new event. Something like "selectionchanged" to the textlist, but it's not sure it will help your case
yes please! i would use that with the "begin" attribute, to delay it by 5 seconds, then make it animate the opacity of the gamelist to 0 after 5 seconds of idling on an item. and when you switch to another item again, it goes back to 100 opacity. come to think of it we might need a deactivation event too?

**Comment by psakhis** [comment]
I support this. 
On gamecarousel component happens similar things, it seems "open" event not supported, only "scroll, activate, deactivate" and i can't hide element on first chance.
On the other hand, seems systemcarousel works nicer with storiyboards and animations than gamecarousel.

**Comment by daFourch** [comment]
> > We could think about adding some new event. Something like "selectionchanged" to the textlist, but it's not sure it will help your case
> 
> yes please! i would use that with the "begin" attribute, to delay it by 5 seconds, then make it animate the opacity of the gamelist to 0 after 5 seconds of idling on an item. and when you switch to another item again, it goes back to 100 opacity. come to think of it we might need a deactivation event too?

Have you tried with events : "open", "activatePrev", "activateNext", "deactivatePrev" and "deactivateNext" ? 

- open : when you arrive in the gamelist view
- activatePrev and Next : when you highlight another game in the gamelist
- deactivatePrev and Next : when you leave the game in the gamelist

**Comment by fabricecaruso** [comment]
I'm closing this one as I don't really understand what's it about and that now we can compose elements
