### ISSUE TITLE
bug: weird sorting order in theme config menu when amount of options too high

### ISSUE THREAD

**Issue by Rose22** [batocera-linux/batocera-emulationstation#1245]
![](https://media.discordapp.net/attachments/780809704963833857/994386820571869256/unknown.png?width=698&height=1241)

with the theme i'm making, which has a ton of customization options, the moment i add too many options in the menu, the order gets all weird and scrambled! i added numbers to the names to demonstrate what it's doing to the order, but even without the numbers the order is the exact same as in the photo.

**Comment by fabricecaruso** [comment]
Related to AmberElec, they are still using std::sort, while batocera uses std::stable_sort
You should maybe find a way to compare batocera & amberelec before you post bugs here.
