### ISSUE TITLE
Wii U using Cemu gamepad emulation mouse not showing cursor while in game from emulationstation

### ISSUE THREAD

**Issue by BaltasarParreira** [batocera-linux/batocera-emulationstation#1252]
Using the lasted Batocera 34, so this is not working 100% as indicated in the WIKI by:

`Gamepad view
The Wii U Gamepad offers an integrated touchscreen. You can access the Gamepad view by pressing and holding the [Tab] key on your keyboard. Clicking somewhere with the mouse simulates a touch on this screen.

Gamepad motion control
Some games require the motion control function of the Gamepad (e.g. Splatoon forces you to use motion control in the tutorial if you start the game for the first time)

Cemu emulates motion control via mouse gesture + right mouse button.`

I notice there is some action when I manage to guess if the mouse cursor is on top a game button so clicking it works, but I can't never see the cursor moving around.

If I go to Cemu using F1 and run the game manual from Cemu menus the normal mouse pointer shows and works, but also never as a game icon/pointer like most of the games that uses the touch/gamepad from Wii U.

Is this still a bug?
How can I fix it since is really annoying not know for those games where the mouse is?

Thanks for this magnificent release.

**Comment by fabricecaruso** [comment]
It's not related to EmulationStation.
Please report to batocera-linux issues : https://github.com/batocera-linux/batocera.linux/issues

**Comment by BaltasarParreira** [comment]
But I'm using the PC version, should also I report the problem there or there is another better repository for that?
Thanks.
