### ISSUE TITLE
zIndex Animation

### ISSUE THREAD

**Issue by BobMoraneRetro** [batocera-linux/batocera-emulationstation#1254]
In the Wiki it say that the zIndex property can be animated like other property.

But it seems to be buggy because nothing happen with a simple code like :

```
 <storyboard>
     <animation property="zIndex" to="100"  begin="1000" duration="350" mode="linear"/>
</storyboard>
```

zIndex seems not to work well like the other property.

**Comment by BobMoraneRetro** [comment]
if i ask... it mean that i want to animate it :-)
It make possible to hide the gamelist carroussel behind an image/video after few second : it make possible to make appear and animate a logo when the carroussel is hiding => illusion of a gamelist logo animation since it's actually not possible to animate directly the gamecarroussel, i'm just trying to what i want with the use what is in the wiki without ask new feature...

**Comment by Rose22** [comment]
i wanted to animate zIndex too (mostly to work around not being able to animate the opacity of other elements than the one the event gets triggered from)

**Comment by fabricecaruso** [comment]
Well I'm on holiday now, so maybe in a month....

**Comment by Rose22** [comment]
> Well I'm on holiday now, so maybe in a month....

enjoy your holiday!

**Comment by psakhis** [comment]
Thanks for this. I'im interested on zIndex hide/show some element too.

**Comment by fabricecaruso** [comment]
My car broke down on the highway, so I went home at least for the weekend while waiting to get my car back...
So I just added this point in my opened PR....

**Comment by Rose22** [comment]
> My car broke down on the highway, so I went home at least for the weekend while waiting to get my car back... So I just added this point in my opened PR....

im sorry, i hope your car gets fixed soon!

**Comment by psakhis** [comment]
I'm sorry for your car, very hot days...
I tested zIndex and now is working. Thank you very much.

**Comment by BobMoraneRetro** [comment]
It work, thanks !
