### ISSUE TITLE
Scroll selected text on gamecarousel and systemcarousel

### ISSUE THREAD

**Issue by psakhis** [batocera-linux/batocera-emulationstation#1261]
Hi,
On a gamelist, selected game have text scroll rolling, it's nice for a long text on a limited screen size.

On a gamecarousel or systemcarousel this feature isn't available. I workaround this with a heavy animations and game text label but i think this native feature will be good.

Thanks for this fantastic app.

**Comment by fabricecaruso** [comment]
It's possible now using <itemTemplate>
