### ISSUE TITLE
Gamesplash dont work in rpi4

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1264]
game splash screen (gamesplash.xml) is not showing in rpi4. I can test in rpi3 soon, but i think is not working either.

Thanks

**Comment by fabricecaruso** [comment]
It's working only with x86 & x64, because video drivers don't support shared modes with other boards.
It's not related to ES, but to the operating system.

**Comment by pajarorrojo** [comment]
understood, thanks

**Comment by pajarorrojo** [comment]
Hi again @fabricecaruso. Im working on some new screens for my theme and I would like to clarify, hope you can help me... so how many architectures are gamesplash compatible in total? only x86, x64 and windows (retrobat) or some more?, or where I can verify this in some file or piece of hard code? Thanks in advance and happy new year

**Comment by fabricecaruso** [comment]
already answered

**Comment by pajarorrojo** [comment]
ok, thanks, i was just looking at the list of boards, would steamdeck be in this compatible group too?
