### ISSUE TITLE
game settings -> retroachievement settings -> index games -> systems included not populated by grouped systems

### ISSUE THREAD

**Issue by yepyepyep4711** [batocera-linux/batocera-emulationstation#1267]
Issue: the sub-menu under game settings -> retroachievement settings -> index games -> systems included is not populated by grouped systems if they are not also displayed individually

Expected result: have either the group(s) or the systems show up in that list so that they can be indexed

Reproduction steps: under game collection settings - > systems displayed, make sure final burn neo is tickced, then go to game settings -> retroachievement settings -> index games -> systems included and see it listed. Then go to game collection settings - > systems displayed and untick it, go to game settings -> retroachievement settings -> index games -> systems included and see it's gone. This behaviour might sound logical if you display all your systems, but if you use automatic game collections it's not.

Example: if you put all your arcade systems in the arcade collection and don't display the individual systems, fbneo will never get indexes, thus "breaking" retroachievements. This is especially true for users of the system until version 32, because this filter didn't exist previously, so indexing group systems did work in the past.

**Comment by fabricecaruso** [comment]
fixed in my current PR
