### ISSUE TITLE
[THEME] StoryBoard and Video

### ISSUE THREAD

**Issue by BobMoraneRetro** [batocera-linux/batocera-emulationstation#1270]
Hello,

There are 2 issues on Gamelist with Storyboard and Video :

1) When i'm trying to make event for video when deactivate/deactivateNext/deactivateNext, when i scroll my gamelist the prev video playing and more i scroll more video are playing at the same time until RetroBAT crash. Video for an example : https://discord.com/channels/357518249883205632/857328707763961886/1002554533555228752

Code i use :
` <storyboard event="open">
                <animation property="offsetY" from="-7.9" to="0" duration="2950" mode="EaseOutQuint"/>
                <animation property="opacity" from="1" to="1" duration="" mode="Linear"/>
                <animation property="opacity" from="1" to="1" begin="3950" duration="" mode="Linear"/>
               <animation property="zIndex" from="" to="350" begin="3950" duration="" mode="Linear"/>
			</storyboard>
			<storyboard event="activateNext">
                <animation property="offsetY" from="-7.9" to="0" duration="2950" mode="EaseOutQuint"/>
                <animation property="opacity" from="1" to="1" duration="" mode="Linear"/>
                <animation property="opacity" from="1" to="1" begin="3950" duration="" mode="Linear"/>
               <animation property="zIndex" from="" to="350" begin="3950" duration="" mode="Linear"/>
			</storyboard>
         <storyboard event="activatePrev">
                <animation property="offsetY" from="-7.9" to="0" duration="2950" mode="EaseOutQuint"/>
                <animation property="opacity" from="1" to="1" duration="" mode="Linear"/>
                <animation property="opacity" from="1" to="1" begin="3950" duration="" mode="Linear"/>
               <animation property="zIndex" from="" to="350" begin="3950" duration="" mode="Linear"/>
			</storyboard>
			<storyboard event="deactivateNext">
                            <animation property="offsetY" to="-7.9" duration="800" mode="EaseOutQuint"/>
            <animation property="opacity" to="0" begin="100" duration="" mode="Linear"/>
			</storyboard>
         <storyboard event="deactivatePrev">
                            <animation property="offsetY" to="-7.9" duration="800" mode="EaseOutQuint"/>
            <animation property="opacity" to="0" begin="100" duration="" mode="Linear"/>
			</storyboard>`

2) Second Issue is the same "more i scroll more video are playing at the same time" in the gamelist with long press on button to make the gamelist scroll.

Nice summer.

**Comment by fabricecaruso** [comment]
Impossible to tell without seeing the full theme

**Comment by BobMoraneRetro** [comment]
How can i send it to you ?

**Comment by BobMoraneRetro** [comment]
i will send it to you on discord

**Comment by fabricecaruso** [comment]
Should be fixed, no ?
