### ISSUE TITLE
(Feature request) Setting to allow screensaver videos to play in full

### ISSUE THREAD

**Issue by ThatGrimshaw** [batocera-linux/batocera-emulationstation#1284]
I have a bunch of old video game commercials downloaded to use for the "Custom Videos" screensaver option. Most of the videos are around 30s long, but some are longer and some are shorter. Rather than each video playing out in full, they play until the value in the "Video Duration" setting is met.

So, if a video is 15s long and the duration is set to 30s, that video will play twice, then the next video will start.
Conversely, if a video is 45s long and the duration is set to 30s, the video will get cut short.

I've tried manually changing the `ScreenSaverSwapVideoTimeout` line in `es-settings.cfg` to `value="0000"` and `value="-1"`, but this only causes each video to play for a split second. Leaving the field empty (`value=""`) does the same thing.

It would be great if there was an option to ignore/override the duration setting so videos play in-line. Also, if there's any workaround for this right now, I would love to hear it!

**Comment by fabricecaruso** [comment]
I don't see the problem. If you set duration to 1000 seconds, your video have the time to finish and they don't loop...
