### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by CursingOwl** [batocera-linux/batocera-emulationstation#1285]
In file included from /home/cursingowl/batocera-emulationstation/es-core/src/utils/FileSystemUtil.h:8,
                 from /home/cursingowl/batocera-emulationstation/es-core/src/Settings.cpp:3:
/home/cursingowl/batocera-emulationstation/es-core/src/utils/TimeUtil.h:48:37: error: field ‘mTimeStruct’ has incomplete type ‘tm’
   48 |                         tm          mTimeStruct;
      |                                     ^~~~~~~~~~~
In file included from /usr/include/c++/12.1.1/cwchar:44,
                 from /usr/include/c++/12.1.1/bits/postypes.h:40,
                 from /usr/include/c++/12.1.1/bits/char_traits.h:39,
                 from /usr/include/c++/12.1.1/string:40,
                 from /home/cursingowl/batocera-emulationstation/es-core/src/Settings.h:6,
                 from /home/cursingowl/batocera-emulationstation/es-core/src/Settings.cpp:1:
/usr/include/wchar.h:83:8: note: forward declaration of ‘struct tm’
   83 | struct tm;
      |        ^~
/home/cursingowl/batocera-emulationstation/es-core/src/utils/TimeUtil.h:30:87: error: return type ‘struct tm’ is incomplete
   30 |                                    operator tm         ()                       const { return mTimeStruct; }
      |                                                                                       ^
make[2]: *** [es-core/CMakeFiles/es-core.dir/build.make:286: es-core/CMakeFiles/es-core.dir/src/Settings.cpp.o] Errore 1
make[1]: *** [CMakeFiles/Makefile2:343: es-core/CMakeFiles/es-core.dir/all] Errore 2
make: *** [Makefile:156: all] Errore 2

**Comment by cmitu** [comment]
Seems similar to https://github.com/RetroPie/EmulationStation/issues/804. Probably something similar to https://github.com/RetroPie/EmulationStation/pull/807 can be implemented.

**Comment by CursingOwl** [comment]
Adding time.h to TimeUtil.h fixed it.
