### ISSUE TITLE
theming: ${system.cheevos} filter not working

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1300]
I understand that this new filter replaces the obsolete ifCheevos="true/false", but it is not working correctly, it always returns 1.000000 even if the selected system is not compatible with retroachievements.

Thanks for all

Related:
#1249

**Comment by fabricecaruso** [comment]
Adressed there : https://github.com/batocera-linux/batocera-emulationstation/pull/1301

**Comment by pajarorrojo** [comment]
Thanks for your work!
