### ISSUE TITLE
theming: {screen.ratio} issues

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1305]
Hi @fabricecaruso , today i have tried with different 5/3 aspect ratio resolutions such as:

800x480
1200x720
1800x1080

But there is an error, the system recognizes them as 16/10 and apply this value to the variable {screen.ratio}

Thanks for your work!!

**Comment by pajarorrojo** [comment]
another issue with aspect ratios:

1360x768 returns a 30/17 aspect ratio when is considered as 16/9

**Comment by fabricecaruso** [comment]
Here's where the code if you wanna understand how it's done. 
https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-core/src/renderers/Renderer.cpp#L529

- There's no 5/3 support. This list was inspired from Retroarch which has no 5/3 support.
What kind of screen is 5/3 ?

- 1360/768 => 1.7708333, 30/17 => 1.76470588, 16/9 -> 1.7777778

The difference is for 0.0061 for 30/17, and 0.0069444 16/9. So the nearest is 30/17.
There's no mistake.

The best we could do is remove support for 30/17, then it will be returned as 16/9

**Comment by pajarorrojo** [comment]
ok, I have already fixed the 30/17 thing at the theme level, when it detects 30:17 I filter it as 16:9 and it's no problem, everything fits fine.

5:3 is an aspect ratio that is used above all on mobile or touch screens, such as 4.3" 5" etc, they are usually small resolutions such as 800x480 or 1200x720, and are very common in portable devices or small formats. Its strange that this format is not supported by Retroarch, its becoming more and more frequent.

An example:
https://retroflag.com/pistation-case.html

Placing it directly between these lines would not be enough?
https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-core/src/renderers/Renderer.cpp#L507

**Comment by pajarorrojo** [comment]
I have ordered a small 5" hdmi screen to test, it will arrive in a few days. I want to clarify what aspect ratio detects on a physical screen and not an emulated one. I will report anything

**Comment by pajarorrojo** [comment]
The 5" screen has already arrived. Indeed, it has a native resolution of 800x480 and the aspect.ratio variable returns 16/10. :(

**Comment by fabricecaruso** [comment]
what about this issue ? did you find a solution ?

**Comment by pajarorrojo** [comment]
I have to redo in-depth test i have a bit forgotten. I'll close it until new results are available
