### ISSUE TITLE
Logs are still created when log level = off

### ISSUE THREAD

**Issue by Hew-ux** [batocera-linux/batocera-emulationstation#1309]
**Issue:** Logs (specifically `es_launch_stderr.log` and `es_launch_stdout.log`) are still created when the log level is set to off. In fact, it seems to be stuck in verbose mode.

**Reproduction:** Go to **MAIN MENU** -> **SYSTEM SETTINGS** -> **FRONTEND DEVELOPER SETTINGS** -> **LOG LEVEL** , then launch a game. The log files will be created at system/logs.

I'm putting it under here as it's ES itself which is producing these logs. But do let me know if this issue report would be more appropriate on Batocera's issue tracker instead.

**Comment by fabricecaruso** [comment]
es_launch_stderr.log and es_launch_stdout.log are not emulationstation logs, but configgen logs.
