### ISSUE TITLE
In the View Options menu “Jump To Game Beginning With The Letter” does not always work.

### ISSUE THREAD

**Issue by g12345567** [batocera-linux/batocera-emulationstation#1312]
In the View Options menu “Jump To Game Beginning With The Letter” does not always work sometimes on certain systems it won’t jump to the first game beginning with the chosen letter, yet on other systems it works as intended. Below I have listed the systems I have Installed, and which ones do and don’t work with the option.

**Non-Working Systems**

3DO, Sega Genesis, Sega Mega CD, Sega Megadrive, Sega Megadrive 32x, Sega Dreamcast, GameCube, Neo Geo CD, Neo Geo Pocket Color, PSP, Nintendo DS, Philips CD-I, Playstation Portable, Playstation, Playstation 2, Virtual Boy

**Working Systems**

All Games, Apple II, Atari 2600, Atari 7800, Atari Lynx, Atomiswave, Commodore 64, Daphne, Neo Geo, PC Engine, PC Engine Cd-rom, Sega Master System, Sega Naomi, Sega Naomi 2, LCD Games, Vectrex, Xbox, Nintendo Entertainment System, Super Nintendo, Game Boy, Game Boy Color, Game Boy Advance, Nintendo 64, Nintendo 64DD, SG-1000,

I’m running Batocera 35 x86_64  But this has been happening on previous builds as well and wondering why only some systems support this option.

**Comment by fabricecaruso** [comment]
Drive Letter ?

**Comment by g12345567** [comment]
UPDATED:  Sorry.

**Comment by fabricecaruso** [comment]
I can't reproduce, it's working just fine. 
Maybe you just changed the sort order to something that is not "game name"

**Comment by fabricecaruso** [comment]
Fixed. It happened when selection was over a game stored in a sub-folder
