### ISSUE TITLE
Provide up to date Windows build instructions

### ISSUE THREAD

**Issue by cyberluke** [batocera-linux/batocera-emulationstation#1317]
Hi, I encountered around 10 bugs in this software, finally I decided to fix some of them in several dependencies and now I need to build this project on Windows.

Please provide correct CMake build parameters, this one is incorrect:
\FreeImage\Dist\x32\FreeImage.lib

You link to this Sourceforge download, but it does not contain this folder structure path (x32 folder):
FreeImage3154Win32.zip

There are more issues, this is just example.

Perhaps Fabrice Caruso could provide a correct up to date build instructions or script?

**Comment by cyberluke** [comment]
Your FreeType2 link throws 404: http://mirror.easyname.at/nongnu/freetype/freetype-2.4.9.tar.bz2

**Comment by fabricecaruso** [comment]
a package containg necessary libs can be found at http://fabrice.caruso.free.fr/eslibs.7z

**Comment by cyberluke** [comment]
Thank you very much Fabrice. I was thinking that BOOST and Eigen will be no longer needed.

**Comment by fabricecaruso** [comment]
The latests CMake script downloads the required dependencies from the repository batocera-emulationstation-win32-dependencies.
