### ISSUE TITLE
I want to send a pull request for es_features.cfg

### ISSUE THREAD

**Issue by cyberluke** [batocera-linux/batocera-emulationstation#1318]
Hi, where is es_features.cfg?

The comment in the file says:
`<!-- es_features.cfg edited for Batocera ES Windows Build. -->`

But my change will have a global impact.

I found only some usage of it here: CustomFeatures.cpp

How is it generated? Where is it stored?

I work on CRT SwitchRes fix and finally, after two years, got interlaced resolution fixed on NTSC/PAL CRT TV's such as Sony PVM.

To work with that, I had to add this last property to es_features.cfg:
```
    <feature name="CRT SCREEN OUTPUT" value="CRTSwitch">
      <choice name="NO" value="false"/>
      <choice name="15KHz" value="1"/>
      <choice name="31KHz (Standard)" value="2"/>
      <choice name="31KHz (120Hz)" value="3"/>
      <choice name="Switchres.ini (INI)" value="4"/>
    </feature>
```

The actual fix will be in this SwitchRes C++ library: https://github.com/antonioginer/switchres/issues/96 , which RetroArch developers manually copy to their 'deps' directory in RetroArch source code repo.

**Comment by nadenislamarre** [comment]
generated by https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulationstation/batocera-es-system/batocera-es-system.py

mainly from 

https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulationstation/batocera-es-system/es_features.yml

**Comment by cyberluke** [comment]
Thank you, that is a little bit unlucky for me to have another emulationstation folder somewhere in batocera.linux repository. So I will need to send pull request there and ask @fabricecaruso how they generate it on Windows. As I cannot find this one in Batocera-Ports Visual Studio solution.

**Comment by fabricecaruso** [comment]
It depends if you are taking about batocera or retrobat. It's not the same file & not the same place

**Comment by cyberluke** [comment]
Lets say I would like to cover all the grounds for everyone:
batocera.linux
batocera.windows
batocera.ports
retrobat 

That would be the best for people. If I forgot something, feel free to correct me.

**Comment by fabricecaruso** [comment]
batocera.windows ???? Batocera & Retrobat are different projects.
Retrobat is some kind of consolitation of many subprojects including this EmulationStation.
If you want to see how retrobat setup is build, see https://github.com/kaylh/retrobat/

**Comment by cyberluke** [comment]
You have had WIN branch in Batocera for a long time. Yes, I know it is not easy to answer.

Just tell me how you build this es_features.cfg in Windows, please and where can I send that pull request. Or you are using batocera.linux python script? I already look in Retrobat as well. It is not there.

**Comment by cyberluke** [comment]
Thanks for providing the link, I will provide it myself: https://github.com/kaylh/RetroBat/blob/ffe3091fe5520b77a10cb327e67f54f492b63a4c/system/templates/emulationstation/es_features.cfg

Sometimes asking a developer for info is like left hand does not know what right hand is doing.

**Comment by cyberluke** [comment]
It is strange that searching for 'es_features.cfg' file directly will not find it - that's why a link would be helpful next time. Also your style of communication could be better. Instead of having your keyboard stuck at '????', you could provide a helpful information beforehand. Perhaps a more respect to senior developers would be nicer. Thank you for consideration & understanding.

![es_features](https://user-images.githubusercontent.com/1111375/194972876-230bf5f9-6933-4e3e-8ad7-1a8c3e3e5ff5.jpg)

**Comment by fabricecaruso** [comment]
waoh... you are very beginner with git ?
Use "go to file" button instead, or search you fork local files....
It's in /system/templates/emulationstation/es_features.cfg
