### ISSUE TITLE
theming: whish: custom spacing between carousel items

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1319]
Please, can we add a new property tag for custom spacing between carousel ítems?, like works on `<controllerActivity> `element with the `<itemSpacing>`. With this new attribute we would have more freedom to adjust the carousel logos on the screen much more precisely.

https://github.com/batocera-linux/batocera-emulationstation/blob/master/THEMES.md#controlleractivity
https://github.com/batocera-linux/batocera-emulationstation/blob/master/THEMES.md#carousel

Thanks!!

**Comment by fabricecaruso** [comment]
I'm closing this one as, now, you can have an itemtemplate, and use a <container> as root with a padding....

**Comment by pajarorrojo** [comment]
I've been trying, but I can't seem to adjust it the way I'd like. I'll keep tinkering with it to see how I can do it. If you say it can be done with an itemtemplate, I'll ask for your help.

**Comment by fabricecaruso** [comment]
just make <logoSize> bigger. this will introduce bigger spacings, then in the logos, add padding.

**Comment by pajarorrojo** [comment]
Okay thanks, I'll give it a try. I was planning to put some work into this with the new itemTemplate. The idea is to remove only the space that's marked in green in the pic, but just from the inactive logos. Everything I've tried so far hasn't worked because the logos adjacent to the active one end up getting parcially hidden underneath  the active
![Captura de pantalla 2023-12-17 a las 23 04 04](https://github.com/batocera-linux/batocera-emulationstation/assets/73712202/ff10e02d-59f3-4d57-8c96-1d52013c8a71)

**Comment by pajarorrojo** [comment]
With the hidden logos, I mean this. You can see how the inactive logos don't have space, thats right, but the ones next to the active one get hidden underneath
![Captura de pantalla 2023-12-18 a las 0 16 56](https://github.com/batocera-linux/batocera-emulationstation/assets/73712202/a52ddea0-25d9-43fa-9b75-5e60795626f5)

**Comment by fabricecaruso** [comment]
Wow. That was totally impossible to understand your initial explanations !!!!

Finally, this has nothing to do with "custom spacing"
It's about to relayouting non selected items taking in account the logo size after applying the logoScale on the selected item...

Well, it's not possible to do this in any way for the moment. 

I'm reopening this one, but it's clearly not a priority.

**Comment by pajarorrojo** [comment]
Yes, I've always thought it's a very particular scenario, and carrying it out would require rewriting the carousel's construction in ES. I understand it's not a priority. Thank you for the clarifications

**Comment by fabricecaruso** [comment]
I just added this : https://github.com/batocera-linux/batocera-emulationstation/pull/1613
Using you theme <scaledLogoSpacing>1.1</scaledLogoSpacing> is looking fine.

![image](https://github.com/batocera-linux/batocera-emulationstation/assets/51082152/bb75dba9-8a8c-41d8-9903-5711c9f3fab4)
