### ISSUE TITLE
about emulationstation UI system settings bug

### ISSUE THREAD

**Issue by zack-huangzihan** [batocera-linux/batocera-emulationstation#1327]
When I turn on the system Settings for the options, switch the voice and press "back", emulationstation restart, I'm going to switch languages switch to another language and press it "back", emulationstation restart，The language options I selected are not saved either.but I have modified ~/.config/emuelec/configs/emuelec.conf  language options, It works. There are some bugs with ui modifications, I wonder if the problem is:  es-app/src/guis/GuiMenu.cpp?

**Comment by fabricecaruso** [comment]
I don't know a lot about what emuelec customized, they have their own version forked here
https://github.com/EmuELEC/emuelec-emulationstation

**Comment by zack-huangzihan** [comment]
ok
