### ISSUE TITLE
SIGSEGV if CollectionSystemsAuto has no value and no roms exist

### ISSUE THREAD

**Issue by Jakobud** [batocera-linux/batocera-emulationstation#1329]
I am running Batocera ES on an Anbernic RG351MP. I have discovered something that I can recreate where ES throws a SIGSEGV error when it's starting up, resulting in an infinite startup loop. I have been able to recreate this on 2 different devices.

When my device boots up and ES tries to start, it would get caught in an infinite loop where it looks like it's starting but then starts over, again and again.

It took a while but eventually I tracked it down to a setting in `es_settings.cfg`:

`<string name="CollectionSystemsAuto" value="" />`

According to my research, this setting should have a value of `all`, `recent` or `favorites`.

If this setting has an empty string value, then ES errors out with a SIGSEGV on startup. If I give it a valid value, then ES starts right up. 

And somehow, in the ES interface I was able to set this value to an empty string. Not sure how. I have never gone in and fiddled with the `es_settings.cfg` before. So I'm not sure what in the interface caused it to have an empty value but something did.

In any case, I assume that something needs to happen on startup that checks this value and if it's empty/null/not set then ES should give it a default value so that there is no error.

Some more context: At the time, my device had zero roms on it. So ES would not be able to find any roms or game systems to show in the menu. I have not tested it but I'm guessing that if there were roms, then ES would not crash because of the above setting. I would assume that whats happening is that ES is looking for roms and doesn't find any, so it falls back to an automatic collection to display but since the value doesn't tell it what kind of automatic collection to display (all, recent or favorites) then it doesn't know what to do and crashes.

Here is a video that shows AmberELEC booting up and then an infinite loop begins when ES tries to start: 

https://photos.app.goo.gl/hevmdFM4xyUetgR6A

**Comment by fabricecaruso** [comment]
1/ I don't crash with that setting empty.
2/ Is it Batocera or is it AmberElec ? We don't support AmberElec, they have their own fork. 
If you are running AmberElec, please close that issue & contact them instead.
