### ISSUE TITLE
VICE Emulator does not start on click (Speedlink Competition Pro Joystick)

### ISSUE THREAD

**Issue by BinaryRider** [batocera-linux/batocera-emulationstation#1337]
Copied from the batocera forum: https://forum.batocera.org/d/8597-emulator-does-not-start-on-click-speedlink-competition-pro-joystick

For a real C64 gaming experience I bought the speedlink Competition Pro (USB) for my x64 PC.

This joystick works very well with the appropriate configuration within VICE. But my problem is that I always have to plug the joystick into the USB port **AFTER** starting the emulator.

If the joystick is already in the USB port before (and it is mapped correctly via the Batocera gamepad mapping function), then I can select all emulators and games in the menu and in the selector, but as soon as I select a C64 game with the fire button (X), the emulator is loaded (game splashscreen is displayed) and then immediately returned to the Batocera menu. The game does not start and the emulator is not displayed, as if the joystick would permanently send a "back" command. All gamepad mapping attempts have shown no success.

This Gif video shows the problem:
![dcaa465017bd](https://user-images.githubusercontent.com/112688799/198881862-442e223e-a695-4906-a669-4b669f996fa7.gif)

**LOG file:**
killall: evmapy: no process killed
2022-10-28 22:12:31,716 ERROR (emulatorlauncher:571):<module> configgen exception:
Traceback (most recent call last):
File “/usr/bin/emulatorlauncher”, line 569, in <module>
exitcode = main(args, maxnbplayers)
File “/usr/bin/emulatorlauncher”, line 97, in main
return start_rom(args, maxnbplayers, args.rom, args.rom)
File “/usr/bin/emulatorlauncher”, line 244, in start_rom
cmd = generator.generate(system, rom, playersControllers, guns, gameResolution)
File “/usr/lib/python3.10/site-packages/configgen/generators/vice/viceGenerator.py”, line 26, in generate
viceControllers.generateControllerConfig(batoceraFiles.viceConfig, playersControllers)
File “/usr/lib/python3.10/site-packages/configgen/generators/vice/viceControllers.py”, line 58, in generateControllerConfig
listVice.append(indexValue.replace(‘#’, pad.inputs[indexName].id, 1))
KeyError: ‘x’

**Comment by fabricecaruso** [comment]
It's not related to EmulationStation.
Please close this issue & create it again in batocera.linux repository.

**Comment by BinaryRider** [comment]
fabricecaruso, sorry about that. I am not skilled with github and unfortunately did not pay attention to the correct repository.
I have resubmitted the case in the correct repository.
