### ISSUE TITLE
Atari 7800 and Channel F retroachievements support (trophie icons not showed)

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1343]
Hi, a new little issue here
Atari 7800 and Channel F systems have retroachievements support and when we enter a game, retroarch recognizes if it has trophies, but the icons are not displayed on the frotend and the system variable "system.cheevos" returns false.

Thanks for your work!

**Comment by lbrpdx** [comment]
Thanks @fabricecaruso, fixed in https://github.com/batocera-linux/batocera.linux/pull/7462

**Comment by fabricecaruso** [comment]
Thanks. Then this issue can be closed.
