### ISSUE TITLE
Can you add an automated script (31k, 120hz) for old crt monitor?

### ISSUE THREAD

**Issue by greatliu** [batocera-linux/batocera-emulationstation#1351]
Hi, dear author.
I found that the batocera had add an automated script for 15k crt([Build-CRT-15KHz-Batocera-V35](https://github.com/ZFEbHVUE/Build-CRT-15KHz-Batocera-V35)), it is amazing!
https://wiki.batocera.org/batocera-and-crt

But I tested this script, perhaps it is only for crt TV@15khz. I use an old crt monitor just support 31k@120hz, it shows ES UI correctly, but got black screen when run any game.
Can you add an automated script (31k, 120hz)? I think many user who have old crt monitor need it.

Thanks!

**Comment by fabricecaruso** [comment]
It's not related to EmulationStation.
Please repost this in batocera-linux.
