### ISSUE TITLE
wrong and non antialised icon

### ISSUE THREAD

**Issue by skysix2** [batocera-linux/batocera-emulationstation#1360]
Hello !!

I noticed 2 issues affecting the controller icons at the bottom.
as seen from the video, I switch between 2 "automatic collections" and 2 "dynamic arcade collections":

1 - the correct icons are those of the "automatic collection" (arcade buttons) when I switch to the "dynamic collections" they become the console controller ones

2 - wrong "dynamic collection" icons have correct antialiasing, while right "autocollection" icons are without antialiasing. 
previously they too were anti-aliased

https://user-images.githubusercontent.com/105243640/205319651-506aa2b9-d483-4d1d-ba77-edd2ff7b3bfd.mp4

**Comment by fabricecaruso** [comment]
Not related to EmulationStation.
Please contact the theme developer

**Comment by Darknior** [comment]
Pour ce qui est du souci d’antialiasing, ça vient surement du theme oui.
Mais comment c'est possible de passer d'une série d'icones à une autre ?
On ne peux pas avoir une collection avec les icones du HELP en mode ARCADE et les systèmes avec les icones CONSOLE, normalement on a soit tout avec un design soit tout avec un autre.

Je ne vois pas comment la collection dans un thème pourrait causer cela ? non ?
C'est là où je pense que le bug vient de ES et non du thème ...
A l’origine il avait posté l'erreur chez moi.

https://github.com/Darknior/RVGM-BT-Theme/issues/66#issuecomment-1334966738
