### ISSUE TITLE
Feature request: select directories for scraping

### ISSUE THREAD

**Issue by Lendersmark** [batocera-linux/batocera-emulationstation#1365]
The built-in EmulationStation scraper downloads images and videos in arbitrary directories inside the roms system folder, such as `/images` and `/videos`.

It would be very useful if we could tell in which directories where we want each kind of asset to be downloaded.

For example, one could want to download 2d boxes into a `/boxart` directory, and screenshots into a `/screenshots` directory. Gamelist.xml creation could be also configurable in the same option screen, for example letting the user choose that the `<image>` tag that points to `/boxart` folder and the `<thumbnail>` tag that points to `/screenshots` folder.

While it would add a certain level of complexity to ES, it would be very useful and minimize the need to use a dedicated scraper tool, such as ARRM or Skraper.

**Comment by fabricecaruso** [comment]
No sorry. It should require to add new options + add a migration code, which will probably add complexity.
The internal scraper is meant to be simple.

You still have external tools if you want your own organisation.
