### ISSUE TITLE
Sega Saturn retroachievements support RPI4

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1369]
Hi,
An issue with RA for Saturn, emulationstation works fine and recognizes games, but trophies and icons are not showing in frontend.

Thanks

**Comment by fabricecaruso** [comment]
It's not related to emulationstation as game trophies and icons are well detected.
Probably related to batocera.linux as it's using yabasanshiro, and this core is not declared as supporting retroachivements.
Please create an issue in batocera.linux repository instead.

**Comment by pajarorrojo** [comment]
ok, but the issue is precisely that the icons and games are not recognized in the frontend, that's why I thought it convenient to warn this in emulationstation and not in linux, are you sure that this concerns linux?

**Comment by fabricecaruso** [comment]
it depends on the declarations made on cores ( by batocera or retrobat or emuelec... )
see es_systems & es_features files.
