### ISSUE TITLE
Request : Make System logo appear in collection and category with several systems.

### ISSUE THREAD

**Issue by LowGui** [batocera-linux/batocera-emulationstation#1372]
Hello, I create themes on RetroBAT in order to use them on RetroBAT and Batocera. Currently in the collections and categories comprising several different systems, the possibility of displaying the name of the system is offered only for the "list" display, not for the gamecarousel type displays or any other views using images instead of the text. This current capability does not allow placing the system name anywhere other than sticking to the game name.

I would like to have the possibility in my themes to display the logo of the machine for the game currently selected. Because sometimes the same game name is found on several platforms and it is difficult to know which system it belongs to.
Also, I would like this logo to be able to be placed and animated anywhere in my gamelist theme.

Hoping this is doable.

**Comment by fabricecaruso** [comment]
you can add an extra using ${system.name} variable
https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-app/src/SystemData.cpp#L1468
