### ISSUE TITLE
error: use of ‘auto’ in lambda parameter declaration only available with ‘-std=c++14’ or ‘-std=gnu++14’

### ISSUE THREAD

**Issue by ZaneBey** [batocera-linux/batocera-emulationstation#1384]
/EmulationStation/es-core/src/ThemeData.cpp:1893:59: error: use of ‘auto’ in lambda parameter declaration only available with ‘-std=c++14’ or ‘-std=gnu++14’

How can i deal with this error?thanks for your ansaw!

**Comment by ZaneBey** [comment]
1893 |         for (auto path : VectorHelper::distinct(paths, [](auto x) { return x; }))

**Comment by fabricecaruso** [comment]
build it with c++14....

**Comment by ZaneBey** [comment]
What are the operating steps? At present, the compiling environment I use is Ubuntu 20.04, and the compiler is cmake 3.10 meke 4.3 gcc-11.3 g++- 11.3！thanks for your ansaw！

**Comment by ZaneBey** [comment]
/usr/bin/c++ -DHAVE_INTL -DHAVE_UDEV -DUSE_OPENGL_21 -D_ENABLE_KODI_ -I/usr/include/freetype2 -I/usr/include/SDL2 -I/usr/include/x86_64-linux-gnu -I/usr/include/vlc -I/home/zanebey/EmulationStation/external -I/home/zanebey/EmulationStation/es-core/src -I/home/zanebey/EmulationStation/external/pugixml/src -std=c++14 -Wno-attributes -O3 -std=gnu++11 -o CMakeFiles/es-core.dir/src/ThemeData.cpp.o -c /home/zanebey/EmulationStation/es-core/src/ThemeData.cpp

**Comment by ZaneBey** [comment]
The compilation parameter already contains "- std=c++14", but an error is still prompted! Please refer to the previous message for the compilation command!
