### ISSUE TITLE
theming: mute tag for videos stop working

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1385]
Hi @fabricecaruso mute audio function for videos stop working in latest beta, im talking about:

```
<video name ="custom-video">
   <audio>false</audio>
</video>
```

tested on rpi4 and x86_64 latest beta with same issue

Thanks!

**Comment by Tovarichtch** [comment]
I confirm the bug. It has been reported in #beta various times. It's all across platforms (x86_64 here).

**Comment by pajarorrojo** [comment]
In my case I use some background videos in my theme (playstation-x) and the audio property true/false has stopped working, it is just like the code extract that I pasted above.

**Comment by pajarorrojo** [comment]
an example, but i use in more scenarios:

https://github.com/pajarorrojo/es-theme-PlayStation-X/blob/d0004bafe0ed3f67b8b0d7b16da9f5abe532b24a/_theme_options/systemvideo/enable-video-bg.xml#L17

**Comment by fabricecaruso** [comment]
Does it concerns only videos ? 
I mean, navigation sounds & background music settings are applying correctly ?

Maybe it's not related to EmulationStation, but to the last VLC version ( ES calls "libvlc_audio_set_mute(mMediaPlayer, 1)" to mute video audio - looks like it has no effect )

**Comment by pajarorrojo** [comment]
yes only concerns to the video tag in my case, to the audio property.

**Comment by pajarorrojo** [comment]
Navigation sound and background work fine for me and apply changes after reboot, not instant but I think it worked like this before

**Comment by pajarorrojo** [comment]
edit: navigation sound apply changes after reboot, not intant, background sound works like expect

**Comment by pajarorrojo** [comment]
For your interest, the main option: SOUND SETTINGS -> ENABLE VIDEO PREVIEW AUDIO works and mute unmute all videos (after rebooting)

**Comment by fabricecaruso** [comment]
So what's the problem ?

**Comment by pajarorrojo** [comment]
Just what I indicated in the first message, the <audio>false</audio> property does not work in the themes coding for videos.

In my theme I use background videos that if they have the audio activated can be very annoying, for this I have a series of subsets in the configuration of my theme that activate or deactivate the audio of the background videos.

We already talked some time ago about muting custom videos and how to do it

https://github.com/batocera-linux/batocera-emulationstation/issues/871#issuecomment-841742945

now it doesn't work

**Comment by pajarorrojo** [comment]
install playstation-x theme from the UI and you can see for yourself. In the theme options you can configure if you want to activate or deactivate the audio of the background videos (system videos, ads), in version 35 it works correctly, not in the last beta

**Comment by pajarorrojo** [comment]
and now that we have the thread open, IMHO the main option "ENABLE VIDEO PREVIEW AUDIO" should only mute the game videosnap (name="md_video") as indicated, and not all the videos shown on the frontend...

**Comment by fabricecaruso** [comment]
I don't reproduce neither on Ubuntu or Windows by compiling the latest source code.

Accordingly, and since the code has not changed for several months on this part, it's probably not directly related to EmulationStation -> It should be the same with 35 as the source code is the same.

I presume batocera.linux team bumped libvlc to a recent version.
And libvlc_audio_set_mute is probably not always working anymore correctly.

**Comment by pajarorrojo** [comment]
Well, what a nuisance. I think many users who use my theme aren't going to be happy about this. Maybe @nadenislamarre can clarify or help us solve this issue. Thanks Fabrice.

**Comment by pajarorrojo** [comment]
forward:
https://github.com/batocera-linux/batocera.linux/issues/7891
