### ISSUE TITLE
Screenscraper pulling wrong wheel logo...somtimes?

### ISSUE THREAD

**Issue by jcox08** [batocera-linux/batocera-emulationstation#1387]
For example I have 2 NES titles

"Super Mario Bros. 2 (USA) (Rev 1).nes" & "Super Mario Bros. 3 (USA) (Rev 1).nes"

Both of these titles have Japan and World Logo (Wheels) available on screenscraper.fr , but Mario Bros.2 pulled the JP logo and the Mario Bros. 3 pulled the World logo. Can someone help me figure out what causes this and how to correct it or fix it?

In the gameslist.xml it also list US region

**Comment by fabricecaruso** [comment]
In the preference you can now set your prefered region.
But. If screenscraper does not have the media for the region, it fallsback to the first available media....
