### ISSUE TITLE
External monitor HDMI-1 don't show video intro. It always plays in EDP-1. How can I fix this?

### ISSUE THREAD

**Issue by madman80** [batocera-linux/batocera-emulationstation#1390]
Hi. I made an arcade machine using a pentium laptop (intel GPU) booting USB Batocera v36. At first I had HDMI signal since booting on external HDMI monitor but black screen appears since ES loads. Ok, that has solution . I need to set HDMI output for ES so I edit system\batocera.conf to add command global.videooutput=HDMI-1. Now everything is shown in the HDMI monitor as expected but the splash video intro. This intro always plays through laptop screen and I want it plays through HDMI output. What file do I need to edit to say the video player plays custom video intro though HDMI? Thanks in advice

In other words... As Batocera wiki says " Batocera displays a total of three splash images during a regular boot sequence" In my case I got:

    1. The boot splash. EDP1+HDMI-1 OK
    2. The custom user splash video .EDP-1 WRONG!
    3. The EmulationStation loading splash. HDMI-1 OK

I need all the boot sequence plays in HDMI output, including the video intro. Video is played perfectly in internal output (LCD screen) so is not a problem related to drivers or framebuffering. I need a command to say batocera "Hey batocera, It doesn't exists other output than HDMI-1 so don´tt even try to look for other ports to play anything through laptop screen". I know that at the very early linux booting is impossible to drive through HDMI only, but once the first LOGO (boot splash) is shown batocera should be able to direct video to the output set in config or other file, maybe init.d

Any idea? Thanks

**Comment by fabricecaruso** [comment]
Hi,

It's not related to EmulationStation but to batocera.linux.

Please repost in batocera.linux repository

**Comment by madman80** [comment]
Excuse me. I'm sorry. I Not was sure what section match with topic. I write again in the proper section
