### ISSUE TITLE
Issue with theme option or subset label

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1393]
Hi, a minor issue here for the UI. 
The inner modal layer in theme options dont display the right subset option label (displayName attribute) I attach two clarifying images. 

**Theme Options list**
![issue1](https://user-images.githubusercontent.com/73712202/215288061-782c4868-1b1a-46de-8706-4024cf80006a.jpg)

**Inner layer with suboptions list**
![issue2](https://user-images.githubusercontent.com/73712202/215288059-52be1def-a194-414d-b09b-863ac737f00f.jpg)

As we can see, the label in the subset list is "animated background" but in the header of the inner layer it shows "theme systembackground" which is the subset attribute "name" and not the "displayName" atribute.

https://github.com/fabricecaruso/es-theme-carbon/blob/master/theme.xml#L101

Thanks!

**Comment by fabricecaruso** [comment]
ok fixed

**Comment by pajarorrojo** [comment]
thanks
