### ISSUE TITLE
[Issue - x86-64] Scraper for Vic20/C20 set to wrong platform

### ISSUE THREAD

**Issue by generalerusso** [batocera-linux/batocera-emulationstation#1403]
While scraping metadata for the Commodore Vic20 I noticed various wrong image files downloaded for many of the games, and some of them not being found. While checking the `es_systems.cfg` file i've noticed the line for the c20 system is set to `<platform>c64</platform>` instead `<platform>c20</platform>`.

I've found additional info that is documented in the wiki and this [file](https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-app/src/PlatformId.cpp)

**Comment by lbrpdx** [comment]
This is handled in https://github.com/batocera-linux/batocera.linux, I'll fix it. Thank you for your report!
