### ISSUE TITLE
[GAMELIST] Cheevos Icons

### ISSUE THREAD

**Issue by Snapouille** [batocera-linux/batocera-emulationstation#1406]
For theme developers who have planned a special display for the RetroAchievements Cup, I would suggest an option to hide/show the cheevos Icons in gamelists as we already have for flag, savestate icon and manual icon.

SHOW RETROACHIVEMENTS ICONS                              On / Off

![2023-02-22 20_38_28-EmulationStation](https://user-images.githubusercontent.com/105559045/220740735-ff3b2867-d996-489e-805e-907296123a3f.png)

That would be great, wouldn't it?
Thank's for all you do.

**Comment by Sylv1pons** [comment]
Yes it would be great 😇

**Comment by EvilDindon** [comment]
Yes, this feature would be cool. Thanks in advance.

**Comment by pajarorrojo** [comment]
totally agree

**Comment by Darknior** [comment]
For sure, you are right, we have choice for all icons, i think it is logic that this one too would be possible to hide ...

**Comment by Snapouille** [comment]
@fabricecaruso if you ever pass by here 🙏

**Comment by fabricecaruso** [comment]
Done for a while now

**Comment by Snapouille** [comment]
merci chef, t'es au top :)
