### ISSUE TITLE
Variable for ES theme "rom_system" for collections

### ISSUE THREAD

**Issue by BenoitBounar** [batocera-linux/batocera-emulationstation#1410]
Add a "rom_system" variable to the ES theme system to show which system the game belongs to in the collections.

When you are in a collection in grid mode which displays the marquee (so does not display the names of the games) you cannot know to which system the game belongs.

Moreover in list mode or grid with title, you have to activate an option to display the system after the name, which is unsightly/inestetic

**Comment by fabricecaruso** [comment]
it already exists. use in <text>{game:systemName}</text> under a <text> extra

**Comment by BenoitBounar** [comment]
Super, thx

**Comment by pajarorrojo** [comment]
Hi @fabricecaruso , about this binds

https://github.com/batocera-linux/batocera-emulationstation/commit/66cdb4005f191077d37d3a09fe47351da4c14721

Im trying to call the console image in auto collections gamelist with a path like:

`<path>./../_theme_inc/images/consoles/{game:system}.png</path>`

But nothing is showing, the variable works ok like a text, but dont seem to work in paths. What im doing wrong? 

Thanks

**Comment by fabricecaruso** [comment]
can't tell without seeing the full theme

**Comment by pajarorrojo** [comment]
thanks, fixed in 

https://github.com/batocera-linux/batocera-emulationstation/commit/1a390cfe9d7b297983949350b33d1b734eaf8564
