### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by Chipsum** [batocera-linux/batocera-emulationstation#1415]
Hi
Arabic font Cairo (current font), doesn't provide full Arabic characters set
I suggest Vazirmatn font, since it supports Arabic, Arabic Presentation Forms-B, and Persian.
https://fonts.google.com/specimen/Vazirmatn

I tested light 300, it's so simple so nice very readable.
Thanks.

![image](https://user-images.githubusercontent.com/37517008/224382558-2e6c8884-89b9-4c45-abcb-5e29c7892c7d.png)

**Comment by Chipsum** [comment]
Not only that it's more readable but also it's a correct font, complete, with Forms-B all included, which is an important Unicode range.
![image](https://user-images.githubusercontent.com/37517008/229563275-9cce177a-1aa4-4adc-9fdd-2e7ccf972ead.png)

**Comment by nadenislamarre** [comment]
Open Font License.
Looks good to me.

@fabricecaruso is it ok to you : https://github.com/batocera-linux/batocera-emulationstation/pull/1435

**Comment by Chipsum** [comment]
it's just beautiful, really nice ! :smiley: :heart: 
![screenshot-2023 04 03-21h09 10](https://user-images.githubusercontent.com/37517008/229616928-397523c2-f07f-4d09-bfd1-0c6d4fb2f0c1.png)
![screenshot-2023 04 03-21h10 59](https://user-images.githubusercontent.com/37517008/229616957-24dd1425-688b-4145-b2fb-040da8f55f30.png)

**Comment by n2qz** [comment]
PR was merged last year, will close this issue soon unless there is some objection.
