### ISSUE TITLE
Play video on VLC from EmulationStation

### ISSUE THREAD

**Issue by manurafal** [batocera-linux/batocera-emulationstation#1418]
In the configuration of the file es_systems.cfg, I created the data, but the command is not working.

`
< system >

     < fullname > Videos</fullname>
     <name> Videos</name>
     <manufacturer> Videos</manufacturer>
     <release> 2021 </release>
     <hardware> raspberry </hardware>
     <path> / userdata / roms / videos</path>
     <extension> .mp3 .mp4 .wmv .avi .mkv </extension>
     <command> vlc play --fullscreen  --no-video-title-show  --play-and-exit %ROM% </command>
     <platform>pc</platform>
     <theme> video </theme>
     <group>video </group>

< /system >

`
How can I make this option work to watch videos?

**Comment by worstcase-scenario** [comment]
Hi, I'm using EmulationStation on EmuElec on an Android TV-box, so I don't know if it works for you, too, but anyway:

I also have a "movie"-section added in EmulationStation just by putting *.mp4-files into the roms/mplayer-folder. 

They can be played without problems (using mplayer) via EmulationStation... although mplayer is very rudimentary...

My "es_system.cfg" file looks like that:

 <system>
    <name>mplayer</name>
    <fullname>Media Player</fullname>
    <manufacturer>EmuELEC</manufacturer>
    <release>2020</release>
    <path>/storage/roms/mplayer</path>
    <extension>.mp4 .MP4 .mkv .MKV .avi .AVI .mov .MOV .wmv .WMV .m3u .M3U .mpg .MPG .ytb .YTB .twi .TWI .sh .SH</extension>
    <command>emuelecRunEmu.sh %ROM% -P%SYSTEM% --core=%CORE% --emulator=%EMULATOR% --controllers="%CONTROLLERSCONFIG%"</command>
    <platform>mplayer</platform>
    <theme>mplayer</theme>
    <emulators>
      <emulator name="mpv">
        <cores>
          <core>mpv</core>
        </cores>
      </emulator>
      <emulator name="ffplay">
        <cores>
          <core>ffplay</core>
        </cores>
      </emulator>
    </emulators>
  </system>
  
 Perhaps it's worth a try...

**Comment by fabricecaruso** [comment]
you don't need this.
Only set imageviewer to platform and it will be loaded by an internal player.
If you want an external player, then use the full path for vlc in the command
