### ISSUE TITLE
Scrape don't work for GP32 System

### ISSUE THREAD

**Issue by zognic** [batocera-linux/batocera-emulationstation#1419]
Related to this issue opened here
https://github.com/batocera-linux/batocera.linux/issues/8297

> there's no GP32 defined in the scraping options of batocera-emulationstation yet.
This needs to be added to :

https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-app/src/PlatformId.cpp and its .h
https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-app/src/scrapers/ScreenScraper.cpp for Screenscraper, and the others in /scrapers/ if other scrapers provide GP32 metadata

**Comment by fabricecaruso** [comment]
I'm closing this issue as it looks like it was added
