### ISSUE TITLE
bug: a new "Splash" view appears in gamelist options

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1433]
hello @fabricecaruso  a small new bug here. A new "splash" view appears in the view style selector in the theme options. 

![splash-bug](https://user-images.githubusercontent.com/73712202/228588955-883ec3c9-1a5a-4d92-832e-2519ae5b9bc9.jpg)

 I think this is because I have created a piece of code in theme.xml with <view splash>.
https://github.com/pajarorrojo/es-theme-PlayStation-X/blob/master/theme.xml#L34

Even so, that view should not appear, just like the screen view does not appear, for example.

To reproduce you can download the last version of the theme playstation-x.

On the other hand, now that we are talking about the list views, would it be possible to hide the basic view of the list, with some theme tag? I'm thinking something like:

`<theme defaultTransition="instant" hideView="basic">`

Thanks for your work!

**Comment by pajarorrojo** [comment]
I've created this piece of code in theme.xml because inside splash.xml doesn't recognize some ifSubset type filters, basically. In fact, many variables don't work inside splash.xml

I have already realized that simply declaring a view, this appears in the list, but splash is not a view to use, technically it is more like screen or help, it should not appear in the list of available layouts IMHO because is not a layout. I don't see why it has to be a condition that the splash view code can only be written into the splash.xml file (or gamesplash.xml). If I need to create exclusive includes for splash for any reason?. 

I'll try deleting all the basic declarations, as you suggest.

**Comment by pajarorrojo** [comment]
The basic view thing worked as you suggested, I always had the belief that it was an essential list for the theme to work well, and conversations with other developers expressed the same feeling about this. Mystery solved. I should have tried before asking...

Regarding the splash issue, sorry but I must insist that I think it is an error that this "not view" appears like an option for gamelist

**Comment by fabricecaruso** [comment]
did you solve it ? I can't see "splash" in your theme recent version.
If you solved it, please close this issue.

**Comment by pajarorrojo** [comment]
I "fixed" it by deleting the view="splash" declarations from the external files to splash.xml, something I already knew. However, this wasn't the intention of this issue. The intention was to be able to declare the splash view outside the file and prevent it from appearing in the game views list as just another view.

**Comment by fabricecaruso** [comment]
Was fixed in my previous commit.
