### ISSUE TITLE
Turning the monitor off causes excess error logging

### ISSUE THREAD

**Issue by RobG66** [batocera-linux/batocera-emulationstation#1440]
Turning off the monitor, but leaving my PC running causes ES to start spamming the es_log.txt file with errors. Every time the log file writes, it also generates a backup es_log.txt.bak

2023-04-12 04:19:44 ERROR Error initializing SDL!
No available displays
2023-04-12 04:19:44 ERROR Renderer failed to initialize!
2023-04-12 04:19:44 ERROR Window failed to initialize!

**Comment by fabricecaruso** [comment]
This one is probably not directly related to EmulationStation. 
I'm closing this one as we don't even have informations about the test conditions and the concerned system
