### ISSUE TITLE
Reset game counters (times played, etc)

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1443]
Hello, I leave a simple request

I think it would be very interesting to be able to offer an option to reset the game counter. This option could be in the main menu to reset all systems, or in the list or game context menu to reset a single system or a single game. When applying, the 3 related gamelist.xml tags will be deleted:
```
<playcount>
<gametime>
<lastplayed>
```

Thanks

**Comment by Banjo-Oz** [comment]
I would love this to be a menu option too. Currently I had to make a script that does this but it's a pain when a UI solution would be much better and more user friendly/

**Comment by pajarorrojo** [comment]
https://discord.com/channels/357518249883205632/1151478615712731136/threads/1154847449144373259

**Comment by bmn001** [comment]
I'd like this too.  It would be nice to have a "Sanitize" or "Reset gameplay data" menu option somewhere in EmulationStation.

Here's a script that does this at the command line.  It would be nice to have a way to trigger it in Emulation Station.

```
#!/bin/bash

set -e

process_file() {
    local file="$1"
    sed -i -e '/<lastplayed>/d' -e '/<gametime>/d' -e '/<playcount>/d' "$file"
}

export -f process_file

find /userdata/roms/ -type f -name '*.xml' -exec bash -c 'process_file "$0"' {} \;
```

**Comment by Gandolaro83** [comment]
Would like to have this too.

**Comment by fabricecaruso** [comment]
adressed here https://github.com/batocera-linux/batocera-emulationstation/pull/1587
