### ISSUE TITLE
Bad settings.xml breaks cemu-config/WII-U games

### ISSUE THREAD

**Issue by lonelykryptonian** [batocera-linux/batocera-emulationstation#1453]
**Issue:** Bad settings.xml breaks cemu-config/WII-U games.  I've upgraded from Batocera beta v36 to v37 and cannot run cemu-config or run WII-U roms.  Nothing happens double-clicking cemu-config or going to the menu and clicking open.  I can open the other configs.  If I try to run any of my WII-U games it will give the initial splash screen and stay there in the soft-freeze.  I have to hard power off device to recover.  I can ping/WinSCP to Batocera (Steam Deck) during all of this.

**Expected result:** To run cemu-config and run WII-U games

**Reproduction steps:** Upgraded from v37 to Stable build on Steam Deck and problem persisted.  Flashed stable build to new micro-sd and could open cemu-config.  "Updated" to v37 dev build and could still use cemu-config.  Copied dir /userdata/system/configs/cemu and usr/bin/cemu of my broken build and the new working build to compare.  Deleted everything in /userdata/system/configs/cemu on my broken build other than what was there on fresh build, could now open cemu-config.  I was going to add file-by-file back until it broke again.  Added the settings.xml and cemu-config is instantly broken, cannot launch a WII-U game without freeze.  Rebooted to verify it still persists, it did.  Replaced settings.xml with the fresh build and cemu-config works again.

Logs and data: Here is my Batocera v37 support file and the settings.xml
[batocera-support-20230510195631.tar.gz](https://github.com/batocera-linux/batocera-emulationstation/files/11447324/batocera-support-20230510195631.tar.gz)

**Comment by fabricecaruso** [comment]
It's not related to EmulationStation.
Please close this issue and reopen a new one in batocera-linux repository
