### ISSUE TITLE
Name theme collection Folder

### ISSUE THREAD

**Issue by manurafal** [batocera-linux/batocera-emulationstation#1454]
What name should I give to the theme folder for my dynamic collection named DBZ to appear in the Batocera menu without having to disable "Show unthemed collections"?

**Comment by pajarorrojo** [comment]
If you want your custom collection to appear you always have to deactivate that option. The same thing happens to me and all of us and I have come to the conclusion that I think this feature does not work as the label says, it simply groups or does not group the collections, and regardless of whether the collection is themed. Maybe some developer can put some light with this.
