### ISSUE TITLE
Scrape without overwrite the game name or description.

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1457]
Hello, when I scrape just some image, video or whatever, it always overwrites the title or the description of the game, which is quite tedious because I have some titles and descriptions translated or customized. The ideal would be to have an option on the scraping screen to avoid this. 

Thanks

**Comment by TigTog** [comment]
I wholehartedly agree...  the scrap functionality is fantastic except for being able to turn off renaming of the title.  

I've several titles which are slightly different versions and i've manually changed them as such.   The all scrape the same detail, which is the expected behaviour, however the filenames  "Game Title (V1).zip", "Game  Title (2 Player).zip", "Game Title (4 Player).zip" all become 3 entries of "Game Title" without their versions included.  

A small change on the scraper would go a long long way to prevent us all having work arounds and vastly improving the UE.

**Comment by RobG66** [comment]
> Hello, when I scrape just some image, video or whatever, it always overwrites the title or the description of the game, which is quite tedious because I have some titles and descriptions translated or customized. The ideal would be to have an option on the scraping screen to avoid this.
> 
> Thanks

 I was just thinking about this same thing the other day.  For example, screenscraper changes quite a few items it thinks are not games with the name prefix ZZZ:notgame (or something similar).  Many of the scraped arcade descriptions leave a lot to be desired too.

 I wrote a gamelist manager script and have been thinking about a 'post scraping' cleanup to put back ratings, descriptions etc (frome a metadata backup).  Your post serves to make me think this is something worthwhile proceeding with.  It won't take much effort to add.   

Rob

**Comment by Banjo-Oz** [comment]
> > Hello, when I scrape just some image, video or whatever, it always overwrites the title or the description of the game, which is quite tedious because I have some titles and descriptions translated or customized. The ideal would be to have an option on the scraping screen to avoid this.
> > Thanks
> 
> I was just thinking about this same thing the other day. For example, screenscraper changes quite a few items it thinks are not games with the name prefix ZZZ:notgame (or something similar). Many of the scraped arcade descriptions leave a lot to be desired too.
> 
> I wrote a gamelist manager script and have been thinking about a 'post scraping' cleanup to put back ratings, descriptions etc (frome a metadata backup). Your post serves to make me think this is something worthwhile proceeding with. It won't take much effort to add.
> 
> Rob

That would be a pretty cool and useful helper.

**Comment by pajarorrojo** [comment]
Continue in the new channel dedicated to suggestions on discord:

https://discord.com/channels/357518249883205632/1153287066935906355
