### ISSUE TITLE
Xenia Canary crashes when loading any game - Batocera 37

### ISSUE THREAD

**Issue by prince-rakeem** [batocera-linux/batocera-emulationstation#1485]
I am having issues with `xenia canary` on `batocera 37 2023/06/17`  it crashes with a `<nested exception encountered> Faulting thread name: GPU commands (01000004)` error when loading a game.  standard `xenia` seems to work ok

**Comment by fabricecaruso** [comment]
Not related to emulationstation. Please close & repost issue in batocera.linux repository
