### ISSUE TITLE
Lost systems/games after upgrade to V36 from V35

### ISSUE THREAD

**Issue by Noderunner2009** [batocera-linux/batocera-emulationstation#1487]
Please help, upgraded to batocera v36 and now systems/games missing;
All rpcs3 gone
All 3ds gone
Controls configs for wii u became weird

This happened after pressing start and updating game lists.

How to recover these systems/games? Dont understand how to restore after upgrade borking things - please help

**Comment by Noderunner2009** [comment]
On x86 intel laptop

**Comment by Noderunner2009** [comment]
Cemu games and system gone as well

**Comment by Noderunner2009** [comment]
It appears Batocera V36 
AND batocera v37
are not compatible with 8th gen intel chips
Cemu will not work. (Clarification i believe ps3 worked fine). Within cemu app, there was a way eventually i was able to launch game but there was no way for input of controllers to be detected by input API in cemu, thus no way to play. Batocera would never detect system either way. 
A fresh clean install of V37 did not resolve issue.

The fix is to downgrade to V35, took some time to find but previous version for x86_64bit architecture was here:
https://mirrors.o2switch.fr/batocera/x86_64/stable/last/archives/35/

The bummer with this is I lost prboom, so no doom games. I could find any alternative to install manually, copied prboom.wad and stuck it in different directories to no avail.

Hopefully V38 may address having cemu work again.

**Comment by fabricecaruso** [comment]
This issue is not related to emulationstation, but to batocera.linux
Please close the issue, and repost a new one in batocera.linux repository
