### ISSUE TITLE
Audio does not work as expected when Steam Deck is plugged into the dock

### ISSUE THREAD

**Issue by uFarad** [batocera-linux/batocera-emulationstation#1488]
Plugging the Steam Deck into the dock switches the video but not the audio to the HDMI output. Audio must be set manually. Then once the Deck is removed from the dock, you need to manually change it back.

**Comment by nadenislamarre** [comment]
yes. something to implement which is in my todo list.

**Comment by fabricecaruso** [comment]
It's not related to emulationstation but to the system ( batocera-linux ).
I'm closing it.
