### ISSUE TITLE
Standalone ES alternate emulator/core

### ISSUE THREAD

**Issue by Tasosgemah** [batocera-linux/batocera-emulationstation#1494]
I have searched everywhere for some support for the standalone ES but i can't find anything. The caruso build of ES also has a standalone Windows build so i'm hopping i can find an answer here since it's the closest i can get?

Basically, i'm trying to use the "alternate emulator/core" function, if that exists.

When i open the Metadata for a game through the menu, i can clearly see two sections that are named "Emulator" and "Core". These are both set to "Auto" but there's no way to change it not there's anything else to select. How do you make use of this? It's obviously a function that allows you to use a different emulator or core for each game but how do you enable this?

**Comment by fabricecaruso** [comment]
It depends on your es_systems.cfg

**Comment by Tasosgemah** [comment]
> It depends on your es_systems.cfg

Yes, i assumed you have to edit your es_systems somehow to add alternative emulators but i have no idea how you do this and i can't find any information anywhere.

For instance, i need to add an alternative core or emulator for Arcade games. This is how this section looks in my es_systems.cfg:

<system>
    <name>arcade</name>
    <fullname>Arcades</fullname>
    <path>G:\Emulators\MAME\MAMEUI64\Roms</path>
    <extension>.zip .7z .chd</extension>
    <command>G:\RetroArch\retroarch.exe -L G:\RetroArch\cores\mame_libretro.dll "%ROM_RAW%"</command>
    <platform>arcade</platform>
    <theme>mame</theme>	
</system>

So let's say i want to be able to select another emulator/core for Arcades, like FBNeo so it appears as an alternative option in the Metadata. How do i do that?

**Comment by fabricecaruso** [comment]
Look how it's done with Retrobat or Batocera.

**Comment by Tasosgemah** [comment]
I tried asking in the Retrobat discord and the answer i got was that it's made differently in those projects so they can't help. That's the same answer i get most of the time when i ask for something and then have to reveal that i'm using the Windows build of Emulatiostation. 

I tried googling for things like adding alternate emulators in batocera/retrobat/retropie in case i find some random link, but i didn't find anything.

I would appreciate if you could help me here if it's not much to ask.

**Comment by nadenislamarre** [comment]
I dont knowhow  thé anwser could be more précisé than taking thé existing file ans adapt to your needs.

**Comment by Tasosgemah** [comment]
> I dont knowhow thé anwser could be more précisé than taking thé existing file ans adapt to your needs.

I'm trying to make use of this:

![358205613_2580899408740580_4382110046364365025_n](https://github.com/batocera-linux/batocera-emulationstation/assets/12124465/c3f7b090-5257-4674-a426-c091b553f74f)

"Auto" is the only option available. How do i add more emulators or cores to be selectable from here?

**Comment by nadenislamarre** [comment]
I'm n'y phone, i cannot détail. But open es_sysyem.cfg, you'll fond various exemples where for 1 système Thérè are several emulators. Thus once added, restart es and you'll get différents choiced

**Comment by Tasosgemah** [comment]
In es_system.cfg there's only 1 emulator for each system. like this:

<name>arcade</name>

<fullname>Arcades</fullname>

<path>G:\Emulators\MAME\MAMEUI64\Roms</path>

<extension>.zip .7z .chd</extension>

<command>G:\RetroArch\retroarch.exe -L G:\RetroArch\cores\mame_libretro.dll "%ROM_RAW%"</command>

<platform>arcade</platform>

<theme>mame</theme>	

My question is how do you add a second emulator or core in this section? The <command> section only has a single emulator/core. I tried to add a second command line but that doesn't do anything.

That's what i can't find and there's no information anywhere else.

**Comment by Tasosgemah** [comment]
Ok i found that if i add this to the cfg, the Metadata section will make more options appear. For instance:

    <emulators>
          <emulator name="fbneo">
                <cores>
                    <core default="true">fbneo_librerto.dll</core>
                </cores>
          </emulator>
    </emulators>
    
    However, while i can see 'fbneo" in the "emulator" selection, i can't make it work. Obviously, it needs to know where this core is and how to use it. So while this is enough for the alternative selection to appear, it's not enough to make it work.
    
 That's how far i have gone.

**Comment by nadenislamarre** [comment]
Where cores are located is not thé problem of es, but thé one of rétroarch. You must configuré rétroarch for that.

**Comment by Tasosgemah** [comment]
RetroArch is already configured.

I can use alternative cores in other frontends already. The only one i can't do that is EmulationStation.

**Comment by fabricecaruso** [comment]
First : I don't understand why you are trying to use the standalone version. 
It's far easier to install Retrobat and adapt to what you need.
I have no plan to provide support for the standalone version, as there is already a lot to do with batocera & retrobat.

Second : As I said, just install Retrobat and browse the es_systems.cfg. There are working samples for everything you need. 
What you probably need in this case is the %EMULATOR% and %CORE% variables in the command.

Third : I don't know if it's possible for Rocketlauncher to do something with these variables. 
Plus, I won't provide any support with Rocketlauncher. I don't know how this launcher works & it's not part either of retrobat or batocera.

**Comment by Tasosgemah** [comment]
I use the standalone version because i already have all my own emulators/RetroArch/roms/media setup. That's 4 years of work and i'm happy with it. And i already use a few other frontends with it.

Retrobat is not just a frontend, it's a complete pre-made setup package, with the frontend being just a small part of it. I don't want to use that, as i said i have my own.

I just wanted to use the frontend, that's it. Emulationstation looks the best for me. And i'm using it for some time now.

Rocketlauncher was just the "emulator" i was using with arcades, because it has it's own way to select alternative emulators for each game. So i set that in Rocketlauncher and use ES to launch that. But i would prefer if i could just use ES's native way of choosing alternate emulators.

I'll install Retrobat like you say, to check the es_systems.cfg. Thanks.

**Comment by Tasosgemah** [comment]
Anyway the best i can figure out from the example cfg is this:

<system>
    <name>arcade</name>
    <fullname>Arcades</fullname>
    <path>G:\Emulators\MAME\MAMEUI64\Roms</path>
    <extension>.zip .ZIP .7z .chd</extension>
    <command>G:\RetroArch\retroarch.exe -core %CORE% -rom "%ROM_RAW%"</command>
    <emulators>
      <emulator name="RetroArch">
        <cores>
          <core>fbneo</core>
          <core>mame</core>
        </cores>
      </emulator>
    </emulators>
    <platform>arcade</platform>
    <theme>mame</theme>	
</system>

It won't work ofc but i'm wondering how close i am? I can see the cores in the metadata section but the games won't launch.

**Comment by Tasosgemah** [comment]
@fabricecaruso 

So, it's now possible to do this through the es_system.cfg?
