### ISSUE TITLE
Editing genres (or at least fixing them)

### ISSUE THREAD

**Issue by Banjo-Oz** [batocera-linux/batocera-emulationstation#1496]
Is there no way to edit genres? Some have glaring omissions, for example: no "1st Person" or "Parser" subcategories for Adventure, no subcategories at all for Beat 'Em Ups (not even just "2D" and "3D". Yet others have dozens of subcategories, like Shooters.

Also, the selection popup order seems completely borked, with Action RPG appearing under Action rather than Role Playing Games, etc.

**Comment by RobG66** [comment]
You can manually edit genre data all you want, but you risk losing all your changes the next time you scrape.  Just accept that it is what it is and there isn't much you can do about it.  I mostly ignore the subcategories.

Rob

**Comment by Banjo-Oz** [comment]
> 

Do you mean go into the gamelist and manually change the text for game genres?

I was wanting to add new genres to the selection choices/checkboxes.

Regardless, I do wish there was a way to have scraping only fill in missing metadata fields and not replace everything. I am sure this was possible when I was using Emulation Station Desktop Edition (separate fork) on Windows.

**Comment by RobG66** [comment]
Here's my github:  https://github.com/RobG66/Gamelist-Manager

 I have started on a gamelist metadata restore for specific elements if they get changed after scraping.  I don't know when I will have that ready though.  It's not hard to do, it's just the user interface takes most of the effort.

Rob

**Comment by fabricecaruso** [comment]
The list of genres is an import of screenscaper genres. 
It's not modifiable to maintain consistency.

You stil can propose changes if they are interesting to this file in this repository : 
https://github.com/batocera-linux/batocera-emulationstation/blob/master/resources/genres.xml
