### ISSUE TITLE
apfm1000 can't be scraped

### ISSUE THREAD

**Issue by bmn001** [batocera-linux/batocera-emulationstation#1497]
The wiki says "This system scrapes metadata for the “apfm1000” group"

I can scrape some apfm1000 roms individually, but not the entire system.

The ES scraper dialog doesn't include APF M1000 as an option - it's the only system missing from the big list of systems with checkboxes.

**Comment by fabricecaruso** [comment]
apfm1000 system is not known by Screenscraper which is probably the global scraper you are using.
Only HFSDB and TheGamesDB are supported.
