### ISSUE TITLE
v37+ ES not communicating with RetroAchievements API

### ISSUE THREAD

**Issue by chewvodka** [batocera-linux/batocera-emulationstation#1516]
Refer to this:
https://github.com/RetroAchievements/retroachievements-api-js/issues/46

This is mostly just a place holder for the Batocera dev team to monitor and eventually repair the RetroAchievements implementation in EmulationStation.  Currently the API is down while the RA devs upgrade their systems.  Prior to this information, I attempted to remedy the situation myself by verifying how the implementation works.  I discovered that the URL address Batocera uses points to a non-existent location, thus resulting in a 403 error.  The correct error we should be seeing is a 503.  So when the API is finally live again, I think Batocera will need it's URL updated as well.

Steps to reproduce:

1. Create account at RetroAchievements.com and enter Credentials into Batocera
2. Install some compatible games and scrape them
3. Bring up game details and look at the option "View this game's achievements"
4. Results in error message "This game has no achievements yet"

Another issue related to ES.  It will crash when you try to access the RetroAchievements menu item to look at your profile and progress.  Steps to reproduce:

1. Create account at RetroAchievements.com and enter Credentials into Batocera
2. Press "START" on controller to bring up main menu and attempt to click on the option "Retroachievements"
3. Results in ES crashing and restarting.

**Comment by fabricecaruso** [comment]
Crash was fixed.
About the 503 error it's not our fault.
See https://github.com/RetroAchievements/retroachievements-api-js/issues/46
