### ISSUE TITLE
Gamelists updating every time TV switches inputs

### ISSUE THREAD

**Issue by maxengel** [batocera-linux/batocera-emulationstation#1524]
System info:
Disk format: ext4
Temperature: 48°C
Architecture: bcm2711
Model: Raspberry_Pi_4_Model_B_Rev_1_4
System: Linux 6.1.25-v8
Available memory: 7321/7811 MB
Cpu number: 4
Cpu max frequency: 1800 MHz
OS version: 37 2023/06/15 16:32

Steps to reproduce:
1. Connect Batocera RPi to TV via HDMI
2. Switch the TV's input to another active input and away from the RPi
3. Switch the TV back to the input Batocera is running on
4. The game lists will all update

Expected behavior:
I'd expect Batocera to remain at the ES screen where it was when the input was switched.

**Comment by nadenislamarre** [comment]
this is the expected behavior.
batocera need to reopen screen connexion with acceleration in the correct resolution / frequency / driver
