### ISSUE TITLE
Nintendo layout on PC games when using Xbox controller

### ISSUE THREAD

**Issue by petraexe** [batocera-linux/batocera-emulationstation#1530]
**Issue:** When I play a PC game with controller support, the A and B buttons are swapped and the X and Y buttons are swapped.

**Steps to reproduce:** 

1. Drag and drop a Windows game from your PC to Batocera
2. Rename the game folder Game.pc
3. Add an autorun.cmd file to the game folder and write `CMD=Game.exe` in it
4. Launch the game through Batocera
5. Messed up button layout

**Comment by fabricecaruso** [comment]
Not related to EmulationStation -> It's all related to batocera-linux repository.
