### ISSUE TITLE
When I try to scrape without a internet connection, I should get some reasonable error message

### ISSUE THREAD

**Issue by szalapski** [batocera-linux/batocera-emulationstation#1533]
Steps to reproduce.

1. In MAIN MENU, NETWORK SETTINGS, ensure INTERNET STATUS is NOT CONNECTED.
2. Go to any ROM and try to scrape.  Notice that the scrape finds nothing and finishes without explanation.
3. Go to MAIN MENU, SCRAPER, SCRAPE NOW.  Notice that the full scraping process runs, possibly for hours, finds nothing and finishes without explanation.

EXPECTED: There should be some reasonable error message to tell me that I am not connected to the internet, perhaps with a cue to go to the NEWORK SETTINGS and try to fix it.  

ACTUAL: The scrape attempt completes unsuccessfully (perhaps after many hours) and I have no idea why it didn't find anything.

Would anyone consider improving this experience?

**Comment by lbrpdx** [comment]
Upgrade to Butterfly / Batocera 38, it's already done.

**Comment by szalapski** [comment]
Ah, doesn't seem to be in full release yet.  Well, good to know!  I'll try it once it's out.

**Comment by fabricecaruso** [comment]
Did you test it ? It is resolved now ?

**Comment by fabricecaruso** [comment]
I don't have such problems.
