### ISSUE TITLE
nvidia gpu on amd laptop will not launch games on TV (HDMI)

### ISSUE THREAD

**Issue by Noderunner2009** [batocera-linux/batocera-emulationstation#1538]
Batocera main screens work but no games will launch when connected to TV (via HDMI) - no NES, SNES, megadrive nor PSX. They all do work & launch if I disconnect HDMI and use only laptop screen. Please help...

I've had trouble getting HDMI to work with batocera v35, v37 and now beta v38

System: Dell G15 5525 AMD ryzen 6600h with Nvidia 3050 gpu laptop

Output of display.log:
Preferred display is HDMI-1-0
Display Index = 2
Error: No connected DRM connectors found for HDMI at index 2. Trying index 1
Selected DRM connector: HDMI-A-1
Two GPUs detected in the system
Setting best primary GPU...
MPV default drm resolution setting of  x  @  Hz
Current resolution: 3840 x 2160 @ 30.00 Hz
No resolution set, nothing to do...
f_minTomaxResolution: 1920x1080
Requested 1920 x 1080
Current resolution: 3840 x 2160 @ 30.00 Hz
Resolution to use: 1920 x 1080
Using old method = Output: HDMI-1-0 Mode: 1920x1080

batocera-boot.conf has the following:
nvidia-driver=true
#nvidia-driver=legacy
nvidia-prime=true
#amdgpu=true
amdgpu=false
#radeon-prime=true
## See https://wiki.batocera.org/display_issues#force_any_specific_supported_resolution_in_es_instead_of_the_default_maximum_one
#es.resolution=
#global.videooutput=HDMI-1-0
global.dpi=96

Feeling defeated as my old 8145u intel laptop launche games great on my TV without any configuration meddling. But instead here, i've tried many config combos, so many reboots, SSHs, and version v35, v37, and now v38 beta

**Comment by fabricecaruso** [comment]
Sorry, it's not related to EmulationStation. 
Please close this issue & repost in batocera-linux/batocera.linux

**Comment by Noderunner2009** [comment]
> Sorry, it's not related to EmulationStation. Please close this issue & repost in batocera-linux/batocera.linux

Even if its Batocera menus and navigations thats working but displaying any nes or genesis games with hdmi is not? That part is batocera too? Game works on laptop screen but black screen with tv. 
If thays the case, please let me know and i can close here and post to batocera

**Comment by fabricecaruso** [comment]
It's not related to EmulationStation.
