### ISSUE TITLE
[Enhancement Request] Option to Hide or Move the Favorites Icon

### ISSUE THREAD

**Issue by JLiszt** [batocera-linux/batocera-emulationstation#1546]
Greetings... 

I was thinking that it would be nice to have an option to hide the Favorites star icon or to show it before or after the name of the game, similar to the option that already exists for the region flags. Or maybe to only show it in the right sidebar with the manual and retroachievements and save states icons.

Thanks!!

**Comment by fabricecaruso** [comment]
With v39 version, and itemTemplating, you'll be able to create / modifiy themes so you can do this.
-> Responsability will be for the theme, not to emulationstation anymore.
