### ISSUE TITLE
Batocera freeze if a single ROM scraping doesn't work due to an API issue.

### ISSUE THREAD

**Issue by Minamoto-Kobayashi** [batocera-linux/batocera-emulationstation#1547]
For the first time today I experienced a strange issue: while the scraping of an entire set works well as usually, a single ROM
scraping freezed the system! The background music theme was playing as usually, but buttons and joysticks do not reacted anymore.
I was forced to do an hard shut down the system pushing the reset button
Some discord users has told me that it was an API issue, but the system should not freeze anyway when the scraping is not working!
Today everything is back to normality, but I do not understand how a scraping failure can freeze the entire system.
I use Linux 6.3.6 with Batocera latest version (actually 37c 2023/06/17), DELL mini-atx board with CPU Intel i5-4570, 8MB RAM.

**Comment by fabricecaruso** [comment]
I can't reproduce, sorry.
