### ISSUE TITLE
ES "quit" event no loger working correctly after update to v38 of Batocera on Pi4

### ISSUE THREAD

**Issue by cdaters** [batocera-linux/batocera-emulationstation#1548]
I have the following script:

```
#!/bin/bash

. /etc/profile.d/xdg.sh
. /etc/profile.d/dbus.sh

stop_audioconfig() {
	VOLUME=$(batocera-audio getSystemVolume)
        (sleep 25.5 && shutdown -h now) & /etc/init.d/S06audio reload && /usr/bin/batocera-audio setSystemVolume "${VOLUME}"
        sleep 0.5 && /usr/bin/mpv --player-operation-mode=pseudo-gui --keep-open=yes --stop-playback-on-init-failure=no --ontop --really-quiet --audio-exclusive=yes --no-config --fullscreen --no-osd-bar --cursor-autohide=always /userdata/shutdown/shutdown.mp4

     }

trap 'stop_audioconfig' EXIT
```

 in the following location:
```
/userdata/system/configs/emulationstation/scripts/quit/shutdown.sh
```

The was working in v37 just fine, it would play my full video and then shut down. However, after updating Batocera to v38, now the script plays a short 1 to 1.5 seconds (of the 25s video) before the system just shuts down.

I have simplified this down to just:
```
#!/bin/bash

/usr/bin/mpv --fs /userdata/shutdown/shutdown.mp4
```
And it plays maybe 2 seconds of my video before shutting down.

**Comment by fabricecaruso** [comment]
It's still working... It's just that EmulationStation is not waiting anymore for the scripts to end...
It was changed because there were lags with many scripts.

**Comment by ssokolow** [comment]
So you're saying that, even if my `shutdown` script to `rsync` changes to `/userdata` to `192.168.0.2:/mnt/Seagate_10TB/tier2/batocera_backups/backups/` hadn't stopped working with the v38 update, Batocera would force the issue and kill it mid-backup?

**Comment by fabricecaruso** [comment]
Fixed it making quit event waitable
