### ISSUE TITLE
(V38) after update, no savegames on n64

### ISSUE THREAD

**Issue by chakula** [batocera-linux/batocera-emulationstation#1549]
since the update, the game saves no longer work. (glide64mk2 for n64)
I copied the old savegames and tried them with a new 37 installation. the memory location is the same, the name is also saved the same way. they also have the same extension.

Thus not compatible with each other

**Comment by fabricecaruso** [comment]
More precisions are required : 
- Do EmulationStation sees the savestates in the pane ? If they are visible... It's not related to EmulationStation but to the emulator. Then you can close this issue as it's not related to EmulationStation.
- If they are not visible, you have to tell us what you have in your folders.

**Comment by chakula** [comment]
i see the files in the file manager. 
i searched for the glide64mk2 site... i found the github site from it. last update 2015.
So the emulator cant chance the save settings... its the same.
but after i made the update to 38, glide64mk2 cant use the safegames.

**Comment by fabricecaruso** [comment]
You don't answer the questions.
What do you mean by "file manager" ? Is it the emulationstation savestate manager ?

**Comment by chakula** [comment]
When i Push f1 in batocera,i See the File Manager.
Sorry im a User ,i dont know what Part is emulationsstation,what part is the os..
I think im wrong Here and close
