### ISSUE TITLE
[V38] Screensaver-started ES script not executed when Screensaver is set to 'slideshow'

### ISSUE THREAD

**Issue by dannn-o** [batocera-linux/batocera-emulationstation#1550]
I had reported this issue originally with V37 (#1477), and tested the fix successfully with V38 when it was still in "Beta".  I recently updated my system from V37 to V38 (Stable), and the fix appears to have regressed and the original issue is back.  If I have Screensaver configured as "Slideshow", the script (at /userdata/system/configs/emulationstation/scripts/screensaver-started) does not get executed when the slideshow begins.

**Comment by fabricecaruso** [comment]
"screensaver-started" event does not exist.
The event is named "screensaver-start"

https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-app/src/SystemScreenSaver.cpp#L76

**Comment by dannn-o** [comment]
I meant to state that I searched Github and saw the "screensaver-start" reference you list above, but wasn't sure if it was replacing the naming conventions used by @nadenislamarre in v37 (screensaver-started and screensaver-stopped. see https://github.com/batocera-linux/batocera.linux/issues/9181).  But, I went ahead and renamed the script folder to be `/userdata/system/configs/emulationstation/scripts/screensaver-start` and retested before I opened this isue, but the script still did not execute.  Do I need to open a new issue, then?

**Comment by fabricecaruso** [comment]
Don't know what to say. 
It's working fine with "screensaver-start"

**Comment by dannn-o** [comment]
The scripts I use invoke Pixelcade...could the issue be particular to the code added in V38 to add native support for Pixelcade?

I have a script that is copied to both `/userdata/system/configs/emulationstation/scripts/screensaver-start` and `/userdata/system/configs/emulationstation/scripts/sleep`.  When I set the Screensaver Type to "**DIM**" (after 1 minute), the script in the "sleep" folder run successfully after the screen dims, blanking out the Pixelcade DMD.  When I set the Screensaver Type to "**SLIDESHOW**" (after 1 minute), the script in "screensaver-start" does not appear to run, as the Pixelcade DMD does not blank out (and, the Pixelcade logs do not show the calls happening as it shows when the "**DIM**" option works successfully), though the slide show begins as expected.  Let me know if there are any log files to investigate, or if there is specific diagnostic code I can add to the script logic that could help.

**Comment by fabricecaruso** [comment]
There'are no differences in scriptings between DIM and SLIDESHOW.
There are no logs for calling scripts. You can try something like outputing something (the date?) to a file in another folder to make sure your script is called. ( something like " date > /userdata/system/configs/emulationstation/datetime.txt " )
If you script is called it's something else.

EmulationStation is not responsible for what was done on Batocera with Pixelcade.
If there's a conflict, I can't help.

**Comment by dannn-o** [comment]
Well, I coded some debugging logic to the scripts involved, and from what I see there is a difference between DIM and SLIDESHOW.  DIM caused the "Screensaver-Start" script and the "Sleep" script to be run in succession.  SLIDESHOW only caused the "Screensaver-Start" script to run.  I plan to try and inspect the Pixelcade code later, as running the "Screensaver-Start" script should have been enough to cause the DMD to blank out.  But, I don't know why DIM is invoking the "Sleep" script, and I'm confident that is why the Pixelcade logic is working with DIM, but not SLIDESHOW.

Here is the debugging log output:
```
Tue Oct 24 06:50:51 AM EDT 2023
Screensaver-start script now running...
Tue Oct 24 06:50:51 AM EDT 2023
Sleep script now running...
Tue Oct 24 09:37:55 AM EDT 2023
Screensaver-start script now running...
```

**Comment by fabricecaruso** [comment]
Ok, so there's no problem with EmulationStation.

"Sleep" is something that reduces emulationstation framerate. It's automatic with DIM/BLACK. It's not for other screensavers type that require animations.

Just ignore sleep event.

**Comment by dannn-o** [comment]
The main thing for me was finding out the naming convention had changed from the V38 Beta fix (from "screensaver-started" to "screensaver-start").  The secondary problem, which was masked by DIM because of the 2nd script executing, seems to be a separate timing problem...that's the one I brought to Al at Pixelcade's attention and assume he has Batocera Team contacts if he needs help with diagnosing.  Thx.
