### ISSUE TITLE
Music player can get stuck in loops with MOD/XM/IT/S3M/... formats

### ISSUE THREAD

**Issue by ssokolow** [batocera-linux/batocera-emulationstation#1554]
When I included some of the tracker music from a compilation of keygen tracks in `/userdata/music`, I discovered that, unlike any other music player I've ever used, EmulationStation will get stuck looping infinitely if the song specifies loops.

It looks like EmulationStation is missing whatever call players like Audacious Media Player use in their plugins based on ModPlug, OpenMPT, etc. to request that the mod player ignore attempts to loop.

**Comment by fabricecaruso** [comment]
No.

We're using SDL_Mixer to play music. 

If this lib has problems with some file formats, we can't help unless rewriting everything by changing the library.
We don't plan to do that.

You can probably ask them & open an issue in their repository, instead.

**Comment by ssokolow** [comment]
I just checked with the version of SDL_mixer included with Kubuntu Linux 20.04 LTS and its `playmus.c` example and I can't reproduce the problem, so either SDL_mixer got fixed/regressed or EmulationStation is invoking it differently.

([moonflight.xm](https://modarchive.org/index.php?request=view_by_moduleid&query=165282) is one of the mods that loops infinitely under EmulationStation while terminating after the expected 1:01 in everything else including said `playmus.c` test.)

Granted, `playmus.c` uses either `0` (no loop) or `-1` (loop infinitely) for the loop count rather than `1` like batocera-emulationstation's `if (Mix_FadeInMusic(mCurrentMusic, 1, 1000) == -1)` ([line 270](https://github.com/batocera-linux/batocera-emulationstation/blob/9075a8f738bae28c22987420afec572978f133bb/es-core/src/AudioManager.cpp#L270) in `es-core/src/AudioManager.cpp`), but changing that to `1` in `playmus.c` doesn't reproduce the problem either.

Where are the instructions for compiling and testing patches to batocera-emulationstation and what's your procedure for matching what I assume to be a vendored SDL_mixer back to an upstream revision?

**Comment by fabricecaruso** [comment]
I reproduce too with your XM file & sdl_mixer 2.6.3.0. We never receive a finish event.
Changing Mix_FadeInMusic to use 0 instead of 1 does not change anything. 
Maybe it's related to another dependency ( libmodplug ? ). I don't know...

I'm not going to spend time on this one as it's related to an external library.
Audio files can always be converted to another format.

**Comment by ssokolow** [comment]
I'd still like to try to track down where the problem lies so I can report it upstream.

Could you point me toward a guide on how to make and test Batocera builds so I don't have to play "guess the versions" with things like libmodplug on my regular distro environment?

**Comment by fabricecaruso** [comment]
I don't know I never built batocera-linux myself.
I work with Visual Studio on Windows.

I know there is this guide : https://wiki.batocera.org/compile_batocera.linux
