### ISSUE TITLE
MSX1 and MSX2 scrapes data from wrong platform

### ISSUE THREAD

**Issue by Gandolaro83** [batocera-linux/batocera-emulationstation#1561]
I have scraped data from ScreenScraper.fr for MSX1 and MSX2 system but 99% of information where not found. Data for almost every game are avaible on ScreenScraper.fr.

After analyzing the few games it scrapped I'm almost sure that when connecting to ScreenScraper.fr MSX1 scraped data from MSDOS repository instead of MSX1 repository, and something similar is happening for MSX2.

To reproduce the bug, in MSX try scraping with string Knightmare, you will find that it is downloading MSDOS picture and not the MSX1 one. Another way to reproduce it is this... try input the string Hook, a game does not exist for the MSX, it results displaying Hook MSDOS game.

**Comment by n2qz** [comment]
Not an EmulationStation issue.  Needs to be fixed in the batocera.linux repository.
