### ISSUE TITLE
v38 - Audio volume sets to 100% after reboot

### ISSUE THREAD

**Issue by sgargallo** [batocera-linux/batocera-emulationstation#1563]
In Batocera 38 (at least in Bcm2836, Bcm2837 and Bcm2711) no matter the audio volume is set, always go to 100% after reboot. Usign default audio settings with HDMI audio. Tested in Pi Zero 2W (Bcm2836 and Bcm2837) and Pi 4 (Bcm 2711). In order to reproduce it, just use the clean image, set audio volume in ES, reboot and open the config menu in audio settings. After further testing I've detected that the problem comes at certain point reading settings from batocera.conf in ES. If you reboot the system and don't enter the settings menu, the volumen stays the same and "batocera-audio getSystemVolume" reads the correct value, but when you open it, ES defaults it to 100% and applies that value to the system. I hope this can help. Thank you!!

**Comment by fabricecaruso** [comment]
Should be fixed in next version
