### ISSUE TITLE
Can not upload mp4 video via HttpApi

### ISSUE THREAD

**Issue by jsm174** [batocera-linux/batocera-emulationstation#1572]
According to the docs, it looks like we should be able to upload a video via the HttpApi:

`POST /systems/{systemName}/games/{gameId}/media/{mediaType}		-> body must contain the file bytes to save. Content-type must be valid.`

Whenever I try to upload a video, I get `404 media not found`. I'm setting the content type to 'video/mp4'.

`POST http://192.168.1.170:1234/systems/vpinball/games/53537ca15aabd46fdfbe26d9c6d3de33/media/video`

![Screenshot 2023-11-05 at 7 02 39 PM](https://github.com/batocera-linux/batocera-emulationstation/assets/1197137/a9cba31d-ebd3-44b1-936e-1f43ce834cbb)

I have no issues uploading images using the same method

`POST http://192.168.1.170:1234/systems/vpinball/games/53537ca15aabd46fdfbe26d9c6d3de33/media/image`

![Screenshot 2023-11-05 at 7 01 16 PM](https://github.com/batocera-linux/batocera-emulationstation/assets/1197137/81e09be7-fd9d-44da-bb51-8a7ee2202cfe)

**Comment by fabricecaruso** [comment]
You're right.
Fixed there https://github.com/batocera-linux/batocera-emulationstation/pull/1573

**Comment by jsm174** [comment]
Thanks for getting this done so fast! I tested this successfully!
