### ISSUE TITLE
v39-beta 2023/11/08 not load in Beelink SER4

### ISSUE THREAD

**Issue by coutow** [batocera-linux/batocera-emulationstation#1576]
when updating the batocera on the mini pc beelink ser4 it is not loaded, however I can perform a downgrade by accessing via ssh to v38, in the initial beta versions of 39 the system loaded the emulationstation normally

**Comment by fabricecaruso** [comment]
I don't understand anything...
Anyway it's not batocera-linux repository, but emulationstation. And, it looks like it's not related to EmulationStation
