### ISSUE TITLE
RetroAchievements: Activate/deactivate hardcore/softcore mode per game and per system

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1585]
### Issue description

Hello,
I think it would be very cool for the UX to allow activate/deactivate hardcore/softcore mode per game and per system regardless of the global configuration. This option could be placed in both context menus, either for a stand-alone game, or per system.

Thanks again

**Comment by fabricecaruso** [comment]
Interesting. 

But it's not something that should be managed by EmulationStation.
It's  a "configuration" problem of the distribution that does not require code changes in EmulationStation.

A new feature should be added inside es_features.cfg for emulator/cores that support cheevos and be managed by configgen / emulatorLauncher which are specific for the distributions.

Please close this issue and move it to Batocera-Linux repository ( and also https://github.com/RetroBat-Official/emulatorlauncher ) - I don't know what distribution you use.

**Comment by pajarorrojo** [comment]
ok, moved

https://github.com/batocera-linux/batocera.linux/issues/10443

**Comment by fabricecaruso** [comment]
For your information. I did spread the word to the Retrobat team, and it was added for the future v6.
See how it was achieved here, if you want to inspire an propose for Batocera too :
https://github.com/RetroBat-Official/emulatorlauncher/pull/239/commits/49e663241e09ab5ea4a9c365f516e6fee4b65d67
