### ISSUE TITLE
Tandy Video Information System (vis) scraper missing

### ISSUE THREAD

**Issue by Geier97332** [batocera-linux/batocera-emulationstation#1596]
The ES scraper dialog doesn't include Tandy Video Information System (vis) as an option.
I use a RPI 4 with Batocera 38.

**Comment by fabricecaruso** [comment]
This system is unknown for screenscraper & hfsdb.
Only TGDB knows it but only has front boxes and english descriptions. 
I'll add TGDB support, but it won't be very interesting.

**Comment by Geier97332** [comment]
Ah, ok!
Thank you!
