### ISSUE TITLE
Add network interface MAC addresses in System Info

### ISSUE THREAD

**Issue by damajor** [batocera-linux/batocera-emulationstation#1599]
### Issue description

Hello,

Connecting the first time on secure Wifi networks that filter client with MAC address can be a pain if the UI does not show this information.

So adding MAC addresses for all network cards in "System Setting" -> "Information" could be a real good idea I think.

Cheers :)

**Comment by fabricecaruso** [comment]
I'm closing this issue because it's not related to EmulationStation. 
The system information is provided by a script in batocera-linux.
