### ISSUE TITLE
[v38 - RP64] Retroachievements: "The g must not be greater than 100"

### ISSUE THREAD

**Issue by Maxpako** [batocera-linux/batocera-emulationstation#1606]
### Batocera build version

v38

### Your architecture

RockPro64

### Your Graphic Processor Unit (GPU)

Integrated (e.g. Intel HD 550; RX Vega 8)

### Graphical brand

None

### Issue description

While setting themes, I just noticed this error while trying to enter in the Retroachievements section.

### Expected result

Get into the Retroachievements menu to see progress

### Reproduction steps

I don't exactly know how this happened, but so far, all I did was to add some more roms, scrap them and then tried to get in the Retroachievements section.

### Logs and data

Nothing found in /var/log/messages

**Comment by n2qz** [comment]
Fixed in #1598, closing issue.

**Comment by SteamRex25** [comment]
how do I fix this error?

**Comment by lbrpdx** [comment]
@SteamRex25 stop cross-posting the same question. I already responded to the issue you opened.
