### ISSUE TITLE
[Enhancement request] - allow option to exclude external paths (network shares) from "Backup User Data" process

### ISSUE THREAD

**Issue by dannn-o** [batocera-linux/batocera-emulationstation#1608]
### Issue description

The "Backup User Data" menu option in Batocera EmulationStation (System Settings - Backup User Data) is a very handy feature.  It would be helpful, though, if there were some way to exclude external paths (network shares) from being copied with the backup request.

In my setup, I have an NAS share mounted to Batocera (via `sharedevice=NETWORK` and `mount.cifs` commands in the batocera-boot.conf file) which contains my music directory.  This, in turn, is used by my audio player of choice, Quod Libet, installed as a Flatpak.  The entire directory is over 50 GB in size, and is mounted under `/userdata/system`.  When running the "Backup User Data" process, this NAS share is included in the backup, and I do not want it included as I already have separate backup processes for all data on the NAS.  The Batocera backup is being done to internal storage, and including the NAS directory would not only take an inordinate amount of time, it also would needlessly use up 50+ GB of space.

For now, the workaround is to unmount the directory before performing the backup.  But, in cases when I forget to do that, I have to force the Batocera computer off by holding in the power button, since there is no way via the GUI to cancel the backup request.  Maybe a menu, similar to the one presented in ES for selecting/deselecting systems to "Scrape", can be displayed to give the user an option to select/deselect mount points for "Backup User Data."

**Comment by fabricecaruso** [comment]
It's not related to Emulationstation but specific to Batocera.
Everything about backup is managed by scripts.
I'm closing this issue as it's not related to emulationstation. Reopen it in batocera-linux.
