### ISSUE TITLE
Retro achievements error "The G must not be greater than 100"

### ISSUE THREAD

**Issue by SteamRex25** [batocera-linux/batocera-emulationstation#1609]
### Concerned project

Batocera

### Distribution Version

Batocera v38

### Architecture

Raspberry Pi4

### Issue description

Whenever I try to see my achievments in the main menu, it keeps giving me this error, I dont know how to fix this.

**Comment by SteamRex25** [comment]
can someone please tell me how to fix this?

**Comment by lbrpdx** [comment]
This is a change on retroachiemenents.org’s side. The API has been updated on current ES (available shortly on Batocera Butterfly), so upgrading to Butterfly is one way to fix this.

As this impacts every user on every Batocera versions 38 and lower, we had a chance to ask a Retroachiements admin if they could consider a fix on their side too to keep backwards compatibility.  They’re considering it. That might be another “silent” fix, but this one isn’t under Batocera’s control.

**Comment by SteamRex25** [comment]
what do you mean upgrade to butterfly?

**Comment by SteamRex25** [comment]
updating broke some of the emulators I use most, now what?

**Comment by lbrpdx** [comment]
“Now what?” “No help?” First, you’ll have to be patient, read the documentation and in particular the troubleshooting section of the wiki. Batocera is a free and open source solution, you’re not paying for a commercial product and its support, so make a minimal effort.  If you want help, you need to provide relevant information not just “it broke”. If you want faster access to other Batocera users, you might get it on the Batocera Discord server. But come prepared with logs and everything explained in the troubleshooting chapter of the wiki. 
Finally, this seems to be a completely different issue than the RetroAchievements one where I gave you help and details on the reasons why. So, no need to keep writing on this ticket now closed.
