### ISSUE TITLE
Games Running slower than they Should???

### ISSUE THREAD

**Issue by SteamRex25** [batocera-linux/batocera-emulationstation#1610]
### Concerned project

Batocera

### Distribution Version

Batocera v39-dev-4f0251e601

### Architecture

Raspberry Pi4

### Issue description

Whenever I try to launch a game, it seems to run slower than it should, this happens on every game. how do I fix this?

**Comment by SteamRex25** [comment]
Too clarify, The music slows down, and the game itself seems to just not go as fast as it should

**Comment by fabricecaruso** [comment]
Did you really read the header of the issue template ??? 
It's not related to EmulationStation, so i'm closing it.
