### ISSUE TITLE
Games Index for A2600 cheevos

### ISSUE THREAD

**Issue by Snapouille** [batocera-linux/batocera-emulationstation#1621]
### Concerned project

Both

### Distribution Version

Batocera 39 beta, Retrobat beta

### Architecture

Windows 10 (Retrobat) and x64 Batocera

### Issue description

Game indexing for the Atari 2600 (Atari2600) no longer works, either on batocera v39 beta or on Retrobat beta.

**Comment by fabricecaruso** [comment]
I just tried (after deleting my gamelist.xml ) and it works perfectly....

The problem is on your side, sorry.

![image](https://github.com/batocera-linux/batocera-emulationstation/assets/51082152/99d6e151-795d-4208-b9d5-e110184d74f9)

**Comment by fabricecaruso** [comment]
After checking the "atari2600 (V1.2 Gilou9999)" set, and compared to a GOOD romset.
There are many games that have an unknown hash in this set.

Exemple for the game Asteroids (USA) :
The hash of this game on your set is B227175699E372B8FE10CE243AD6DDA5
It's unknown with retroachivements.

The only supported hash is dd7884b4f93cab423ac471aa1935e3df
See on this page. https://retroachievements.org/linkedhashes.php?g=11687

So, It's not a problem with EmulationStation but to the romset...

Either change the romset, either contact retroachivements.org

**Comment by zognic** [comment]
I suspect a sporadic issue with Retroachievement API. I can reproduce now, it was OK yesterday.

**Comment by Snapouille** [comment]
still blocked for me, even though I checked my hashes and I don't use the "atari2600 (V1.2 Gilou9999)" set.

For example here the hash from my game "Princess Rescue"
![2023-12-23 18_02_38-MD5 File Checksum - Online Tools — Mozilla Firefox](https://github.com/batocera-linux/batocera-emulationstation/assets/105559045/670c5111-53ec-4a8a-9cd3-67858af6a66d)
and here the supported hash game files :

![2023-12-23 18_03_00-Supported Game Files - ~Homebrew~ Princess Rescue · RetroAchievements — Mozilla ](https://github.com/batocera-linux/batocera-emulationstation/assets/105559045/4b998820-2967-4f21-b913-11b6d024d041)

Having said that, it's far from being a major problem, I just wanted to warn you. 
Now, if it's better for me to keep my mouth shut, I'll do so in future.

**Comment by fabricecaruso** [comment]
No game is working ? you probably have cheevos feature missing in es_features.cfg.
Could you provide that file so we can check ?

**Comment by Snapouille** [comment]
All the games work correctly with the retroachievements, only the cheevos icons don't appear after a Games indexing.
Here my es_features.cfg and es_systems.cfg : 
[es-files.zip](https://github.com/batocera-linux/batocera-emulationstation/files/13781874/es-files.zip)

**Comment by fabricecaruso** [comment]
you mean you have correct `<cheevosHash>` and `<cheevosId>` values in gamelist.xml ??
Are you sure you did not uncheck "show retroachivements icon" for this system ?

**Comment by Snapouille** [comment]
I think we don't understand each other. 
I don't have <cheevosHash> and <cheevosId> after a "Games indexing".
ES say "Indexing completed. Update gamelists to apply changes", but after update nothing is incremented in the gamelist, neither <cheevosHash> nor <cheevosId>.
![2023-12-28 13_45_01-EmulationStation](https://github.com/batocera-linux/batocera-emulationstation/assets/105559045/f53775e1-473f-4cf2-a49d-9ce976c3ebe5)

**Comment by Snapouille** [comment]
If I insert the lines myself in the gamelist it works.

**Comment by fabricecaruso** [comment]
Anyway. Since several days, every access to their doRequest.php API has been forbidden on retroachivements.org and returns a 403 error, so indexing is no more possible since a few days.
I contacted them... 
As long as they block us, we can't test anymore.

**Comment by fabricecaruso** [comment]
For your information, I wrote a bit of code ( in my latest PR ) to manage & display the received error from their servers when they send an error. 

This is what I get actually :

![image](https://github.com/batocera-linux/batocera-emulationstation/assets/51082152/43cc16b6-84bb-4356-adb1-38a4fe6e4fe5)

As long as they block us, we can't index games, and we also can't activate achievements ( if not activated )
