### ISSUE TITLE
[36 stable, Pi4] EmulationStation hangs on loading ckau-book theme

### ISSUE THREAD

**Issue by alephnaught0** [batocera-linux/batocera-emulationstation#1624]
I have a real weird problem!

I’m running 36 stable on a Pi4. I’ve been using my favourite theme (ckau-book) for aaages with no issues whatsoever. Yesterday I was doing a bit of tinkering with control schemes for various platforms, a little scraping, nothing especially dramatic. Haven’t updated Batocera recently, or changed or updated my theme. Last thing I did before things broke was toggle MAME off in the “displayed systems” menu.

Then all of a sudden, it won’t boot. I get the ES loading screen going through all my systems, then it gets to “Collections” with a full loading bar, and just hangs there.

I tried reversing basically every change I had made that day, one at a time, to no avail whatsoever. I started trying other things in desperation, and eventually tracked the problem down. If I switch to another theme, it boots just fine. Literally any other theme. Except ckau-book. Even if I delete and re-install it (which I have a few times now), it still hangs on boot.

Which is.. like I say.. super weird! I hadn’t changed anything theme-related at all, so for ES to suddenly out of nowhere refuse to boot with this theme seems bonkers. And I really like it, so I don’t much want to switch things up. I’ve tried clearing caches, toggling various frontend options on and off, no joy. Nor do the EmulationStation logs show any errors or warnings of note.

Hugely appreciate any ideas you may have for things to try. This could of course be an issue with the theme itself rather than a Batocera bug so it may be out of scope, but I'd like to find out!

**Comment by fabricecaruso** [comment]
you probably have not enougth VRAM set, so it keeps on loading/reloading medias.
Try increase the VRAM amount and make sure "optimize images" is checked.
