### ISSUE TITLE
Looping OGG files not working anymore on emulationstation interface after V36

### ISSUE THREAD

**Issue by MrVictorFull57** [batocera-linux/batocera-emulationstation#1635]
When adding music files in OGG format, they usually play without any problems, even when editing the metadata of these files by adding loop points to them by using the LOOPSTART and LOOPLENGTH tags (in sample format, curiously, just like in RPG Maker), they usually play endlessly without any interruption and without any audio cuts, just like a video game song would play.

Despite this rather cool feature, it wasn't even documented on the wiki page below that teaches how to properly add music on the emulationstation interface, which would be a good thing if it were updated.

https://wiki.batocera.org/emulationstation:music

But what I wanted to point out to is to the fact that after upgrading the system to version 36 (the most recent so far), this looping music feature is not working anymore, not even after modifying the tag formats of the music files to similiar tags.

Then I'd like to know what could have happened for this problem to start to occur (some missing file, codec change or something similar) and if possible a solution or a workaround for this. And congrats for the excellent work. Your system is amazing to use and i'm having a great time with it.

Note: this was found using the x86_64 version. and sorry for some typos here and there, english isn't my native language.

**Comment by fabricecaruso** [comment]
> Transferring to emulationstation repository

It's not directly related to EmulationStation. ES code has not been changed for 2 years, now.

I think, it's related to something in the sdl_mixer version you are installing with BR.
I know there are problems with loops in XM modules too.

I won't investigate such a thing.

Anyway users still can convert their files to mp3.
