### ISSUE TITLE
Screensaver doesn't engage after 5m of idle with 5m idle set on v38 / Steam Deck (original LCD)

### ISSUE THREAD

**Issue by SteveDevOps** [batocera-linux/batocera-emulationstation#1639]
### Concerned project

Batocera

### Distribution Version

v38 2023/10/14 21:43

### Architecture

Steam Deck (original LCD)

### Issue description

I have tried to set screensaver to either DIM or BLACK in settings on v38 / Steam Deck.. to no avail. Running off of micro sd card / booting from bios. Using 5min of Idle in settings. It doesn't engage, I've timed it.

USER INTERFACE SETTINGS->SCREENSAVER SETTINGS
set to 5m, and TYPE as BLACK or DIM

Is this a known bug or am I missing an additional setting? I have it set to activate after 5min of idle time and it happens at some point later.. not 5m of idle. 

Other conditions:
I am actively running Scraper. Unit is connected to hub dongle via usb-c which is providing hard-line network and power.  This is a situation where I need to ensure the screensaver engages on time because I'm leaving it to Scrape overnight and I don't want excessive heat generated or screen burn.

_**Does scraper execution trump idle time?**_

**Comment by fabricecaruso** [comment]
Yes. Scraper resets idle time. 
You can't activate screensaver while scraping or indexing games.
