### ISSUE TITLE
EmulationStation crashes when removing the first entry in the Favorites section

### ISSUE THREAD

**Issue by Tasosgemah** [batocera-linux/batocera-emulationstation#1642]
### Concerned project

Standalone emulationstation

### Distribution Version

continuous-master dated 3-Jan-04

### Architecture

Windows 10

### Issue description

When i remove the first entry in the Favorites list, EmulationStation crashes. This mostly happens after i just opened the program and this is the first thing i do, or when i add an item in the favorites and then remove it immediately after (it has to be the first item in the list).

### Logs and data

ERROR	Interrupt signal SIGSEGV received.

**Comment by fabricecaruso** [comment]
should be fixed by https://github.com/batocera-linux/batocera-emulationstation/issues/1642

**Comment by Tasosgemah** [comment]
> should be fixed by #1642

Yes, it doesn't crash anymore. But now the star icon doesn't appear/disappear when you add/remove a favorite in real time, the result only appears after you restart EmulationStation.

**Comment by fabricecaruso** [comment]
You're right. My mistake. 
Should be fixed by https://github.com/batocera-linux/batocera-emulationstation/pull/1645
