### ISSUE TITLE
Mute imagegrid videosnap through theme code

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#1649]
### Issue description

I think that is necessary an equivalent to the {game:video} element attribute` (<audio>false</audio>),` but specifically for the videosnap within the tile of the imagegrid that we display using the `<showVideoAtDelay>` attribute.

Thanks

**Comment by fabricecaruso** [comment]
already possible using <video name="gridtile.video">

**Comment by pajarorrojo** [comment]
Really? thanks a lot for the info, i will try now :)
