### ISSUE TITLE
Access to the terminal through the menu

### ISSUE THREAD

**Issue by Mr-Bajs** [batocera-linux/batocera-emulationstation#1654]
### Issue description

I think it would be a QoL improvement if the terminal would be accessed through system settings or similar like that.

**Comment by fabricecaruso** [comment]
@nadenislamarre What's your point of view ?

**Comment by nadenislamarre** [comment]
if it already available via f1 => application => terminal

**Comment by nadenislamarre** [comment]
batocera is a gaming console, not a windows system :-P
in worst case, batocera supports power off.
and if you really want, you can connect from a pc or a phone via ssh.

**Comment by nadenislamarre** [comment]
yes, it is not simple to add for the benefit.
but maybe the question is : why do you need to kill processes ? it should not happen.
