### ISSUE TITLE
Odroid N2 8bitdo Question

### ISSUE THREAD

**Issue by blisstik** [batocera-linux/batocera-emulationstation#167]
Hello,

I have a question regarding using 8bitdo SN30pro and 8bitdo Retro Receiver. On a Ubuntu build, ES does not detect the controller until I set the Retro Receiver mode to MacOS via Select + Right on the Dpad.

On batocera, it detects the controller as "Sony Computer Entertainment Wireless Controller" right after pairing with the Retro Receiver, which is a very good solution.

My question is, where is this code changed? Within ES or kernel or OS?

**Comment by blisstik** [comment]
not retro receiver but usb wireless adapter -> https://www.8bitdo.com/wireless-usb-adapter/

**Comment by lbrpdx** [comment]
BT code is shared between ES and OS... have your tried on a more recent Batocera version? 5.25 introduced a lot of changes for BT controllers.
