### ISSUE TITLE
Page up/down skipping too many pages in grid mode

### ISSUE THREAD

**Issue by rdagger** [batocera-linux/batocera-emulationstation#1674]
### Batocera build version

V38oc 2023/10/14 21:43

### Your architecture

Core i3-4010U

### Your Graphic Processor Unit (GPU)

Integrated (e.g. Intel HD 550; RX Vega 8)

### Graphical brand

Intel

### Issue description

I'm running the ES-Theme-Carbon theme with a 3x2 grid. Whenever I hit page up or down, the game list jumps 4-1/2 pages instead of just one.

### Expected result

The page should just up or down 1 page at a time or provide the ability to adjust the number of pages.

### Reproduction steps

1. Set ES-Theme-Carbon theme.
2. Set default grid size to 3x2.
3. Click an emulator with a lot of games like mame.
4. Press page down or up.

**Comment by fabricecaruso** [comment]
OK, a fix will be included next. See https://github.com/batocera-linux/batocera-emulationstation/pull/1673/commits/2c99fb2eb047a4b24219b3531323a04dd1382985
