### ISSUE TITLE
Feature Request: better games media organization options

### ISSUE THREAD

**Issue by 0chroma** [batocera-linux/batocera-emulationstation#1690]
It would be nice if I could configure emulationstation to search for images in a specific folder, and request it to use a folder structure, rather than them be dumped into a flat `images/` folder. I have a collection of scraped images in a `downloaded_media` folder generated by ES-DE, and would like to reuse it in batocera, but can't seem to find any configuration options for having emulationstation use media in those folders.

example folder structure:
```
downloaded_media
└── doom
    ├── covers
    │   └── doom1.png
    ├── fanart
    │   └── doom1.jpg
    ├── manuals
    │   └── doom1.pdf
    ├── marquees
    │   └── doom1.png
    ├── miximages
    │   └── doom1.png
    ├── physicalmedia
    │   └── doom1.png
    ├── screenshots
    │   └── doom1.png
    └── videos
        └── doom1.mp4

```

**Comment by fabricecaruso** [comment]
We're not going to change the current organization for the internal scrapers.
You still can write you own code to process the gamelist.xml files, and do the organisation you want yourself.
