### ISSUE TITLE
[BUG] Bluetooth doesn't work when using external drive for storage

### ISSUE THREAD

**Issue by geogolem** [batocera-linux/batocera-emulationstation#1692]
### Concerned project

Batocera

### Distribution Version

Batocera 38/39

### Architecture

x86_64

### Issue description

https://www.reddit.com/r/batocera/comments/ptq813/comment/krngpev/?context=3

 if I flash batocera onto a new usb flash stick (or usb HDD etc.) all is well.. bluetooth works well. but I would like to use a separate storage disk for my roms etc. so I go into system settings and choose the drive I want to use for storage. It tells me I need to reboot... when i reboot, bluetooth doesnt work.. the bluetooth dongle doesnt even seem to have power, but when i click scan for devices it doesnt give an error, just scans for ever.

I am experiencing this when I follow the instructions here:

https://wiki.batocera.org/store_games_on_a_second_usb_sata_drive

switching back to internal for the storage gets bluetooth working again. I can recreate this problem repeatedly.

I can provide more info if required.

**Comment by fabricecaruso** [comment]
Not related to EmulationStation at all.
Please repost to batocera-linux repository
