### ISSUE TITLE
add support to batocera.conf.d/*.conf  split configuration

### ISSUE THREAD

**Issue by aderumier** [batocera-linux/batocera-emulationstation#1695]
### Issue description

Hi,
I'l could be great to be able to have splitted batocera.conf in multiple configuration files,

for example, when you distribute roms with a pack, to include the specific games or core tuning in a file like

/userdata/batocera.conf.d/<core.conf>

**Comment by fabricecaruso** [comment]
We don't distribute, and we don't support people that distribute "roms with a pack"

Also fine tuning is generally to the destination hardware : 
- Emulators are not always the same from one machine to one another.
- You won't upscale games to 4k when you are using a weak machine
So moving settings from one machine to one another could be a source of many problems.

It could be interesting to split some configuration into multiple files, but NOT for the reason you invoke.

**Comment by aderumier** [comment]
Hi,
I'm more thinking about game configuration, not system config

for example I have a c64 collection, with some game specific config 
- different core like [game].core=vice_xscpu64 ,  
- or specific display (cropping,...)
- specific shader
...

You can't get these games work (or badly) without theses tuning

**Comment by Darknior** [comment]
I m agree with you. An unique config file in batocera is a pain.
Evry time i must do a batocera fresh instal i lost all my games config 😥

We have already speak about it on discord with the team. The best is you should come on the batocera discord and open a request, a new idea.
To explain the idea to the team and we will speak about it there.
It will be a very long and hard work to do it. It is not an easy task. You will must to motivate them. I will try to help you.

But it is a batocera request, not an emulation station one. Choose the good thread.

Thanks
