### ISSUE TITLE
.ps1 launch problem in scripts/* ES folder

### ISSUE THREAD

**Issue by Nelfe80** [batocera-linux/batocera-emulationstation#1700]
### Concerned project

Retrobat

### Distribution Version

Retrobat V6

### Architecture

Windows 11 pro

### Issue description

Hello,
I adapted my python script in ps1 but it doesn't launch at all. On the command line from the /scripts/game-selected folder it launches fine.
For example:
.\run.ps1 "mame" "C:/RetroBat/roms/mame/cotton2.zip" "Cotton 2: Magical Night Dreams"
But from ES/Retrobat onwards, when I change game, I see a split-second window appear and disappear.
Perhaps the way the scripts are launched has changed?
Thanks

### Logs and data
```

Function Load-Config {
    try {
        $configIniFilePath = "C:\RetroBatV6\plugins\MarqueeManager\config.ini"
        Write-Host "Checking for config file at: $configIniFilePath"

        if (-Not (Test-Path $configIniFilePath)) {
            Write-Error "Fichier de configuration non trouvé at $configIniFilePath."
            exit 1
        }

        $iniContent = Get-Content $configIniFilePath -Raw
        $config = @{}
        $currentSection = ""

        foreach ($line in ($iniContent -split "`n")) {
            $trimmedLine = $line.Trim()
            if ($trimmedLine.StartsWith("[") -and $trimmedLine.EndsWith("]")) {
                $currentSection = $trimmedLine.Substring(1, $trimmedLine.Length - 2)
                $config[$currentSection] = @{}
            } elseif ($trimmedLine -match '^\s*(\S+)\s*=\s*(.*)') {
                $key, $value = $matches[1], $matches[2]
                $config[$currentSection][$key] = $value
            }
        }

        Write-Host "Successfully loaded config from $configIniFilePath"
        return $config
    }
    catch {
        Write-Error "Error loading configuration file: $_"
        exit 1
    }
}


Function Send-Event {
    param ($event, $params, $serverUrl, $currentTime)
    try {
        # Construct the query string with params
        $queryParts = foreach ($key in $params.Keys) {
            "$key=$([System.Uri]::EscapeDataString($params[$key]))"
        }

        # Add timestamp at the end
        $queryParts += "timestamp=$currentTime"
        $query = $queryParts -join "&"

        # Construct the full URI
        $fullUri = "${serverUrl}?event=$event&$query"
        Write-Host "Requesting URI: $fullUri"  # For debugging

        $response = Invoke-WebRequest -Uri $fullUri -UseBasicParsing

        # Uncomment to see the response text
        # Write-Host $response.Content
    }
    catch {
        Write-Host "Erreur lors de l'envoi de l'événement : $_"
    }
}


Function Get-CurrentDirectoryEvent {
    $currentDirEvent = Split-Path (Get-Location) -Leaf
    Write-Host "Current Directory Event: $currentDirEvent"  # For debugging
    return $currentDirEvent
}

$epochStart = [datetime]"1970-01-01T00:00:00Z"
$current_time = (New-TimeSpan -Start $epochStart -End ([datetime]::UtcNow)).TotalSeconds
$config = Load-Config

$configHost = $config['Settings']['host']
$configPort = $config['Settings']['port']

if (-not $configHost) { Write-Host "Host value not found in configuration." }
if (-not $configPort) { Write-Host "Port value not found in configuration." }

$server_url = "http://${configHost}:${configPort}"
Write-Host "Host URL: $server_url"

$event = Get-CurrentDirectoryEvent
Write-Host "Event: $event"  # For debugging

# Use $args directly to get the arguments passed to the script
$params = @{}
for ($i = 0; $i -lt $args.Count; $i++) {
    $params["param$($i + 1)"] = $args[$i]
}

Send-Event -event $event -params $params -serverUrl $server_url -currentTime $current_time

```

**Comment by Nelfe80** [comment]
Ok, I've just been told that you can't directly launch a ps1 on windows, which doesn't allow execution.
This will open a notepad-type reader by default.
You need to bypass it...

**Comment by Nelfe80** [comment]
Aynshe helped me understand. I had associated the .ps1 files with my IDE. Sorry about that. 
What is certain is that you have to go through an intermediate .bat to authorize the execution of a ps1, so you can't run it directly. 
```
@echo off
powershell -ExecutionPolicy Bypass -File "..\run.ps1" %*
```
It's ok. Thanks.

**Comment by Nelfe80** [comment]
Thanks for all the tests. You're absolutely right, .bat are very efficient and I'm going to use them from now on. Unfortunately, you can't attack a URL directly with them, so I'm going to use an intermediate file that I'll listen to.
Thank you for this project, the complexity and power of which I can now appreciate.

**Comment by nadenislamarre** [comment]
"I did not try Python but it would probably be the slowest ( exceeding 1 second )" : for sure, no. very strange assumption.

**Comment by nadenislamarre** [comment]
as a comparison, time to load python on linux is 0.68 seconds.

$ time python3 </dev/null
real	0m0,068s
user	0m0,055s
sys	0m0,014s
$

**Comment by Nelfe80** [comment]
In fact, [Fabricecaruso](https://github.com/fabricecaruso) was talking about a python script compiled for windows with Pyinstaller, and indeed it takes a second or so, a little less to launch. He's got a point there.
It's true that launching python directly from the command line is very fast, but not everyone has python installed on Windows.
