### ISSUE TITLE
Retroachievements broken

### ISSUE THREAD

**Issue by loki666** [batocera-linux/batocera-emulationstation#1707]
### Concerned project

Batocera

### Distribution Version

Batocera V39+

### Architecture

any

### Issue description

enabling retroachievemnts fails

I think the issue is a change in their API which seems to requires a Web API Key for their requests
see https://api-docs.retroachievements.org/getting-started.html

**Comment by fabricecaruso** [comment]
I can't reproduce. It's working perfectly.
Be more specific.

**Comment by loki666** [comment]
well, enabling retroarchievements in the settings, next to your user and password, gives me an error popup

I dug a bit in the code and it's related to that line
https://github.com/batocera-linux/batocera-emulationstation/blob/282024366af2b0a49a4b48f56ac2615d327e8766/es-app/src/RetroAchievements.cpp#L664C110-L664C113

and indeed, if I try to do a curl with my username and password, I'm getting a 403

**Comment by fabricecaruso** [comment]
I have no issue.
As dorequest.php requires the user/pass encoded in the url parameters, maybe it's related to a specific char.

You probably have incompatible chars in your password, no ? 
Try another password with only ascii chars in it, maybe.

**Comment by loki666** [comment]
weird, nor my login, nor my passwd contains any sepcial characters, only alphanumeric

**Comment by loki666** [comment]
to be complete, this issue is in fact happening on a port I'm doing for an Anbernic device
and I didn't include a CHEEVOS_DEV_LOGIN in my keys.txt file as I understood it was used for developping new achievements for a game...

Maybe I was wrong, and I do need one

**Comment by loki666** [comment]
Yup my bad sorry.
