### ISSUE TITLE
I can't change resolution core libretro

### ISSUE THREAD

**Issue by sanjorja** [batocera-linux/batocera-emulationstation#1716]
### Concerned project

Batocera

### Distribution Version

Batocera v37 script 15khz CRT

### Architecture

Linux Batocera

### Issue description

On any system, with any core libretro emulator, when changing the video mode from the batocera menu, it does nothing, it does not apply it. However, if the emulator is standalone, it allows you to modify it. Is it a script error, batocera limitation or is this just like that? I want this because I like to play at non-native resolutions, for example atomiswave 2D fighting games (at 320x240) in some gamecube, ps2, atomiswave or naomi games, but not all systems have standalone emulators. I use batocera v37

**Comment by fabricecaruso** [comment]
not related to emulationstation. please repost in batocera-linux repository
