### ISSUE TITLE
OnClick theme feature?

### ISSUE THREAD

**Issue by marcoriesco** [batocera-linux/batocera-emulationstation#1721]
I've been seeing a new prop in the "onclick" image tag for some time, is it a functional prop? If so, how can we use it, since we have to give a String value.

`{ "onclick", STRING }`

**Comment by fabricecaruso** [comment]
See the list of actions in the following methods : 
https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-app/src/views/SystemView.cpp#L1592
https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-app/src/views/gamelist/ISimpleGameListView.cpp#L623
