### ISSUE TITLE
allow multiple <theme> tags per system

### ISSUE THREAD

**Issue by dhwz** [batocera-linux/batocera-emulationstation#1729]
### Issue description

I'm not 100% sure it's possible, but I have wish so maybe it can be realized.
Can we have something like `<theme>snes-msu1 snesmsu1</theme>` added to ES (similar to what we can already do for `<platform>` tags).
This would make themes more interchangeable between different OS's, e.g. sometimes Batocera uses different names for the systems than EmuELEC or AmberELEC or ArkOS, so themes cannot be used without manual modification of the filenames.
If we can have something like described above the 2nd, 3rd tag could be used as fallback if the 1st tag is not found.

**Comment by fabricecaruso** [comment]
No. And it would be impossible as theme structures are very different from one theme to another about how they manage systems.
