### ISSUE TITLE
Scraping renaming to have a separate option to toggle on and off feature request

### ISSUE THREAD

**Issue by Xorathmion** [batocera-linux/batocera-emulationstation#1730]
### Issue description

As the title suggests.

Don't know if this is the greatest channel for submitting feedback or request a feature, lol. But I've been feeling like this an option in the scraping features within EmulationStation that is sorely missing for the 2 years I've been playing with Batocera that both use EmulationStation as a frontend, instead of using a 3rd party app like Skyscraper or the like.

Just like you can omit descriptions, manuals, fanart, ratings, whether to download a 3D box art vs. a 2D box art... there should be an option to omit renaming, especially at a grand scale of doing your entire list of games, especially if columns contain weird extra spaces, or you have too many romhacks in your collection... and if you have already scraped your collection and you already have renaming perfectly done for most of your titles including your romhacks/mods... I wish there was a way to toggle off renaming to avoid erroneously renaming hundreds of romhacks.

Please add this feature when scraping a way to toggle off renaming, whether you do it for all your platforms, per console/platform scraping or to individual games... the toggle switch to opt-in and opt-out would be indispensable.

Thanks for hearing me out if this gets to the proper parties.

EDIT: I see that ES-DE version of ES has the options we're looking for. Batocera should add this feature to their own fork at some point. It would be sweet.  

https://www.youtube.com/watch?v=js_m_jVnX2s&t=200s 

They just added the Overwrite names toggle options for Scrapper in the 6.2.0 update of Retrobat's emulationstation shortly after asking and proving an example.  Hope this is also added to Batocera as well soon.

![image](https://github.com/batocera-linux/batocera-emulationstation/assets/21286625/6c1a06df-d45c-4958-8f43-f3ca345fe58b)

**Comment by dhwz** [comment]
These 3 overwrite settings do already exist in Batocera EmulationStation.

**Comment by Xorathmion** [comment]
> These 3 overwrite settings do already exist in Batocera EmulationStation.
> 
> See #1725

It is, because on the latest Stable, just checked.

![image](https://github.com/batocera-linux/batocera-emulationstation/assets/21286625/c8f330bb-5589-4f5b-9b1e-c03e4ad37548)

Is it on the beta instead? If it is, is there anything I need to be aware of about the current latest beta before I make the jump?

**Comment by fabricecaruso** [comment]
in the next beta
