### ISSUE TITLE
EmulationStation (on Batocera) no longer runs as smoothly as usual.

### ISSUE THREAD

**Issue by snydar** [batocera-linux/batocera-emulationstation#1787]
### Concerned project

Batocera

### Distribution Version

Batocera V41-dev.2024/09/13

### Architecture

Raspberry Pi 4 B 

### Issue description

Hello everyone,
since the update today to version V41-dev.2024/09/13, the EmulationStation no longer runs as smoothly as usual on Batocera. It jerks a bit when scrolling. I have always set the resolution to 1280x720 60Hz. Can anyone confirm this or has there been a driver update since this version that could cause this?

### Logs and data

[batocera-support-20240914101216.tar.gz](https://github.com/user-attachments/files/17001987/batocera-support-20240914101216.tar.gz)

**Comment by nadenislamarre** [comment]
recently, no driver upgrade,
but screen 2 enabled, that can cause this.
wha'ts the output of batocera-resolution listOutputs  ?

**Comment by snydar** [comment]
Here is the output. There is also only one screen connected.

/userdata/system]# batocera-resolution listOutputs
HDMI-A-1

/userdata/system]# batocera-resolution currentMode
1280x720.60000

**Comment by snydar** [comment]
@PIC16f841 You are right, I have tested the version from 2024/09/13 more. It no longer runs smoothly overall.

**Comment by PIC16f841** [comment]
This is still happening on 18/09/2024 beta

**Comment by snydar** [comment]
I can confirm that. @nadenislamarre Should we perhaps move this thread? Because the problem does not only occur with EmulationStation.

**Comment by xboxones1** [comment]
Confirmed, tried beta 41 from September 22.

**Comment by dmanlfc** [comment]
fixed - https://github.com/batocera-linux/batocera.linux/pull/12544
