### ISSUE TITLE
Scraper Password readable

### ISSUE THREAD

**Issue by BloodyIron** [batocera-linux/batocera-emulationstation#1819]
### Batocera build version

ES v40 2024/08/01 1:28

### Your architecture

x86

### Your Graphic Processor Unit(s) (GPU)

APU

### Issue description

When I set the password for screenscraper and go out of the password section, I can go back into it and read the password as cleartext. This means anyone with access to the system can go read the password that I really don't want to share with them.

Can we please have this aspect of security improved soon?

### Detailed reproduction steps

Already described

### Details of any modifications you have made to Batocera.

None

**Comment by lbrpdx** [comment]
I don't think the screenscraper should be cleared out in the UI. Then, you could argue that the wifi password is in the clear too.
If a Batocera machine is left unattended, it should be put in kiosk/kids mode with no access to the passwords (or any other sensitive setting).

**Comment by n2qz** [comment]
This will in fact clear the input box for wifi passwords, and all other passwords - which currently display as "******" but then show the password in the input dialog.

I think it's best to always do this, for all passwords.  If there's strong disagreement, I can make it only clear the input dialog when "ENABLE SECURITY" is set.

**Comment by BloodyIron** [comment]
> This will in fact clear the input box for wifi passwords, and all other passwords - which currently display as "******" but then show the password in the input dialog.
> 
> I think it's best to always do this, for all passwords. If there's strong disagreement, I can make it only clear the input dialog when "ENFORCE SECURITY" is set.

When you go and edit the field, it should NEVER show the password value in clear-text. This is generally seen as very insecure practice for any password field regardless of where such a function is implemented. It is bad practice for websites, it is bad practice for desktop applications, and any other such thing.

There is no upside to being able to read the text of a password that is already set, whether it's through the GUI (which I am originally speaking to) or reading it via files on disk (as per @nadenislamarre 's point).

Considering in the case I speak to for screenscraper this is the same password I use to login to the website and services (as in this is not an API token or service account that's separate from the main account) this represents a pretty substantial security problem.

I would also like to add that there's a significantly tangible difference between:

1. Someone in your home walking past your batocera system unattended and simply going to read the settings in the GUI which would take seconds, taking a photo of your password, and moving on unnnoticed.
2. Taking the same batocera computer and physically opening it to remove the storage device and reading the files on disk...

#2 would be very very very noticed by the owner of said system, and #1 is much easier to do as a "drive-by" action.

I understand that batocera isn't inherently designed to be a security-focused ecosystem in the first place, but this is bare minimum security for any system to block passwords that are already set from being read.

I am glad this is re-opened, and that we have dialogue going on here. But I really still advocate for passwords being improved in these regards in the batocera ecosystem. And I do agree that the files on disk containing such info have them one-way encrypted (this doesn't necessarily require TPM by the way) as there are already tools in the Linuxy ecosystem to enable this.

**Comment by n2qz** [comment]
> I understand that batocera isn't inherently designed to be a security-focused ecosystem in the first place, but this is bare minimum security for any system to block passwords that are already set from being read.

I agree, which is why I'm correcting most of these exposures.

> And I do agree that the files on disk containing such info have them one-way encrypted (this doesn't necessarily require TPM by the way) as there are already tools in the Linuxy ecosystem to enable this.

What tools are you referring to?

**Comment by BloodyIron** [comment]
> > I understand that batocera isn't inherently designed to be a security-focused ecosystem in the first place, but this is bare minimum security for any system to block passwords that are already set from being read.
> 
> I agree, which is why I'm correcting most of these exposures.
> 
> > And I do agree that the files on disk containing such info have them one-way encrypted (this doesn't necessarily require TPM by the way) as there are already tools in the Linuxy ecosystem to enable this.
> 
> What tools are you referring to?

Well here's one: https://man7.org/linux/man-pages/man3/crypt.3.html

**Comment by BloodyIron** [comment]
Also, thanks for coming up with a workable solution! :)

**Comment by n2qz** [comment]
> > What tools are you referring to?
> 
> Well here's one: https://man7.org/linux/man-pages/man3/crypt.3.html

That's useless in these contexts.  Batocera needs to be able to **use** the stored credentials, so it needs to be able to decrypt them.  A one-way hash is useful only for credential *validation*, not for credential *storage*.

> Also, thanks for coming up with a workable solution! :)

You're welcome!
