### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by TheNando** [batocera-linux/batocera-emulationstation#221]
Has anyone been able to create a Windows build for this? I've had a lot of trouble. Finally got through the CMake process and opened the project in VC++ 2010 Express, and I'm getting tons of syntax errors.

For example
```
batocera\es-core\src\math/Vector3f.h(34): error C2143: syntax error : missing ';' before '}'
```

and that line looks like
```
const Vector3f operator- (const float& _other) const    { return { mX - _other, mY - _other, mZ - _other }; }
```

The problem there is the `{` right after the return is causing a syntax error. I'm not sure what to do next. If anyone has a Windows build they wouldn't mind sharing, I'd be very grateful.

**Comment by fabricecaruso** [comment]
> 
> 
> Has anyone been able to create a Windows build for this? I've had a lot of trouble. Finally got through the CMake process and opened the project in VC++ 2010 Express, and I'm getting tons of syntax errors.
> 
> For example
> 
> ```
> batocera\es-core\src\math/Vector3f.h(34): error C2143: syntax error : missing ';' before '}'
> ```
> 
> and that line looks like
> 
> ```
> const Vector3f operator- (const float& _other) const    { return { mX - _other, mY - _other, mZ - _other }; }
> ```
> 
> The problem there is the `{` right after the return is causing a syntax error. I'm not sure what to do next. If anyone has a Windows build they wouldn't mind sharing, I'd be very grateful.

Of course it builds on Windows... But not on VS 2010.. 
C++ 11 is required so you need at least VS2013.

**Comment by TheNando** [comment]
Ah. I'll get that a try then. You may want to update the docs. I used 2010 based on the first sentence here:
https://github.com/batocera-linux/batocera-emulationstation#building

**Comment by TheNando** [comment]
Well that was downright harrowing, but after 5 hours, I finally got it to build and work. Not bad considering that I've literally never used cmake or compiled a C++ app before. Though, I kinda cheated in that I found this doc and used it as a kind of step-by-step guide on which deps to get and how to build them:

https://gist.github.com/jrassa/0b8f5caa7a9e4d0d146ac988fcc02f5f

**Comment by fabricecaruso** [comment]
You are right, the readme is wrong.

Also, I have an updated yml file for AppVeyor that work with batocera's ES here :
https://gist.github.com/fabricecaruso/47722086a2788eac77d8d98c561f8346

Plus, there is an automated Windows build on my fork here :
https://github.com/fabricecaruso/batocera-emulationstation/releases

**Comment by TheNando** [comment]
Oh man. The hours I could have saved if I knew about your build. At least I learned a lot going through it myself. I do appreciate your help, though!

**Comment by fabricecaruso** [comment]
I have another "fork" which is specially designed for Windows users and it is 100% compatible with batocera's themes. Menus are just simpler ( there is not network / shader / system management options ). I'm thinking about merging the two versions in one in the future ;-)

You can find it here :
https://github.com/fabricecaruso/EmulationStation/releases
