### ISSUE TITLE
All game tags label localization not work in Video UI mode.

### ISSUE THREAD

**Issue by yingw** [batocera-linux/batocera-emulationstation#360]
Swith ES to other language than English, then use some theme with Game Tag display such as "Developer, Last Played, Released Date" and etc (all about 8 labels). In Detail / Simple UI mode, everything works fine until switch to the new "Video Mode", all those label won't be translated into the system language correctly, it show back to English ag. I tested both [Supersweet](https://github.com/RetroHursty69/es-theme-supersweet) and [Fundamental](https://github.com/G-rila/es-theme-fundamental) theme on batocera and EmuElec and got same result.

**Comment by Darknior** [comment]
Thanks to report the bug but it is already fixed in last 5.25 beta.
I think you use the 5.24, all will be fixed for you with next stable release :)
If you found some other issues report them here ;)

**Comment by fabricecaruso** [comment]
I confirm : this is already solved for 5.25
