### ISSUE TITLE
Counting screenshots as screenshots

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#436]
Actually I didn't check it out yet but what is the "unit" for screenshots collection after excluding screenshots out of "all games" ? Is it "game" like it was before? If it does it would be great to turn it into "screenshots". I mean the main screen and info about games in particular systems. In case of screenshots it should be like e.g "5 screenshots".

**Comment by Darknior** [comment]
Screenshot is really an old crappy system in ES :(
I really dream @fabricecaruso take time one day to show screenshots like game covers, and when we open it, show it with a real image viewer that let us to see it in full screen, and why not Zoom and move on it. It's the feature i stand too for reading games manuals in ES for each games :)

The problem with the word "GAMES AVAILABLE" is that its a string used for all the systems, the same string translated too in each langage ...
It's not possible to change it only for this system.

**Comment by mistepien** [comment]
Ok, thanks for your answer. Let leave this issue open. The issue is not of critical importance but maybe someone will manage to do it.

**Comment by fabricecaruso** [comment]
Ok. I have a commit for that. 
Issue closed.
