### ISSUE TITLE
ES menu for global.shaders

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#440]
Besides shadeset (i.e. zfast) it would be great to have a menu to deal with global.shaders. Maybe in one list?

**Comment by Darknior** [comment]
You can already choose your shader, you have a list with cool names.
You will never have a full shader list in Batocera, it 's like that to make it easy to use for every one.
But you are free to config your hown personal shader in batocera.conf.

**Comment by mistepien** [comment]
Ok thanks, maybe you are right
