### ISSUE TITLE
Flac file a ES background music

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#445]
ES is already linked with libflac. It would be great to have an option to use flac files as background files. I tried
`if (extension == ".mp3" || extension == ".ogg" || extension == ".flac" )`
in es-core/src/AudioManager.cpp (line 159) but it does not work.

**Comment by lbrpdx** [comment]
It actually does... I am writing a PR for that. FLAC decoding is done through SDL2 Mixer. What file didn't work for you @mistepien ?
