### ISSUE TITLE
Wrong controller icon width

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#453]
After last commit to ES I got strange controller icon in all themes. It's "compressed". It is related not only do Carbon theme but also other themes.
![IMG_5700](https://user-images.githubusercontent.com/9516457/79637648-7c09c200-8181-11ea-876b-be3f498f4022.jpg)

**Comment by mistepien** [comment]
I think that this upto8 commit. There is the same space for controller icons as before but 8, not 5, controller icons must fit.

**Comment by fabricecaruso** [comment]
fixed
