### ISSUE TITLE
System switching in gridmode view in Carbon Theme does not work

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#454]
L/R system switching in Carbon Theme does not work. I have gamepad with L1,L2,R1 and R2. And they are fully functional. But not for system switching in gridmode view.

**Comment by mistepien** [comment]
I got it. L1/R1 works on main screen. L2/R2 works when we are in system screen with gridmode view. L2/R2 does not work in main screen, L1/R1 does not work in system screen with gridmode view.

**Comment by fabricecaruso** [comment]
Yes & no.

L1/R1 works in system view to move -/+ 10 systems. L2/R2 does not work in system view.
L1/R1 works in gamelist view to move -/+ 25 games. L2/R2 works in gamelist views.

L1/R1 are designed to move many "items" (system or game depending the current view).
L2/R2 to move though systems.

So : L2/R2 is missing in system view. I'll add it in the next PR.
