### ISSUE TITLE
ES menu to set ap extentions for particular systems/extentions config file in every system rom folder

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#456]
I know that this is additional complexity but current situation is quite frustrating for new users.

Currently is you e.g. add amigacd32 Worms games which is my case composed of cue, iso and wav files, I see it double on the gamelist because both cue and iso are considered to be games. In such situation I have two options. 1. to change extension of is iso file and edit cue file, 2. to copy es_systems.cfg to /userdata and edit that file and remove .iso/.ISO extensions for system  amigacd32 -- but I can do that only via ssh, /usr/share/emulationstation/es_systems.cfg is not available via smb share.

What I suggest is making ES menu  - checklist with extensions for every system. In default all extensions would turn on and user would have opportunity to turn off some of them. In above example with amigacd32 and my copy of Worms I would simply turn off iso/ISO extension.

The other option is to set it via e.g. extentions.txt in every system rom folder. In such case user would be able to edit such system via samba share.

**Comment by fabricecaruso** [comment]
Done in my current PR
