### ISSUE TITLE
Error while finishing compilation (linking process)

### ISSUE THREAD

**Issue by bitstuffing** [batocera-linux/batocera-emulationstation#468]
When you tries to compile it in raspberry pi 4 with raspbian buster it doesn't work (fail in linking process).

Linking CXX executable ../emulationstation
/usr/bin/ld: /opt/vc/lib/libvchiq_arm.so: undefined reference to symbol 'vcos_generic_mem_free'
/usr/bin/ld: //opt/vc/lib/libvcos.so: error al añadir símbolos: DSO faltante desde línea de orden
collect2: error: ld returned 1 exit status
make[2]: *** [es-app/CMakeFiles/emulationstation.dir/build.make:1092: emulationstation] Error 1
make[1]: *** [CMakeFiles/Makefile2:358: es-app/CMakeFiles/emulationstation.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

But retropie-emulationstation compiles and works fine.

Probably this error could happen by "Makefile ld" bad configuration?

Also I compile in ArchLinux and compile and works fine, this error just appear in RP4 with 4.19.x and  5.4.x kernels

![image](https://user-images.githubusercontent.com/15215960/80862835-58ae3f00-8c78-11ea-93cc-fd334a5a3929.png)

Greetings!

**Comment by nadenislamarre** [comment]
it just lacks the rpi libs at edition linking.
just use cmake . -DRPI or something like it and it will work.

**Comment by harddevelop** [comment]
> it just lacks the rpi libs at edition linking.
> just use cmake . -DRPI or something like it and it will work.

Thanks, I'm agree with you but... doesn't work :'(.

Could you please add this libraries to makefile? or... I can fork and do it if you specify exactly the library you're using.

Greetings!

**Comment by harddevelop** [comment]
Ok, I've found what parameter are you refering: 
-DRPI4=1
with it in cmake process just linking continue and finish
but now there is some error that has been happening in Retropie emulationstation just before a few weeks:
![image](https://user-images.githubusercontent.com/15215960/81822971-11576680-9534-11ea-8629-83d0337cc2f1.png)
After the last release in 1-2 may this error dissapears.

Have you take into account his fixes?

Greetings

**Comment by aldoborrero** [comment]
With my Raspberry Pi3 I'm having the same issues with linking and the `cmake . -DRPI4=1` flag doesn't work either.

Any updates?

**Comment by fabricecaruso** [comment]
Probably obsolete
