### ISSUE TITLE
Problem when create grid.xml

### ISSUE THREAD

**Issue by Moriggy** [batocera-linux/batocera-emulationstation#474]
Hi!

When I create an xml file for each type of gamelist separately for the theme.xml principal, detailed, basic mode works fine but grid mode does not recognize programming well. It has to be programmed in the main xml for a correct display of that gamelist mode. Is it a possible ES error?

Each xml created for each type of gamelist is included in the main theme.xml:
< include >./gamelistview/detailed.xml</ include >
< include >./gamelistview/basic.xml</ include >
< include >./gamelistview/grid.xml</ include >

Is there any idea or solution of what may be the problem?

**Comment by fabricecaruso** [comment]
I need to see the full theme.
Provided information is not enough.

**Comment by Moriggy** [comment]
> I need to see the full theme.
> Provided information is not enough.

Of course. Here is the link to the theme that I just uploaded to my github repository so you can see what I was saying.

If the content of the grid.xml file is entered into the theme.xml, the gamelist looks perfect.

https://github.com/Moriggy/es-theme-EmulOnFire

**Comment by fabricecaruso** [comment]
What should I see in your theme ? 
Looks like It's working well in the last 5.26 beta & what I see is what is described in your grid.xml file.

Note : 5.26 had fixes concerning customViews. In 5.25 custom views & its base class must be in the main theme.xml file

**Comment by Moriggy** [comment]
Great!!! I try to do it in 5.25 version.

Thanks for your time & help!!! Nice job with ES!!!
