### ISSUE TITLE
Switch to disable screenshots collection

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#475]
It would be great to have an option to disable screenshots collection without getting involved in hacking es_systems.cfg.

**Comment by Darknior** [comment]
You already can do it in games configuration menu, you can hide the system.

**Comment by fabricecaruso** [comment]
Absolutely....

**Comment by fedekrum** [comment]
I can't find the option.... where is it?

**Comment by fabricecaruso** [comment]
game collection settings / systems displayed /
