### ISSUE TITLE
System is hanged after making change in system file-extentions

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#478]
I turn off "img" file  in pcenginecd system, than whole ES is going to reload but it is stale. There is splash image (rpi3) and nothing happens. To get system back I had to power off the machine.

**Comment by fabricecaruso** [comment]
I can't reproduce. Maybe related to another setting.
You need to provide more information.
Is it systematic or just appened once ? 
Does it happen also on other systems ?
Does it happen only with .img extension ?
Plus, I'd need your whole config to test : gamelist.xml for this system - es_settings.cfg file - batocera.conf file.

**Comment by fabricecaruso** [comment]
Problem solved for the next release.
