### ISSUE TITLE
carousel transition with slide mode in detailed system view is not smoothless between first and last system

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#483]
Carousel transition and SLIDE transition works fine when I'm in main screen. Notwithstanding is it es-videogame or es-carbon transition is fine and transition between last and first system is the same like between evey other pair.

BUT. When I'm in detailed system view and switch to other system (quick switch) there is a problem. Transition between last and first system (in my case between Atari ST and Favorites) is not so smoothless  and differs to in-system transition between other pair. It looks like switching from last to first means fast switching through all system between.

**Comment by fabricecaruso** [comment]
Not fixable without a big rewrite... And not very important...

**Comment by mistepien** [comment]
Please add it to your TODO list. ES in Batocera is so perfect that this small glitch is like a thorn.
