### ISSUE TITLE
Starting game with slide transition turn-on

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#484]
It would be great to have an option to turn off this fancy effect when slide mode is turn-on. I mean this zooming in video picture just before switching to retroarch. I like slide effect very much (esp. since when I found vram switch) but this zooming effect is something I would like to turn off.

**Comment by fabricecaruso** [comment]
On my other fork, I had TRANSITION splitted in two separate options, including a GAME LAUNCH TRANSITION. That's something I can port to batocera.
I keep this Issue open & will add this for 5.27

**Comment by mistepien** [comment]
Great!
