### ISSUE TITLE
System view order no longer following the order of es_systems.cfg

### ISSUE THREAD

**Issue by ShaneShirey** [batocera-linux/batocera-emulationstation#508]
Previously, the order of systems in system view would follow the order of es_systems.cfg. That broke sometime this week with no option within EmulationStation to fix this order.

Not sure if this change was intentional or not, but wanted to bring attention to it.

**Comment by fabricecaruso** [comment]
That's intentionnal, and if you search a bit you'll quickly find where the option is....

**Comment by ShaneShirey** [comment]
What if you didn't want it sorted alphabetically though? Do you intend to add a sort option that sorts by the order in es_systems.cfg?

**Comment by ShaneShirey** [comment]
Also, doesn't this option seem weird to be in Game Collection Settings when the option to select which systems display is the UI settings?
