### ISSUE TITLE
Wrong text for left joystick in gamepad configuration

### ISSUE THREAD

**Issue by smandon** [batocera-linux/batocera-emulationstation#517]
When configuring a gamepad, the text for configuration of the left analog down and right is wrong.
![OGA](https://user-images.githubusercontent.com/5166873/84720451-5a109e00-af7e-11ea-81bb-50baaebe1a91.jpg)
As you can see, the last two directions should be "left analog down" and "left analog right". It is likely the same with translations in other languages (confirmed with French at least).
I've seen this problem on raspberry pi3 and odroid go advance builds.

**Comment by lbrpdx** [comment]
No, it should be read as “left analog” up/left and “right analog” up/left. 
When you have a controller with 2 analog sticks, like PS3, PS4 or Xbox360 controllers, this is meant to configure first the left analog stick, then the right analog stick. And you only need to push the stick in the up and left directions, down and right will he found automatically. 
On your Odroid Go Advance, you should configure only the first two, and skip right analog up and left, as there is only a left analog stick, no right analog.

**Comment by smandon** [comment]
Thank you, I understand now.

But it's really not intuitive at all and not documented.
Maybe a more explicit text would be useful? I'm sure I'm not the first one puzzled by this, as I've never seen any emulator or mapping software behaving like this. Do other platforms using ES have the same issue? I don't remember this from retropie or recalbox.
It may seem logical from the developer's point of view that the other directions can be infered, but definitely not from the end user's.

Another issue related to this is that it doesn't allow mapping them to buttons, for example if you want to use a keyboard or arcade stick.
Wouldn't it be possible to have the user do an up/down or left/right motion and detect if it corresponds to an axis or two buttons?

**Comment by fabricecaruso** [comment]
There are icons to show required directions... 
And the text  "RIGHT ANALOG LEFT" is quite explicit...
