### ISSUE TITLE
Make it possible to change the confirmation button.

### ISSUE THREAD

**Issue by ainmosni** [batocera-linux/batocera-emulationstation#523]
In ES, B (down) is to confirm while A (up) is to cancel. This is different than the default in kodi, or retropie, or anywhere else. Could you add an option to reverse this?

**Comment by fabricecaruso** [comment]
Why don't you just reconfigure your controller to invert these buttons ?

**Comment by ainmosni** [comment]
@fabricecaruso Because I'd rather keep the labels correct to, I'm building one for someone else and having the b button in the interface not match the button label would be confusing. Also, AFAIK, that button binding propagates to emulators as well, which would not be ideal.

**Comment by 25minutes** [comment]
Agree with @ainmosni . It's so confusing...
Is it hard-coded, or is it defined in some config file? If it's possible to change the config file to swap these 2 button, at least there's a workaround. Any hints?
I've been searching for a solution for a while, but unfortunately haven't found one.

**Comment by fabricecaruso** [comment]
Done. See this PR https://github.com/batocera-linux/batocera-emulationstation/pull/577
