### ISSUE TITLE
Add "CRTSwitchRes" to "Per system advanced configuration"

### ISSUE THREAD

**Issue by joerg-knitter** [batocera-linux/batocera-emulationstation#524]
When using a VGA-2-RGB/Component cable to connect a CRT TV or monitor, enabling CRTSwitchRes is said to be the preferred video output solution because it sets the CRT to the internal resolution of the used core. 
Some cores offer the option to add a TV overscan to this internal output resolution (like Mednafen Beetle PSX, Genesis Plus GX and Stella), but most currently don´t. This results in the image to be streched too much horizontally on a real 4:3 CRT TV due to the missing overscan borders, and on some games and console emulations, the image is cut on the left and the right (with having not the "original" display aspect ratio at the same time).

A good example can be found at https://wiki.nesdev.com/w/index.php/Overscan: The real horizontal resolution of the original NES (NTSC) with overscan is 280px while only 256px are used (with 24px of borders added to the left and right).
None of the cores I tested allowed to add this overscan area of 24px or set it themselves with an appropriate option, and thus CRTSwitchRes just switched to the 256px on all cores, not 280px as it should be. This results in the image to be streched 24px wider when output to the CRT TV.

Since some cores allow adding those overscan borders (like mentioned above) while others don´t, I would prefer a per system advance configuration if I want to use CRTSwitchRes or my self-defined resolution instead (e.g. enabling it for PSX, but disabling it for NES where I would "manually" set it to a custom resolution of 280px x 240px for now).

**Comment by fabricecaruso** [comment]
This is not related to emulationstation, but to batocera.linux.
Can you delete this issue & create a new one in the batocera.linux repository.

**Comment by joerg-knitter** [comment]
Thanks for your feedback. I asked for an additional menu entry in the "Per system advanced configuration" in ES because I that it was harcoded.
