### ISSUE TITLE
splash screen shown once just before game

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#585]
If there is a splash image (eg. png file) set in /boot/splash then it will be shown before launch of the core - but only once.

When other game or even the same one is launched again then no splash is shown. System is RPI3, maybe splash goes to some framebuffer and running core clears that and this is why next time this framebuffer is empty?

**Comment by fabricecaruso** [comment]
Not related to ES : ES "hides" when launching a game. 
Please close Issue & create a new one in batocera.linux repository.

**Comment by mistepien** [comment]
ok
