### ISSUE TITLE
Gamecube & Wii: cannot use "Stretch to Window" for Aspect Ratio

### ISSUE THREAD

**Issue by 25minutes** [batocera-linux/batocera-emulationstation#586]
The emulator Dolphin itself supports "Stretch to Window" as the aspect ratio. However, this setting is always overwritten by Batocera when a ngc/wii game is launched. Via EmulationStation's Games Settings menu, it's possible to force 16/9 or force 4/3 , but it just cannot choose "Stretch to Window".

Can you add "Stretch to Window" option for Gamecube/Wii (perhaps via Per System Advanced Configuration)? Alternatively, can you add a parameter in batocera.conf for users to specify the aspect ratio for Gamecube/Wii?

**Comment by fabricecaruso** [comment]
Is not in ES side, but in batocera.linux side.
Can you close this Issue & create it in batocera.linux repository ?

**Comment by 25minutes** [comment]
OK.
