### ISSUE TITLE
Language set to Chinese，F1   system will  unrecognizable characters

### ISSUE THREAD

**Issue by easleyclaymore** [batocera-linux/batocera-emulationstation#593]
![38D7B25B153C7FEF5A233B271D3ACD98](https://user-images.githubusercontent.com/40049427/93894798-b7588000-fd21-11ea-981f-9fa99bc7aa31.jpg)

anybody knows how to fix it?

**Comment by fabricecaruso** [comment]
It's not related to EmulationStation. 
Please close the issue & create a new one in batocera.linux repository.
