### ISSUE TITLE
Incorrect number of games

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#611]
If I disable some extension in particular system (eg. IMG in PCEngine CDROM) then overall number of games displayed in main screen includes these disabled, hidden positions. So eg. overall number is 25 but when you enter into PCEngine CDROM you see only 13 games (in my case).

In other words pcenginecd.HiddenExt has no impact upon counting of systems eg. in pcenginecd, but it is the same in every other system. 
I use beta for x86_64 v29 coming from 14.10.2020 but I can confirm that also in stable 5.27.2.

**Comment by mistepien** [comment]
The dirty workaround is editing of file /usr/share/emulationstation/es_systems.cfg. If you delete unwanted file extensions from that file than the problem is solved.

**Comment by azvarel** [comment]
from version 5.27 it is already possible to select which extensions you want to appear

![image](https://user-images.githubusercontent.com/129056/97082175-29044200-15de-11eb-9bb8-b1c3c4b3d8a7.png)

**Comment by mistepien** [comment]
Yes, I cannot agree with even more. But as I've written: if you disable files with that ES setting you mentioned about than such disabled-hidden files are still counted in overall number of games in particular system. Thus on the list you see just one game but in the main screen you can see that there are eg. 100 games. That's the problem.

Editing  /usr/share/emulationstation/es_systems.cfg solves problem in counting unwanted files in overall number of games per particular systems.

**Comment by fabricecaruso** [comment]
Fixed in my last commit
