### ISSUE TITLE
Snes9x "REDUCE SLOWDOWN" does not work

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#655]
There is a new option in SNES with Snes9x system settings "REDUCE SLOWDOWN". That is, IMHO linked to Retroach Snes9x specific option "Reduce Slowdown (Hack, Unsafe)". But changing option in ES has no impact upon Retroarch.

![IMG_6264](https://user-images.githubusercontent.com/9516457/98446661-55ac7380-211f-11eb-8e6d-d820fb6d30a9.jpg)

![IMG_6262](https://user-images.githubusercontent.com/9516457/98446664-5b09be00-211f-11eb-87b2-5019c2d5ac70.jpg)

**Comment by mistepien** [comment]
I found that this non-functional feature is added in batocera.inux repository, not in ES.

**Comment by fabricecaruso** [comment]
@Darknior this one is for you... lol

**Comment by Darknior** [comment]
Yes it's ok i've miss 2 lines in configuen now we will fix it.
