### ISSUE TITLE
Clock format isn't configurable

### ISSUE THREAD

**Issue by Rican7** [batocera-linux/batocera-emulationstation#691]
Currently, unless I'm mistaken, it seems that the clock can only show in "24 hour notation", or rather `%H:%M`.

I was wondering if the clock format could be configured to show a different format, such as the "12-hour notation" of `%I:%M`, or even a "12-hour expanded notation" with a designator like AM/PM, such as `%I:%M %p`.

One could even allow theming of the clock by using the `%I:%M %P` format for the "12-hour expanded notation" and then allowing a `forceUppercase` theme rule to be applied to the clock view. 😃

**Comment by lbrpdx** [comment]
This is addressed with https://github.com/batocera-linux/batocera-emulationstation/pull/804 as well as timezone selection from ES, because folks who care about 12-hour mode are very often the same who care about timezones ;) 🇺🇸
