### ISSUE TITLE
hidden extensions + screencraper

### ISSUE THREAD

**Issue by mistepien** [batocera-linux/batocera-emulationstation#697]
There is eg. pc engine cd system. There are 20 img and cue files what makes 10 games but 20 positions is a system view. After deselection of img as visible extension there are 10 games. This is just fine. 10 games are counted as overall number of games in that system. Everything works.

BUT if you launch screenscraper for that system you will see that screenscraper is downloading stuff for 20 games.
Thus screenscraper does not take into account that some extensions are hidden.

**Comment by fabricecaruso** [comment]
It's normal, extension filtering is just a display filter.
