### ISSUE TITLE
<sortname> field in game metadata

### ISSUE THREAD

**Issue by duiz** [batocera-linux/batocera-emulationstation#713]
An option I been missing in this version of ES that has been implemented in earlier builds is a sortname field in metadata. This allows games to be sorted by the sortname and makes sorting and organizing a bit more customizable while keeping the proper naming conventions for some games.

**Comment by Darknior** [comment]
For my part i prefer an option like in KODI to sort games name without "Le La Les The ...." 
It's perfect to make easier to found games, a new tag will complicate things for me ...
An other option i've already suggested , take from KODI too, is the SAGA, to group games of same familly but with different names with translated games name like Mystical Ninja and Gambare Doraemon that are games of same familly but different names.

**Comment by fabricecaruso** [comment]
I don't agree : Sorting must be done using what's displayed on the screen & not on a field that is not visible.
