### ISSUE TITLE
Batocera should default to 60 Hz on bootup

### ISSUE THREAD

**Issue by STPKITT** [batocera-linux/batocera-emulationstation#716]
Hello,
I'm constantly running into the issue that Batocera at least on certain displays defaults to 50 Hz which leads to all emulators I tried also being limited to 50 fps, which is a pretty fatal issue.
I guess Batocera is reading out the EDID of displays on boot and that may be beneficial to be able to switch output resolution and refresh rate on the fly during use of the system but it should still default to 60 Hz display output when the display supports it.

**Comment by fabricecaruso** [comment]
too old & not related to ES

**Comment by STPKITT** [comment]
If the statement too old is true I'll find out in a few minutes since I'm about to install the current version.
What do you meant that it's not related to ES? What would that behaviour be related to instead?

**Comment by STPKITT** [comment]
So I tried it now and I can report that the current version of Batocera defaults to 60 Hz at least on my TV which is still the same TV which I had used when I opened this issue. So this issue can stay closed. Thanks!
