### ISSUE TITLE
SaveState Manager integration: a little improvement

### ISSUE THREAD

**Issue by XargonWan** [batocera-linux/batocera-emulationstation#768]
Actually to reach the savestate manager is needed to go into the game options, and launch it from here.
I am suggesting a similar approach from what many mini consoles are doing: select the game and then you can load the last auto save or whatever savestate you wish.

In detail my idea is to create a new menu option in the **settings** screen like I show you below.

**AUTO SAVE /LOAD:**

**- PROMPT:** When the user chooses the game and presses the button to start it it will prompt the SaveState Manager. This enables the autosave option in RA.
**- ON:** Sets the autoload and save function on in RA, so whenever the game is launched the user can start where he left off.
**- OFF:** no save manager prompt, no autosave, no autoload.

**PROMPT** can be by by default so everyone can enjoy the new save manager feature.

What do you think about it?

**Comment by fabricecaruso** [comment]
Savestate manager is accessible with "L3" button ( analog left button ).
AutoLoad/Save option already exists since a while & is still working.
Isn't that enough ?

**Comment by XargonWan** [comment]
> Savestate manager is accessible with "L3" button ( analog left button ).
> AutoLoad/Save option already exists since a while & is still working.
> Isn't that enough ?

Thankyou for your quick reply: I didn't know about L3, however not every console got pushable analog controls, so I still think that this feature would be nice.

**Comment by Darknior** [comment]
> Savestate manager is accessible with "L3" button ( analog left button ).
> AutoLoad/Save option already exists since a while & is still working.
> Isn't that enough ?

i discover it too :)
L3 not existing on OGA OGS lol
But all the key are already used.
For my part the actual system is fine to use.

Maybe showing the savestate menu  automatically when launching a game like on mini console is more intuitive ?
Maybe let the user choosing this feature with an option in ES

**Comment by fabricecaruso** [comment]
"Maybe showing the savestate menu automatically when launching a game like on mini console is more intuitive ?"
Maybe as an option... We should do a poll ;-)

**Comment by XargonWan** [comment]
> "Maybe showing the savestate menu automatically when launching a game like on mini console is more intuitive ?"
> Maybe as an option... We should do a poll ;-)
> XargonWan initial idea is interesting but in that case we'd have to rename the option to something more comprehensible I think

Thankyou please let me know when you do this pool :)

**Comment by QuaiGoner** [comment]
That would be a great addition

**Comment by fabricecaruso** [comment]
PR done...
