### ISSUE TITLE
Button to add to favorites, i miss you

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#792]
Hi team!
I love this new version 30, but I miss the button to add/remove favorites, assigned in previous versions to the button (Y). Now my question: Would it be possible to assign the hotkey button as a quick button to add or remove from favorites as it did before (Y)? I think it is a very intuitive button for this task. 
What do you think about this?

**Comment by shantigilbert** [comment]
https://github.com/EmuELEC/emuelec-emulationstation/pull/21 maybe this could be implemented, use longpress x to add to favorite and short press x for random game

**Comment by lbrpdx** [comment]
This has now been added with a long press on https://github.com/batocera-linux/batocera-emulationstation/pull/800 - I guess this ticket can be closed.
