### ISSUE TITLE
Sleep mode for RG351M broken

### ISSUE THREAD

**Issue by DFelten** [batocera-linux/batocera-emulationstation#799]
I really like Batocera and already use it on my Raspberry Pi. It also works very well on the RG351M, but it lacks sleep mode for a handheld. Especially on a handheld, you play for a short time and switch it to sleep mode. Unfortunately, it currently shuts down when the power button is pressed. That's the only reason why I'm currently still using another system (351ELEC).

Is such a sleep mode planned?

**Comment by nadenislamarre** [comment]
in fact it is already in the version 30.
it works on odroid go super. ive done a quick test on other similar boards, it wasn't working correctly. to be analyzed.
however, i don't really get the interest. i find it fun, but not really usefull.
the problem of the sleep mode is that you've to think to shutdown properly your board if you don't play with it before going to bed, because, it make the battery largely longer, but not eternal. personnally, i prefer to wait 20 seconds each time i want to play. when i play, it is not for just 1 min.

**Comment by nadenislamarre** [comment]
there is a wiki about it : https://wiki.batocera.org/customize_hotkeys

**Comment by DFelten** [comment]
> in fact it is already in the version 30.
> it works on odroid go super. ive done a quick test on other similar boards, it wasn't working correctly. to be analyzed.
> however, i don't really get the interest. i find it fun, but not really usefull.
> the problem of the sleep mode is that you've to think to shutdown properly your board if you don't play with it before going to bed, because, it make the battery largely longer, but not eternal. personnally, i prefer to wait 20 seconds each time i want to play. when i play, it is not for just 1 min.

For example on easyRPG there are no savestates. It's not possible to just play 10 minutes and quick save the game. Instead, the console and screen must remain on until a savepoint is found.

Thanks, I will test it on version 30!

**Comment by DFelten** [comment]
The suspend mode works, but unfortunatly the device is disconnected from port 1 after quit the sleep mode. So the buttons no longer work and I have to restart the device.

<img src="https://user-images.githubusercontent.com/1169185/109965398-34cfe580-7cef-11eb-9dfa-74192f3fddb0.jpg" width="250">

My current multimedia_keys.conf
```
KEY_VOLUMEUP	1		/usr/bin/amixer set Master 5%+
KEY_VOLUMEUP	2		/usr/bin/amixer set Master 5%+
KEY_VOLUMEDOWN	1		/usr/bin/amixer set Master 5%-
KEY_VOLUMEDOWN	2		/usr/bin/amixer set Master 5%-
KEY_MUTE        1               /usr/bin/amixer sset Master toggle
# KEY_POWER       1               /sbin/shutdown -h now
KEY_POWER       1               /usr/sbin/pm-suspend
# display some information on X displays
KEY_F2          1               /usr/bin/batocera-info --short | HOME=/userdata/system XAUTHORITY=/var/lib/.Xauthority DISPLAY=:0.0 osd_cat -f -*-*-bold-*-*-*-38-120-*-*-*-*-*-* -cred -s 3 -d 4
SW_HEADPHONE_INSERT 0           batocera-audio set headphone
SW_HEADPHONE_INSERT 1           batocera-audio set speakers

```

**Comment by fabricecaruso** [comment]
too old & not related to ES
