### ISSUE TITLE
Presets for Sorting 

### ISSUE THREAD

**Issue by soaresden** [batocera-linux/batocera-emulationstation#806]
Hi !

I think it would be so goood to have presets to sort our library !
Specially in Collections

I would love to do some collections like a Tomb Raider's collection

```
1996 - PSX - Tomb Raider 1
1997 - PSX - Tomb Raider 2 
1998 - GBC - Tomb Raider
1999 - PSX - Tomb Raider 3 
```

(these infos above are fakes, just exemples)

Also there is some Games that have bad names and are so strange to sort like Ace Combat

Air Combat
Ace Combat 2 
Ace Combat 3 

etc

Maybe there is other presets that will makes sens

Please right your suggestions :)

ReleaseYear - System - Title _1996 - PSX - Tomb Raider 1_
System - Title _PSX - Tomb Raider 1_
...etc

**Comment by fabricecaruso** [comment]
Done
