### ISSUE TITLE
reordering snapshots list more friendly

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#809]
Hello team.
To avoid confusion with other manual snapshots, would it be possible to identify the autosave slot in some way? with an icon or label type "automatic" for example. When you have many snapshots it is not possible to recognize which is the automatic slot in the AUTO SAVE/LOAD  list.

In addition to the marking, I would always put in the same position on the list, right next to the "START NEW GAME" option and this option always first, now is placed at the end of the snapshots list . 

New ordering proposal:

[ **START NEW GAME** ] -+-+-+-+- [ **AUTOSAVE SLOT** ] -+-+-+-+- [ **REST OF MANUAL SNAPSHOTS** ]
 _always in first option_________always second, empty or not__________________order by date desc

Waht do you think, guys? IMO is a more cleaning and intuitive list.

Thanks for the great work!

**Comment by fabricecaruso** [comment]
The autosave is identifiable ! It's named "AUTO SAVE"....

**Comment by fabricecaruso** [comment]
I agree about the [ START NEW GAME ] option... But it's discutable with the autosave, expecially if it's empty.... No ?

**Comment by pajarorrojo** [comment]
Sorry, my fault. It is true that auto save is identifiable. I had not seen it because in my custom theme it is not visible, i can see in the default carbon theme ... my apologies again. I have to work on my theme to see why it happens, but seems obviously that the font size is to high. 

![IMG_20210325_190902691](https://user-images.githubusercontent.com/73712202/112523458-11a0cf00-8d9f-11eb-8c50-3beeefc9b55e.jpg)
![IMG_20210325_190939788](https://user-images.githubusercontent.com/73712202/112523482-1796b000-8d9f-11eb-98d9-3fee566e5e94.jpg)

Putting the START GAME option always first is a good change. As you can see in the screenshots, if I want to start a new game it is annoying to always go to the end of the list.

**Comment by pajarorrojo** [comment]
The auto save option is debatable but in my humble opinion I think it would be friendly if it was always in the second option, like when it is empty.

**Comment by fabricecaruso** [comment]
<menuTextSmall name="menutextsmall"> <fontSize> is too big....

**Comment by pajarorrojo** [comment]
Thanks! im working on it!
