### ISSUE TITLE
ES Theming: Screen view elements, where i place you?

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#820]
Hello team,
I think it would be very positive for theming programming that the elements of the "screen" view, such as clock and controllers could be activate or deactivate in other views such as the system, games list, or even in the menu view.

If I'm not mistaken, right now the "screen" items are shown in all the views except in splash view, which can be annoying for design themes, it's difficult to place these elements without disturbing one view or another, then the current (bad) solution is to place them in a corner at a reduced size so that they disturb as little as possible. I don't know if this can be done or if it is very complex, they are just ideas, but I think they are very useful and powerful elements to show information very quickly in the right place, IMO. What do you think?

**Comment by Snapouille** [comment]
@fabricecaruso Have you managed to do something conclusive on this request?

**Comment by fabricecaruso** [comment]
No. And I don't think I'll ever change that. 
Screen is Screen and is meant to be a permanent OSD.
