### ISSUE TITLE
Blank screensaver should turn off screen

### ISSUE THREAD

**Issue by svera** [batocera-linux/batocera-emulationstation#827]
The blank screensaver in EmulationStation just shows a black screen, but it is not really turning the screen off to save energy. This is critical to have an always-on system with RPi or any other desktop system, as the screen is the main source of power consumption.

**Comment by fabricecaruso** [comment]
It's not EmulationStation responsability to turn the screen off, but it's the system responsability.
Plus, now you have a "suspend" option .
I'm closing this issue.
