### ISSUE TITLE
Scraper: Add NONE to IMAGE SOURCE option

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#828]
Why always have to download the image source? is there any reason? If I only need the manual or the video to complete my gamelist or game, right now there is no way to download it without overwriting the thumbnail. It would be very positive and a more complete and powerful Scraper tool with a pure “cherry picker” function simply adding a “NONE” option to image. This is possible?

**Comment by fabricecaruso** [comment]
scrapping "image" don't overwride the thumbnail !?!

**Comment by pajarorrojo** [comment]
Sorry when I say "thumbnail" I mean the main image showed either in format, mix v1, mix v2, screenshot etc... In any case, what I propose here is clear. Simply if it would be possible to scrape without being forced to choose an image type without always overwriting the main image (ok not thumbnail). I have created my own mixes, if I need to scrape only videos or manuals right now it is not possible without overwrite mi own mixes.

**Comment by fabricecaruso** [comment]
You are talking about the "manual per game scrap" ?

**Comment by pajarorrojo** [comment]
I'm talking about the general scraper, about the options screen before starting the scraping, as in the attached image. And more specifically from the "image source" option as highlighted in the image.

![IMG_20210417_213813485](https://user-images.githubusercontent.com/73712202/115125148-9b227600-9fc6-11eb-9c02-b23b17d1218f.jpg)

**Comment by pajarorrojo** [comment]
> "manual per game scrap"

Hmm, where is the "manual per game scrap"? in the game options only appears the option "SCRAPE" for me. When I choose to scrape, it doesn't give me any options and it goes directly to scrape all the data. 

![IMG_20210417_214136734](https://user-images.githubusercontent.com/73712202/115126138-43d3d400-9fcd-11eb-9396-b4f2ba86d617.jpg)
![IMG_20210417_214153958](https://user-images.githubusercontent.com/73712202/115126140-4e8e6900-9fcd-11eb-8374-8087a5535f56.jpg)

This is another thread but I think it would be good to also show the options screen before scraping a single game, as in global scraping, choosing which data or media to download and which to discard before starting to scrape the specific game.

**Comment by fabricecaruso** [comment]
done

**Comment by pajarorrojo** [comment]
Tested! works fine!! good job @fabricecaruso!

This feature can also be very good to implement ... IMO:
"When I choose to scrape, it doesn't give me any options and it goes directly to scrape all the data. This is another thread but I think it would be good to also show the scraper options screen before scraping a single game, as in global scraping, choosing which data or media to download and which to discard before starting to scrape the specific game."
