### ISSUE TITLE
Enhancement: ES theming: control sound of videos with an xml tag

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#871]
I think it would be very positive for theme developing the possibility to control the volume of videos with an xml tag <volume> or simply <mute>, this would be wonderful for theme design purposes like background custom videos where sound may not be so necessary.

Something like?:
```
<mute>boolean true/false</mute> 
<volume>integer value 0 to 100</volume> 
```

Just ideas! ;) Thanks again for the hard work!!

**Comment by fabricecaruso** [comment]
mute function already exists using <audio>false</audio>
Volume : no interest.

**Comment by pajarorrojo** [comment]
> mute function already exists using false
You mean the general option to activate or deactivate volume?

**Comment by fabricecaruso** [comment]
no. in themes

**Comment by pajarorrojo** [comment]
[](https://wiki.batocera.org/write_themes_for_emulationstation)

i have checked the wiki again and i dont see it.

for example:

```
<video name "custom-video" extra = "true">
   <mute> true </mute>
</video>
```

You mean that would be the correct way?

**Comment by pajarorrojo** [comment]
> mute function already exists using `<audio>false</audio>`


Im so happy now!!! Thanks Fabrice!!
