### ISSUE TITLE
AUTO LOAD/SAVE = OFF will load file if autostate is available

### ISSUE THREAD

**Issue by crcerror** [batocera-linux/batocera-emulationstation#874]
At first nice work on the latest ES.
I'm testing on Pi3 with 05/05 build so maybe the bug has been solved meanwhile

If you select a new game the menu will appear that lets you select **NEW GAME** and **NEW AUTOSAVE**
Now you terminate the game with button-combo and the autosave will be created.

Now you go to the core options and disable AUTOSAVE (or better set AUTOSAVE=OFF)
You start the game again and the menu with the selection won't appear, but the autostate will still be loaded.

This can cause crashes if the lr-core of the specific emulator was updated and the autosave is loaded by mistake.

**Comment by fabricecaruso** [comment]
I don't reproduce. There's something in your settings... Please be more precise about everything you did. What setting you have (global/core), Which version you use, Which system....

**Comment by crcerror** [comment]
Arghh! It was set as global! I'm sorry!
