### ISSUE TITLE
Add "Analog to Digital Type" option in ES

### ISSUE THREAD

**Issue by iconoclusterdotexe** [batocera-linux/batocera-emulationstation#893]
Hello.
An "Analog to Digital Type" option in ES can be a good idea.
I've tried a small simple and raw test code to use with a single core in libretroConfig.py and it works:

>     # Analog to Digital option
>     if system.isOptSet("analog2digital"):
>         if system.config["analog2digital"] == "leftanalog":
>             retroarchConfig['input_player1_analog_dpad_mode'] = '1'
>             retroarchConfig['input_player2_analog_dpad_mode'] = '1'
>             retroarchConfig['input_player3_analog_dpad_mode'] = '1'
>             retroarchConfig['input_player4_analog_dpad_mode'] = '1'
>         elif system.config["analog2digital"] == "rightanalog":
>             retroarchConfig['input_player1_analog_dpad_mode'] = '2'
>             retroarchConfig['input_player2_analog_dpad_mode'] = '2'
>             retroarchConfig['input_player3_analog_dpad_mode'] = '2'
>             retroarchConfig['input_player4_analog_dpad_mode'] = '2'
>         elif system.config["analog2digital"] == "none":
>             retroarchConfig['input_player1_analog_dpad_mode'] = '0'
>             retroarchConfig['input_player2_analog_dpad_mode'] = '0'
>             retroarchConfig['input_player3_analog_dpad_mode'] = '0'
>             retroarchConfig['input_player4_analog_dpad_mode'] = '0'
>     else:
>         retroarchConfig['input_player1_analog_dpad_mode'] = '0'
>         retroarchConfig['input_player2_analog_dpad_mode'] = '0'
>         retroarchConfig['input_player3_analog_dpad_mode'] = '0'
>         retroarchConfig['input_player4_analog_dpad_mode'] = '0'

Anyway it needs to be short, maybe by using a counter to 16 players. But i don't want to add in every single core, i want to be used in general "Game Settings", maybe related with standalone emulators too (I don't remeber if duckstation, redream or flycast have a similar option to use) and i think for you @fabricecaruso it can be simple to do. 😎

**Comment by fabricecaruso** [comment]
Not related to Emulationstation, but to batocera.linux @Darknior : this one is for you.
