### ISSUE TITLE
Feature Request: Tell user the version to download

### ISSUE THREAD

**Issue by crcerror** [batocera-linux/batocera-emulationstation#898]
I removed the info message from Shell-output as users/dev have full control over content to download.

This is not possible in ES yet. If the download is ongoing there is no information about version number (upgrade/downgrade??).
I know the check in ES is very simple it reads out current version and just compares it with the web version. And if there is a difference than you are told to do an upgrade.

I think the message should simply tell users.
*You are currently on "B30 21-30-04" do you want to install version "B31-dev 21-06-13"* **[yes] [no]**

There should be no info that B30 is lower than B31 or vice versa, but this piece of info will help a lot.

**Comment by fabricecaruso** [comment]
good idea
