### ISSUE TITLE
Math behind the brightness slider has rounding errors

### ISSUE THREAD

**Issue by miwasp** [batocera-linux/batocera-emulationstation#905]
Imagine a device with a max brightness of 255 and you set the current brightness with the slider to 35.
The function SetBrighness in es-app/src/ApiSystem.cpp calculates a value of 89 and inserts it in /sys/class/backlight/backlight/brightness.
The next time the function GetBrighness is called, it calculates a value of 34 for the slider, the next SetBrighness writes 86 to /sys/class/backlight/backlight/brightness, next GetBrighness calculates 33 and so on.

These are rounding errors due to casting the values:
`value = (uint32_t) (value / (float)max * 100.0f); `

This could be fixed by adding 0.5 before casting or use some math round()-function.

**Comment by fabricecaruso** [comment]
So please, PR a fix ;-)

**Comment by miwasp** [comment]
Done
