### ISSUE TITLE
MAME (Current version) Default Controls

### ISSUE THREAD

**Issue by TVsIan** [batocera-linux/batocera-emulationstation#909]
The controls for MAME on x86_64 don't map as expected. By default, the left analog stick is the left/solo joystick, the d-pad is unmapped, and the right joystick is mapped to the face buttons, in the wrong order.

In the libretro MAME versions, both the d-pad and left stick are usable, but not for standalone without remapping. Which would have to be done for every game, since the default.cfg resets on launch.

MAME supports "OR" for controls in the .cfg file, attached is what it looks like after editing the controls in MAME.

[default.cfg.txt](https://github.com/batocera-linux/batocera-emulationstation/files/6612780/default.cfg.txt)

I did see a recent pull to use the d-pad if there's no analog stick available, but having both sets of inputs mapped by default would solve that issue as well as make twinstick games and anything that plays better on d-pad vs stick more playable overall.

While MAME's normal default is just the stick, having both either as the default or an option (possibly l-stick/d-pad/both) would be helpful since the defaults can't be changed here, unlike in Windows.

**Comment by fabricecaruso** [comment]
Not related to EmulationStastion. 
Please close the issue & create a new one in batocera.linux repository.
