### ISSUE TITLE
New variables and ability to load images randomly from a custom directory not only game images.

### ISSUE THREAD

**Issue by arielg77** [batocera-linux/batocera-emulationstation#923]
It would be great if there is a variable that contains the name of the system for a selected game in the detailed and grid views to be able to load a logo of the system to which the selected game belongs.
for example: game.system.name and game.system.fullName 

Other great feature that would be great is the ability to load randomly images from a custom directory not only game images. For example:

`
<view name="detailed, grid">
    
    
    <image>
       
        <path>./assets/${game.system.name}.png</path>
       
    </image>
    
    
    <image>
        
        <path>./assets/banners/${system.theme}/{random}</path>
       
    </image>
   
</view>
`

Thanks!!!

**Comment by pajarorrojo** [comment]
I agree with the system logo thing per game in gamelist, it can be a very good resource, especially in collection lists.

**Comment by fabricecaruso** [comment]
There are dynamic variables now.
