### ISSUE TITLE
ES System not being read correctly

### ISSUE THREAD

**Issue by lilo-san** [batocera-linux/batocera-emulationstation#924]
I was testing a batocera-cha-32-20210625 Beta build for the CHA and for some reason a custom list I have for systems throws errors that don't make sense.

I was working perfectly on batocera-cha-32-20210622 Beta build for the CHA. And is working perfectly on the windows build of EmulationStation but not Batocera.

I have use the same list before on an older Batocera version successfully.

Restarting EmulationStation from the console using batocera-es-swissknive --restart shows:

2021-06-26 15:14:54    ERROR    System "cps1" is missing name, path, extension, or command!
2021-06-26 15:14:54    ERROR    System "cps2" is missing name, path, extension, or command!
2021-06-26 15:14:54    ERROR    System "cps3" is missing name, path, extension, or command!
2021-06-26 15:14:54    ERROR    System "capcom" is missing name, path, extension, or command!

The systems file is copied using wifi and the guest user to: /share/system/config/emulationstation/es_systems_capcom.cfg

Find the systems file attached, just rename from txt to cfg.
[es_systems_capcom.txt](https://github.com/batocera-linux/batocera-emulationstation/files/6720386/es_systems_capcom.txt)

**Comment by lilo-san** [comment]
f.caruso indicated that:
each system must have its own folder
& not be a child of the folder of another system

I can confirm that following those rules it works, I cannot tell why it worked a few days prior.

**Comment by Ntemis** [comment]
Then close this down please
