### ISSUE TITLE
Theming: Set default transition type via theme xml

### ISSUE THREAD

**Issue by pajarorrojo** [batocera-linux/batocera-emulationstation#926]
Hello team. Would it be possible to implement the ability to set the type of transition (fade, instant, etc) from system list to games list via theme xml?

I don't know if it will be very difficult to implement, but I think it would be very positive for the UX in some cases.

Thanks!

**Comment by fabricecaruso** [comment]
Done. 
See this commit : 
https://github.com/batocera-linux/batocera-emulationstation/commit/254b289e2d18b9da6ef2f2c6e9811bed03806bef

**Comment by pajarorrojo** [comment]
Thanks for your work! :)
