### ISSUE TITLE
Chinese texts in a theme can not be wraped automatically. 

### ISSUE THREAD

**Issue by windknight223** [batocera-linux/batocera-emulationstation#939]
Describe the bug
When there are chinese text with no space character in a theme, the chinese text can not be wrapped automatically.

To Reproduce

    Put some chinese text into the description of a game in the gamelist file
    Open ES;
    Go to the detailed view of that game;
    See no wraps for Chinese text.

Expected behavior
The chinese text should be wrapped automatically just like western language.

Additional context
The following snippet could be used for test:

	<desc>一款转换街机游戏，1942年是一款垂直卷轴射击游戏，供一到两名玩家使用。这一年是1942年，你是一个勇敢的超级王牌战斗机飞行员。你在一艘航母上获得并完成每一关，然后起飞去争夺陆地和海洋。在摧毁敌机的某些编队后，你可以收集不同的能量来增加你的火力和生存机会。</desc>

**Comment by fabricecaruso** [comment]
Was fixed in a previous commit
