### ISSUE TITLE
PI4 4GB V31 - Retroachievements trophies do not show up on games list for Nintendo DS games.

### ISSUE THREAD

**Issue by mefaun** [batocera-linux/batocera-emulationstation#960]
When I press "FIND ALL GAMES" in Retroachievements settings in ES, it skips on the Nintendo DS system altogether.
I am running on a PI4 4GB, on Batocera version 31.
My Nintendo DS games are in .nds format. And are cheevos supported.
Selected MelonDS as core emulator, issue still on-going.
Please notice that trophies are not shown on the games list:
![WeChat Image_20210827003918](https://user-images.githubusercontent.com/7518663/131095781-90d28c18-5214-4723-bef6-2ae9d1a20d9c.jpg)
Retroachievements system does work using melonDS, as noted in these images:
![cheevos supported](https://user-images.githubusercontent.com/7518663/131095864-20149bb5-e40a-4ad4-b770-ecd7037f3aac.jpg)
![WeChat Image_20210827011829](https://user-images.githubusercontent.com/7518663/131096182-b11e507b-24ef-4def-b01c-3ebb982b2543.jpg)

**Comment by fabricecaruso** [comment]
@nadenislamarre 
'cheevos' feature is missing on melonds core :
https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulationstation/batocera-es-system/es_features.yml#L265
It should be added since it's supported by the core :
https://docs.libretro.com/library/melonds/

**Comment by lbrpdx** [comment]
Fixed in Batocera 32.
