### ISSUE TITLE
v32 beta Pi4 - Black screen and no audio at first boot

### ISSUE THREAD

**Issue by chippettone** [batocera-linux/batocera-emulationstation#964]
V32 on PI4 - The HDMI1 is automatically selected at the first boot instead of HDMI0. Also there is no audio leaving the option automatically. The sound must be selected in HDMI. In the V31 there was not this problem. Also often the splash does not start and the screen remains black. Disabling the splash starts correctly Batocera.

**Comment by not43s** [comment]
I can second that I had issues with this as well.

**Comment by lbrpdx** [comment]
On Pi4, by default audio is set to 3.5mm jack and you need to set it to HDMI. This is a known issue on v32 (and easy to fix on 1st boot). For more details, please open an issue on https://github.com/batocera-linux/batocera.linux this is not related to EmulationStation.
