### ISSUE TITLE
[xml][metadata] mMetadata.get(MetaDataId::SortName) is retrieving releasedate value instead of the game sort name if not present.

### ISSUE THREAD

**Issue by Langerz82** [batocera-linux/batocera-emulationstation#993]
In MetaData.cpp the call to mMetadata.get(MetaDataId::SortName) is returning releasedate instead of blank if the sortname tag is not present, when releasedate is set.

This is a very bizarre bug that I have come across on the emuelec fork, but I think it might apply here too.

file affected:
https://github.com/batocera-linux/batocera-emulationstation/blob/master/es-app/src/MetaData.cpp

ref:
https://github.com/EmuELEC/emuelec-emulationstation/pull/34

**Comment by Langerz82** [comment]
Sorry its not getName.

I'll give you an example of our code, and what is the issue. In FileData.cpp we have the following to get the sortname in the xml like so.
```
const std::string FileData::getSortName() const
{
	return mMetadata.get(MetaDataId::SortName);
}
```
The issue is the when the sortname xml tag is not supplied, it's defaulting to the value in releasedate. I can't find the code responsible for backfalling to releasedate, but its breaking some of our code.
I know it's a different fork, but maybe it's a deeper issue on your code base too.

**Comment by Langerz82** [comment]
Not sure if related, but following line:
https://github.com/batocera-linux/batocera-emulationstation/blob/4bd220c1ef5ad58005124e7ab875bf7a1ff190fb/es-app/src/MetaData.cpp#L300

Should be:
```
if (mType == GAME_METADATA && id == MetaDataId::Players && Utils::String::startsWith(value, "1-")) // "players"
```

**Comment by fabricecaruso** [comment]
SortName Metadata does not exist in batocera-emulationstation.
Does not apply here.

**Comment by Langerz82** [comment]
My apologies, the new sort order was pushed onto the sorttype vector out of order on our code, hence it sorting incorrectly. sorry too bother you guys.
